const fs = require('fs');
const path = require('path');
const { createQuestion } = require('./bank_factory');

function getLogicQuestions() {
  const q = [];
  // Midterm: 32 Questions
  // Boolean algebra, basic gates, simplification, K-maps, decoders, multiplexers, adders
  const midRaw = [
    ["Which Boolean law states that A + A'B = A + B?", "Redundancy Law (or Absorption Law variation)", "De Morgan's Law", "Involution Law", "Idempotent Law", "By absorption/simplification: A + A'B = (A + A')(A + B) = 1*(A + B) = A + B."],
    ["What is the dual of the Boolean expression: A + B * C?", "A * (B + C)", "A' + B' * C'", "A' * (B' + C')", "A * B + C", "To find the dual, interchange + and * operators, and interchange 0 and 1 without complementing variables: A*(B+C)."],
    ["Simplify the Boolean function F = A B + A B':", "A", "B", "A + B", "1", "F = A(B + B') = A(1) = A."],
    ["How many minterms are there for a Boolean function of 4 variables?", "16", "8", "4", "32", "For n variables, there are 2^n possible minterms. 2^4 = 16."],
    ["What is the standard POS (Product of Sums) term called?", "Maxterm", "Minterm", "Prime implicant", "Essential implicant", "A sum term that contains all variables (either complemented or uncomplemented) is called a maxterm."],
    ["Which gate is considered a universal gate because any Boolean function can be implemented using only this gate?", "NAND", "XOR", "AND", "OR", "NAND and NOR gates are universal gates because they can realize NOT, AND, and OR operations."],
    ["What is the output of an XOR gate when both inputs are 1 (A = 1, B = 1)?", "0", "1", "Undefined", "High impedance", "XOR output is 1 only when inputs are strictly different. When A=B=1, output is 0."],
    ["In a 3-variable Karnaugh map, how many cells (squares) are there?", "8", "4", "16", "6", "A 3-variable K-map has 2^3 = 8 cells."],
    ["Adjacent cells in a Karnaugh map differ by how many bit positions?", "1 bit (Gray code sequence)", "2 bits", "3 bits", "Any number of bits", "K-maps use Gray code ordering so that adjacent cells differ by exactly one literal/bit."],
    ["In Karnaugh map minimization, a group of 4 adjacent 1s eliminates how many variables?", "2 variables", "1 variable", "3 variables", "4 variables", "A group of 2^k cells eliminates k variables. For 4 cells (2^2), 2 variables are eliminated."],
    ["What is a 'Don't Care' condition in a digital circuit design?", "An input combination that will never occur or whose output value does not matter", "An input that always produces a logic 1", "An input that produces a clock pulse", "A floating CMOS state", "Don't care conditions (X) can be assigned 0 or 1 in K-maps to maximize grouping sizes."],
    ["A half adder adds two 1-bit inputs and produces:", "Sum (A XOR B) and Carry (A AND B)", "Sum (A AND B) and Carry (A OR B)", "Sum (A OR B) and Carry (A XOR B)", "Sum (A XNOR B) and Carry (A AND B)", "A half adder has Sum = A ⊕ B and Carry = A · B."],
    ["How many half adders and OR gates are required to construct a full adder?", "2 half adders and 1 OR gate", "1 half adder and 2 OR gates", "3 half adders and 0 OR gates", "2 half adders and 2 OR gates", "A standard full adder consists of two half adders and one OR gate to combine the carry outputs."],
    ["What is the primary speed limitation in a Ripple Carry Adder?", "Propagation delay of the carry bit through all full adders", "The fan-out of the inputs", "Clock skew", "Gate leakage current", "Each stage must wait for the carry-out of the previous stage, causing a linear delay O(n)."],
    ["Which type of adder overcomes the ripple carry delay by computing carries in parallel?", "Carry Lookahead Adder", "Serial Adder", "BCD Adder", "Ripple Counter Adder", "Carry lookahead adders calculate carry generate (G) and carry propagate (P) to compute all carries simultaneously."],
    ["A 3-to-8 line decoder has how many input lines and output lines?", "3 inputs and 8 outputs", "8 inputs and 3 outputs", "3 inputs and 3 outputs", "8 inputs and 8 outputs", "An n-to-2^n decoder has n input lines and 2^n output lines."],
    ["Which device selects one of many analog or digital input signals and forwards it into a single output line?", "Multiplexer (MUX)", "Demultiplexer (DEMUX)", "Encoder", "Decoder", "A multiplexer acts as a digitally controlled multi-position switch."],
    ["How many select lines are required for a 16-to-1 multiplexer?", "4 select lines", "3 select lines", "5 select lines", "8 select lines", "For 2^n inputs, n select lines are required. Since 16 = 2^4, 4 select lines are needed."],
    ["Can any Boolean function of n variables be implemented using a 2^n-to-1 multiplexer directly?", "Yes, by connecting function truth table values to data inputs", "No, multiplexers can only do routing", "Only if the function is symmetric", "Only for POS forms", "A 2^n-to-1 MUX can implement any n-variable function by connecting variables to select lines and minterms to data inputs."],
    ["A priority encoder resolves which problem found in standard binary encoders?", "Multiple active inputs simultaneously", "Propagation delay", "Power dissipation", "Floating outputs", "A priority encoder outputs the binary code of the active input with the highest priority."],
    ["What is the 2's complement of the 8-bit binary number 0000 1100 (decimal 12)?", "1111 0100", "1111 0011", "0000 1101", "1111 1100", "1's complement of 00001100 is 11110011. Adding 1 gives 11110100 (-12 in 2's complement)."],
    ["What is the range of signed integers that can be represented with 8 bits in 2's complement?", "-128 to +127", "-127 to +128", "-256 to +255", "-127 to +127", "For n bits, the 2's complement signed range is -2^(n-1) to 2^(n-1) - 1. For n=8: -128 to +127."],
    ["What is the result of binary addition 1011 + 0110?", "10001", "10010", "10000", "01111", "1011 (11) + 0110 (6) = 10001 (17)."],
    ["Convert decimal 29 into binary:", "11101", "11011", "10111", "11110", "29 = 16 + 8 + 4 + 1 = 11101 in binary."],
    ["Convert binary 11010111 to hexadecimal:", "D7", "B7", "E7", "C7", "Split into nibbles: 1101 = D (13), 0111 = 7. Result: D7."],
    ["Which code represents each decimal digit by a 4-bit binary sequence?", "BCD (Binary Coded Decimal)", "Gray code", "Excess-3", "ASCII", "BCD represents each decimal digit from 0 to 9 using 4 binary bits (0000 to 1001)."],
    ["In Gray code, what is the main characteristic when progressing from one number to the next?", "Only one bit changes at a time", "All bits invert", "Two bits change at a time", "It follows standard binary weight", "Gray code is an unweighted code where successive values differ by only a single bit, preventing glitches."],
    ["What is the output equation of a 2-input XNOR gate?", "F = A' B' + A B", "F = A' B + A B'", "F = A + B", "F = (A + B)'", "XNOR is the equivalence gate, giving 1 when inputs are equal: F = A B + A' B'."],
    ["According to De Morgan's theorem, (A + B + C)' is equal to:", "A' · B' · C'", "A' + B' + C'", "(A · B · C)'", "A · B · C", "De Morgan's theorem states: The complement of a sum equals the product of the complements."],
    ["Simplify: (X + Y)(X + Y'):", "X", "Y", "X + Y", "0", "Using distribution: X + Y Y' = X + 0 = X."],
    ["What is the minimum number of NAND gates required to implement a 2-input XOR gate?", "4", "3", "5", "6", "A 2-input XOR requires exactly 4 two-input NAND gates."],
    ["Which logic family is known for the lowest static power consumption?", "CMOS", "TTL", "ECL", "RTL", "CMOS circuits draw virtually zero static current because complementary transistors are never on simultaneously in steady state."]
  ];

  midRaw.forEach((m, idx) => {
    q.push(createQuestion(`LOGIC-MID-${String(idx+1).padStart(3, '0')}`, 'subj-logic', false, m[0], m[1], m[2], m[3], m[4], m[5], 'Medium', 'Digital Design Midterm Exam.pdf', idx));
  });

  // Final: 52 Questions
  // Sequential circuits, latches, flip-flops, registers, counters, state machines, memory
  const finRaw = [
    ["What distinguishes a sequential circuit from a combinational circuit?", "Sequential circuits contain memory elements and their outputs depend on past inputs", "Sequential circuits contain only logic gates with no feedback", "Combinational circuits use clock pulses", "Sequential circuits cannot implement Boolean algebra", "Sequential logic outputs depend on both current inputs and the present state stored in memory elements."],
    ["What is the forbidden (invalid) input condition for an active-HIGH SR latch?", "S = 1, R = 1", "S = 0, R = 0", "S = 1, R = 0", "S = 0, R = 1", "When S=1 and R=1 in an active-high NOR latch, both Q and Q' are forced to 0 simultaneously, violating complementarity and leading to a race condition."],
    ["How does a D flip-flop resolve the invalid state problem of an SR flip-flop?", "By setting R = S' via an inverter, ensuring inputs are never both 1", "By adding an enable line", "By removing the clock input", "By cascading two latches in parallel", "A D flip-flop feeds D to S and D' to R, so S and R can never be equal."],
    ["What is the characteristic equation of a JK flip-flop?", "Q(next) = J Q' + K' Q", "Q(next) = J Q + K Q'", "Q(next) = J' Q + K Q", "Q(next) = D", "When J=1, K=0 => Q=1; J=0, K=1 => Q=0; J=K=0 => Q; J=K=1 => Q'. Thus Q(next) = J Q' + K' Q."],
    ["What happens in a JK flip-flop when both J = 1 and K = 1 upon clock arrival?", "The output toggles (inverts its state)", "The output is set to 1", "The output is cleared to 0", "The circuit enters an undefined state", "When J=1 and K=1, the flip-flop operates in toggle mode: Q(t+1) = Q'(t)."],
    ["What is the characteristic equation of a T flip-flop?", "Q(next) = T ⊕ Q", "Q(next) = T · Q", "Q(next) = T + Q", "Q(next) = T' Q", "A T flip-flop toggles when T=1 and holds when T=0, represented by the XOR operation Q(next) = T ⊕ Q."],
    ["What is 'setup time' (t_su) in a flip-flop?", "The minimum time the data input must remain stable before the clock edge", "The time required for output to change after clock edge", "The minimum clock pulse width", "The time data must be held after the clock edge", "Setup time is the mandatory interval preceding the active clock transition during which input data must be held constant."],
    ["What is 'hold time' (t_h) in a flip-flop?", "The minimum time data input must remain stable after the active clock transition", "The time data must be stable before clock edge", "The delay between Q and Q'", "The reset propagation delay", "Hold time is the duration after the active clock edge during which the data input must not change."],
    ["What happens if setup or hold time requirements are violated in a flip-flop?", "Metastability (the output may oscillate or settle unpredictably)", "The circuit burns out", "The clock frequency increases", "Output immediately goes to logic 1", "Violating timing constraints can drive flip-flop internal nodes into a metastable intermediate voltage."],
    ["In an edge-triggered flip-flop, state transition occurs:", "Only during the rising or falling transition of the clock signal", "Throughout the high level of the clock", "Throughout the low level of the clock", "Continuously regardless of clock", "Edge-triggered devices sample inputs and update outputs strictly at the specified voltage transition."],
    ["A Master-Slave flip-flop is designed specifically to eliminate which problem?", "Race-around condition in level-sensitive latches", "Clock jitter", "Static hazards", "Power consumption", "The master latch isolates the input during clock HIGH while the slave updates output on clock LOW, preventing feedback race-around."],
    ["How many flip-flops are required to construct a Mod-16 counter?", "4 flip-flops", "16 flip-flops", "8 flip-flops", "5 flip-flops", "A counter with mod N requires n flip-flops such that 2^n >= N. For N=16, 2^4 = 16, so 4 flip-flops are needed."],
    ["What is an asynchronous (ripple) counter?", "A counter where the clock of each flip-flop is triggered by the output of the preceding flip-flop", "A counter where all flip-flops share a common clock", "A counter that counts without any clock", "A counter with no propagation delay", "In ripple counters, flip-flops are clocked in cascade, accumulating propagation delays across stages."],
    ["What is the major disadvantage of an asynchronous ripple counter compared to a synchronous counter?", "Accumulation of propagation delay limiting maximum operating frequency", "High circuit complexity", "More flip-flops required", "Inability to count backwards", "Cumulative propagation delay through cascaded flip-flops limits the clock speed and causes output glitches during transitions."],
    ["In a synchronous counter, all flip-flops are clocked by:", "The same common system clock simultaneously", "Cascaded outputs of previous flip-flops", "An asynchronous external pulse generator", "A ripple carry chain", "Synchronous counters connect the clock input of every flip-flop to the master clock line simultaneously."],
    ["A Mod-10 counter is also commonly known as a:", "Decade counter (or BCD counter)", "Ring counter", "Johnson counter", "Hexadecimal counter", "A counter with 10 distinct states (0 through 9) is called a decade counter or BCD counter."],
    ["How many unused (illegal) states are there in a standard 4-bit BCD counter?", "6 states (1010 to 1111)", "10 states", "4 states", "8 states", "A 4-bit register has 16 states. BCD uses 10 states (0 to 9), leaving 16 - 10 = 6 unused states."],
    ["How many states does an n-bit Ring Counter have?", "n states", "2^n states", "2n states", "n - 1 states", "An n-bit ring counter circulates a single 1 through n flip-flops, yielding exactly n valid states."],
    ["How many states does an n-bit Johnson (twisted ring) Counter have?", "2n states", "n states", "2^n states", "n^2 states", "A Johnson counter feeds the inverted output Q' of the last stage back to the first, producing 2n distinct states."],
    ["What type of shift register takes data serially on one line and outputs all bits in parallel?", "SIPO (Serial-In Parallel-Out)", "SISO (Serial-In Serial-Out)", "PISO (Parallel-In Serial-Out)", "PIPO (Parallel-In Parallel-Out)", "SIPO registers shift data in bit-by-bit serially and provide immediate parallel access to all register stages."],
    ["What is a Mealy state machine?", "A finite state machine whose outputs depend on both present state and current inputs", "A machine whose outputs depend strictly on present state only", "An asynchronous state machine without a clock", "A machine with no inputs", "In a Mealy machine, output = f(Present State, Current Inputs), allowing faster response but possible input glitches."],
    ["What is a Moore state machine?", "A finite state machine whose outputs depend only on the present state", "A machine whose outputs depend on inputs directly", "A combinational circuit without states", "A shift register counter", "In a Moore machine, output = f(Present State). Output changes occur synchronously on clock edges."],
    ["Which state machine model typically requires fewer states to implement the same sequential specification?", "Mealy machine", "Moore machine", "Both require identical number of states", "Turing machine", "Mealy machines can generate different outputs for different inputs within the same state, often needing fewer states than Moore machines."],
    ["What is a state transition table?", "A tabular representation showing present state, inputs, next state, and outputs", "A truth table for combinational logic only", "A diagram showing logic gates", "A timing chart of propagation delays", "A state table lists current states and input combinations alongside resulting next states and outputs."],
    ["What is the purpose of state reduction in sequential circuit design?", "To reduce the number of flip-flops and combinational logic required", "To increase clock frequency only", "To convert Mealy to Moore", "To eliminate the clock line", "State reduction combines equivalent states to minimize hardware complexity without changing input-output behavior."],
    ["Two states in a sequential circuit are said to be equivalent if:", "For every possible input sequence, they produce identical outputs and transition to equivalent states", "They have the same name", "They both transition to state 00", "They share the same clock cycle", "States are equivalent if no input sequence can distinguish between them by observing output behavior."],
    ["What is the excitation table of a flip-flop?", "A table showing required inputs for a desired transition from present state to next state", "A table showing next state for given inputs", "A power dissipation chart", "A truth table of an inverter", "Excitation tables specify what inputs (e.g. J, K or D or T) must be applied to drive the flip-flop from Q(t) to Q(t+1)."],
    ["For a JK flip-flop, what are the required inputs J and K to cause a transition from Q = 0 to Q = 1?", "J = 1, K = X (Don't care)", "J = 0, K = 0", "J = 0, K = X", "J = X, K = 0", "To transition 0 -> 1: J must be 1 to set or toggle, while K can be 0 or 1 (Don't care). J=1, K=X."],
    ["For a JK flip-flop, what are the required inputs J and K for a transition from Q = 1 to Q = 1 (hold 1)?", "J = X, K = 0", "J = 1, K = X", "J = 0, K = 1", "J = 1, K = 1", "To maintain 1: J can be 0 (hold) or 1 (set), while K must be 0 (prevent reset/toggle). Thus J=X, K=0."],
    ["For a T flip-flop, what is the required input T for a transition from Q = 1 to Q = 0?", "T = 1", "T = 0", "T = X", "T = clock", "Since the state changes from 1 to 0, a toggle is required: T = 1."],
    ["What is a static-1 hazard in combinational logic?", "A temporary glitch to 0 when the output is expected to remain 1", "A glitch to 1 when output should be 0", "A permanent stuck-at-1 fault", "A clock skew glitch", "A static-1 hazard occurs when an output momentarily drops to 0 due to unequal path delays while theoretically remaining 1."],
    ["How can static hazards be eliminated from a two-level sum-of-products circuit?", "By adding redundant consensus terms covering adjacent prime implicants", "By increasing clock speed", "By removing universal gates", "By using only NOR gates", "Adding redundant product terms ensures that transitions between adjacent K-map groupings do not cause momentary 0 outputs."],
    ["What is the fundamental difference between a PAL (Programmable Array Logic) and a PLA (Programmable Logic Array)?", "PAL has a programmable AND array and fixed OR array; PLA has programmable AND and programmable OR arrays", "PLA has fixed AND array; PAL has fixed OR array", "PAL is volatile; PLA is non-volatile", "PLA cannot implement sum-of-products", "PLA offers dual programmability (both AND and OR planes), whereas PAL has a programmable AND plane feeding fixed OR gates."],
    ["In semiconductor memories, what does volatile memory mean?", "Data is lost when power is turned off", "Data is permanently retained", "Data can only be written once", "Memory operates without a clock", "Volatile memories like SRAM and DRAM require continuous power to retain stored bits."],
    ["What is the primary memory cell mechanism used in Dynamic RAM (DRAM)?", "A single transistor and a storage capacitor", "A 6-transistor cross-coupled latch", "Floating gate avalanche injection", "Magnetic flux loop", "DRAM stores charge on a tiny capacitor accessed via an NMOS pass transistor, requiring periodic refreshing."],
    ["Why does DRAM require periodic refreshing?", "Because charge stored in the memory cell capacitor leaks away over time", "To reset the address decoder", "To prevent thermal breakdown", "To clear old data bits", "Capacitor dielectric leakage discharges the cell within milliseconds, requiring read-and-rewrite refresh cycles."],
    ["Static RAM (SRAM) memory cells typically use:", "A bistable latch consisting of 4 or 6 CMOS transistors", "A capacitor and a single transistor", "Magnetic cores", "Optical junctions", "SRAM uses cross-coupled CMOS inverters forming a stable latch that retains state without refresh as long as powered."],
    ["What is the total storage capacity of a memory chip with 12 address lines and 8 data lines?", "4096 bytes (4 KB)", "1024 bytes (1 KB)", "8192 bytes (8 KB)", "2048 bytes (2 KB)", "12 address lines address 2^12 = 4096 locations. Each location stores 8 bits (1 byte), giving 4096 bytes = 4 KB."],
    ["What is the function of a tri-state buffer in digital bus architecture?", "It provides three output states: High (1), Low (0), and High-Impedance (Hi-Z)", "It amplifies voltage by 3x", "It acts as a ternary logic gate", "It delays signals by 3 clock cycles", "Tri-state outputs allow multiple devices to connect to a shared data bus by putting inactive devices into high-impedance state."],
    ["In digital IC specifications, what is 'fan-out'?", "The maximum number of standard logic inputs that an output can drive reliably", "The cooling requirement of the chip", "The maximum number of inputs connected to a gate", "The propagation delay ratio", "Fan-out defines how many input loads a gate output can switch while maintaining valid logic voltage levels."],
    ["What is 'noise margin' in digital logic gates?", "The maximum extraneous noise voltage added to an input that does not cause an undesirable change in circuit output", "The sound level generated by switching", "The ripple voltage on the power supply", "The ground bounce duration", "Noise margin quantifies gate tolerance against spurious electromagnetic noise: NM_H = V_OH - V_IH and NM_L = V_IL - V_OL."],
    ["In CMOS logic, why is the PMOS transistor size typically wider than the NMOS transistor size?", "Because hole mobility in silicon is lower than electron mobility", "To handle higher current density", "To decrease input capacitance", "Because PMOS has higher breakdown voltage", "Electrons in silicon have ~2.5x higher mobility than holes; PMOS channel width is made wider to balance rise and fall propagation delays."],
    ["What is an essential prime implicant in a Karnaugh map?", "A prime implicant that covers at least one minterm not covered by any other prime implicant", "Any prime implicant with 4 terms", "A minterm that cannot be grouped", "A prime implicant that contains don't cares", "Essential prime implicants are mandatory in the minimal sum of products because they alone cover specific minterms."],
    ["Which code is commonly used in optical shaft encoders to prevent erroneous multi-bit readings during rotation?", "Gray code", "Standard binary", "Excess-3", "BCD", "Gray code guarantees that only a single track bit changes between adjacent sectors, eliminating positioning errors caused by sensor misalignment."],
    ["What is the radix (base) of the octal number system?", "8", "16", "2", "10", "Octal has base 8, using digits 0 through 7."],
    ["In a 4-bit ripple carry adder, if each full adder has a delay of 2 ns, what is the total worst-case carry propagation delay?", "8 ns", "2 ns", "4 ns", "16 ns", "Delay = n * delay_per_stage = 4 * 2 ns = 8 ns."],
    ["What type of multivibrator has no stable state and continuously oscillates between two quasi-stable states?", "Astable multivibrator", "Monostable multivibrator", "Bistable multivibrator", "Schmitt trigger", "An astable multivibrator acts as a free-running clock oscillator without requiring external triggers."],
    ["What is a Schmitt trigger inverter used for in digital inputs?", "To convert noisy or slowly changing analog signals into clean, sharp digital transitions using hysteresis", "To invert data with zero delay", "To double the clock frequency", "To store dynamic bits", "The Schmitt trigger features distinct switching thresholds (hysteresis) that reject input noise and sharpen slow edges."],
    ["What is the output frequency of a 4-bit binary ripple counter clocked with a 16 MHz signal?", "1 MHz", "4 MHz", "8 MHz", "2 MHz", "Each flip-flop divides the frequency by 2. A 4-bit counter divides frequency by 2^4 = 16. 16 MHz / 16 = 1 MHz."],
    ["In asynchronous design, what is a 'critical race' condition?", "A state transition where the final stable state depends on which internal variable changes first, leading to erratic operation", "A race between two clock lines", "A condition where outputs toggle at maximum speed", "A non-critical harmless glitch", "In a critical race, unequal path delays between multiple updating state variables can cause the circuit to enter an unintended stable state."],
    ["What is an algorithmic state machine (ASM) chart primarily used for?", "Describing the flow of control and hardware operations in a digital system step-by-step", "Designing PCB board layouts", "Calculating transistor gate dimensions", "Simulating analog frequency response", "ASM charts visually specify complex digital hardware control logic, states, conditional outputs, and branch conditions."],
    ["What is the primary function of a lookahead carry generator (LCG)?", "To compute all stage carries directly from generate and propagate signals in constant time", "To store data bits in registers", "To invert sum outputs", "To multiplex data lines", "The LCG computes carries for 4 or more bits simultaneously via two-level logic, eliminating sequential carry ripple delay."]
  ];

  finRaw.forEach((m, idx) => {
    q.push(createQuestion(`LOGIC-FIN-${String(idx+1).padStart(3, '0')}`, 'subj-logic', true, m[0], m[1], m[2], m[3], m[4], m[5], 'Medium', 'Digital Logic Final Exam.pdf', idx));
  });

  return q;
}

function getSignalsQuestions() {
  const q = [];
  // Midterm: 32 Questions
  // Continuous & discrete time, elementary signals, transformations, linearity, time-invariance, causality, stability, convolution, CTFS
  const midRaw = [
    ["Which of the following signals is a continuous-time energy signal?", "A rectangular pulse of finite duration and amplitude", "A continuous cosine wave cos(10t)", "A unit step function u(t)", "A ramp function r(t)", "Energy E = ∫ |x(t)|^2 dt is finite for pulses of bounded duration and amplitude, while periodic signals have infinite energy and finite power."],
    ["What is the total energy E of the signal x(t) = e^(-2t) * u(t)?", "1/4", "1/2", "1", "2", "E = ∫_0^∞ (e^(-2t))^2 dt = ∫_0^∞ e^(-4t) dt = [-e^(-4t)/4]_0^∞ = 1/4."],
    ["What is the average power P of a periodic sinusoid x(t) = A * cos(ω_0 t + θ)?", "A^2 / 2", "A^2", "A / 2", "A^2 / 4", "The average power of any sinusoidal waveform with peak amplitude A over a period is P = (A / √2)^2 = A^2 / 2."],
    ["What is the sifting property of the Dirac delta function δ(t)?", "∫ x(t) δ(t - t_0) dt = x(t_0)", "∫ x(t) δ(t - t_0) dt = δ(t_0)", "x(t) * δ(t) = 0", "d/dt [δ(t)] = u(t)", "The sifting property extracts the exact value of the integrand at the point where the impulse argument becomes zero: x(t_0)."],
    ["What is the relationship between the unit impulse function δ(t) and the unit step function u(t)?", "δ(t) = d/dt [u(t)]", "u(t) = d/dt [δ(t)]", "δ(t) = u(t) * u(t)", "δ(t) = ∫ u(t) dt", "The unit step is the integral of the unit impulse, and the unit impulse is the distributional derivative of the unit step."],
    ["A continuous-time signal x(t) is defined as an EVEN signal if it satisfies:", "x(-t) = x(t)", "x(-t) = -x(t)", "x(t) = x(t + T)", "x(-t) = 0", "An even signal exhibits mirror symmetry across the vertical axis: x(-t) = x(t)."],
    ["What is the odd part x_odd(t) of any general signal x(t)?", "(x(t) - x(-t)) / 2", "(x(t) + x(-t)) / 2", "x(t) * x(-t)", "x(t) - x(0)", "Any signal can be uniquely decomposed into even and odd components: x_odd(t) = (x(t) - x(-t)) / 2."],
    ["If x(t) is shifted to x(t - 3), this represents:", "A time delay of 3 units (shifted to the right)", "A time advance of 3 units (shifted to the left)", "A time expansion by factor 3", "An amplitude attenuation by 3", "Replacing t with (t - t_0) with t_0 > 0 shifts the waveform to the right along the time axis by t_0 units."],
    ["Given a signal x(t), the transformed signal x(2t) corresponds to:", "Time compression by a factor of 2", "Time expansion by a factor of 2", "Amplitude doubling", "Time shift by 2", "Scaling the independent variable by a factor a > 1 compresses the signal horizontally along the time axis by 1/a."],
    ["Is the continuous-time signal x(t) = cos(4π t) + sin(6π t) periodic, and what is its fundamental period T_0?", "Periodic with T_0 = 1 s", "Periodic with T_0 = 2 s", "Periodic with T_0 = 0.5 s", "Non-periodic", "ω_1 = 4π => T_1 = 2π/(4π) = 0.5 s. ω_2 = 6π => T_2 = 2π/(6π) = 1/3 s. LCM(1/2, 1/3) = 1 s."],
    ["What is the condition for a discrete-time sinusoid x[n] = cos(ω_0 n) to be periodic?", "ω_0 / (2π) must be a rational number", "ω_0 must be an integer", "Any discrete sinusoid is always periodic", "ω_0 must be greater than π", "Unlike continuous sinusoids, discrete-time sinusoids are periodic if and only if the cyclic frequency f_0 = ω_0 / (2π) = m / N is rational."],
    ["A system described by y(t) = 3 x(t) + 5 is:", "Nonlinear and time-invariant", "Linear and time-invariant", "Linear and time-variant", "Nonlinear and time-variant", "Zero input gives y(0) = 5 ≠ 0, violating homogeneity (superposition). Thus it is nonlinear, but time-invariant."],
    ["A system described by y(t) = t * x(t) is:", "Linear and time-variant", "Linear and time-invariant", "Nonlinear and time-invariant", "Nonlinear and time-variant", "It satisfies superposition: a x_1(t) + b x_2(t) -> a t x_1(t) + b t x_2(t). However, time delay test fails: delayed input gives t x(t-t_0) != (t-t_0) x(t-t_0)."],
    ["A continuous-time system is defined as CAUSAL if:", "The output at any time depends only on present and past inputs", "The output depends on future inputs", "The impulse response is non-zero for t < 0", "The system has infinite memory", "Causality means the system cannot predict future inputs: y(t) depends solely on x(τ) for τ ≤ t."],
    ["What is the necessary and sufficient condition for a continuous-time LTI system to be BIBO stable?", "∫_{-∞}^∞ |h(t)| dt < ∞ (impulse response is absolutely integrable)", "h(t) must be periodic", "h(0) = 0", "H(0) = 1", "Bounded-Input Bounded-Output stability requires the impulse response h(t) to be absolutely integrable."],
    ["What is the convolution of any signal x(t) with a shifted impulse δ(t - t_0)?", "x(t - t_0)", "x(t) + δ(t - t_0)", "x(t_0)", "x(t) * t_0", "Convolving with an impulse reproduces the original signal shifted to the location of the impulse: x(t) * δ(t - t_0) = x(t - t_0)."],
    ["Compute the convolution of x(t) = u(t) with h(t) = u(t):", "t * u(t) (a unit ramp function r(t))", "u(t)", "δ(t)", "t^2 * u(t)", "y(t) = ∫_0^t 1 * 1 dτ = t for t ≥ 0, which is the unit ramp function r(t) = t u(t)."],
    ["Which property of convolution states that x(t) * h(t) = h(t) * x(t)?", "Commutative property", "Associative property", "Distributive property", "Linearity property", "Convolution is commutative; the order of input and impulse response can be interchanged without affecting output."],
    ["If two LTI systems with impulse responses h_1(t) and h_2(t) are connected in CASCADE (series), the overall impulse response is:", "h_1(t) * h_2(t) (convolution)", "h_1(t) + h_2(t)", "h_1(t) · h_2(t)", "h_1(t) / h_2(t)", "Cascaded LTI systems have an overall impulse response equal to the convolution of their individual impulse responses."],
    ["If two LTI systems with impulse responses h_1(t) and h_2(t) are connected in PARALLEL, the overall impulse response is:", "h_1(t) + h_2(t)", "h_1(t) * h_2(t)", "h_1(t) · h_2(t)", "max(h_1, h_2)", "Parallel connected systems receive the same input and their outputs are summed: h(t) = h_1(t) + h_2(t)."],
    ["What are the Dirichlet conditions for the existence of the Fourier Series of a periodic signal x(t)?", "x(t) must be absolutely integrable over a period, have a finite number of maxima/minima, and finite discontinuities", "x(t) must be an even function with no poles", "x(t) must have infinite energy", "x(t) must be differentiable at every point", "Dirichlet conditions guarantee convergence of CTFS except at points of discontinuity where it converges to the midpoint."],
    ["In the exponential Fourier series x(t) = Σ a_k e^(j k ω_0 t), what does the coefficient a_0 represent?", "The DC (average) value of the signal over one period", "The peak-to-peak amplitude", "The total power of the harmonics", "The fundamental frequency", "a_0 = (1/T) ∫_T x(t) dt, which is exactly the average or DC component of the periodic waveform."],
    ["If a periodic signal x(t) is real and even, its Fourier series coefficients a_k are:", "Purely real and even", "Purely imaginary and odd", "Complex conjugates", "Zero for all k", "Symmetry properties state: real and even signals have purely real and even Fourier coefficients."],
    ["If a periodic signal x(t) is real and odd, its Fourier series coefficients a_k are:", "Purely imaginary and odd", "Purely real and even", "Zero for all odd harmonics", "Constant real numbers", "Real and odd signals produce purely imaginary and odd Fourier series coefficients."],
    ["What does Parseval's theorem for Fourier series state?", "The average power of a periodic signal equals the sum of the squared magnitudes of its harmonic coefficients", "Power is conserved only in LTI filters", "Energy equals the Fourier transform at ω = 0", "Fourier coefficients are bounded by 1", "Parseval's relation: P = (1/T) ∫_T |x(t)|^2 dt = Σ_{-∞}^∞ |a_k|^2."],
    ["What is the response of a stable LTI system to a complex exponential input x(t) = e^(s t)?", "y(t) = H(s) e^(s t), where H(s) is the eigenvalue (transfer function)", "y(t) = e^(s t) / s", "y(t) = s * e^(s t)", "y(t) = 0", "Complex exponentials are eigenfunctions of LTI systems; the output is the same exponential scaled by the complex eigenvalue H(s)."],
    ["A causal discrete-time LTI system with impulse response h[n] is BIBO stable if:", "Σ_{n=-∞}^∞ |h[n]| < ∞", "h[n] = 0 for n > 0", "h[0] = 1", "Σ h[n]^2 = 0", "Discrete BIBO stability requires absolute summability of the unit impulse response."],
    ["What is the step response s(t) of an LTI system with impulse response h(t)?", "s(t) = ∫_{-∞}^t h(τ) dτ", "s(t) = d/dt [h(t)]", "s(t) = h(t) * δ(t)", "s(t) = h(t) / t", "Because u(t) is the integral of δ(t), linearity implies that the step response is the running integral of the impulse response."],
    ["What is the fundamental frequency ω_0 of the signal x(t) = 5 cos(50π t)?", "50π rad/s (or f_0 = 25 Hz)", "25 rad/s", "100π rad/s", "5 rad/s", "In cos(ω_0 t), the coefficient multiplying t inside the argument is ω_0 = 50π rad/s."],
    ["Compute the discrete-time convolution of x[n] = {1, 2} with h[n] = {1, 1}:", "{1, 3, 2}", "{1, 2, 2}", "{2, 3, 1}", "{1, 1, 2}", "Convolution: y[0]=1*1=1, y[1]=1*1 + 2*1=3, y[2]=2*1=2. Result: {1, 3, 2}."],
    ["What is the length of the convolution of a sequence of length L_1 with a sequence of length L_2?", "L_1 + L_2 - 1", "L_1 + L_2", "L_1 * L_2", "max(L_1, L_2)", "The non-zero duration of the discrete convolution of two finite sequences is L_1 + L_2 - 1."],
    ["A system is memoryless (static) if:", "The output at any instant depends only on the input at that same instant", "The output depends on the derivative of input", "The impulse response has infinite duration", "The system contains inductors and capacitors", "A memoryless system has y(t) = f(x(t)), meaning it does not retain any past history of inputs."]
  ];

  midRaw.forEach((m, idx) => {
    q.push(createQuestion(`SIGNALS-MID-${String(idx+1).padStart(3, '0')}`, 'subj-signals', false, m[0], m[1], m[2], m[3], m[4], m[5], 'Medium', 'Signals & Systems Midterm.pdf', idx));
  });

  // Final: 52 Questions
  // CTFT, DTFT, Laplace Transform, ROC, Z-Transform, Frequency Response, Sampling Theorem
  const finRaw = [
    ["What is the Continuous-Time Fourier Transform (CTFT) of the Dirac delta function δ(t)?", "1", "2π δ(ω)", "1 / (jω)", "0", "F{δ(t)} = ∫_{-∞}^∞ δ(t) e^(-jω t) dt = e^0 = 1 for all frequencies."],
    ["What is the CTFT of the constant signal x(t) = 1?", "2π δ(ω)", "1", "1 / (jω)", "δ(ω)", "By duality with F{δ(t)} = 1, the Fourier transform of a DC signal 1 is 2π δ(ω)."],
    ["What is the CTFT of x(t) = e^(-a t) u(t) where a > 0?", "1 / (a + jω)", "1 / (a - jω)", "a / (a^2 + ω^2)", "1 / (jω)", "∫_0^∞ e^(-a t) e^(-jω t) dt = ∫_0^∞ e^(-(a + jω)t) dt = 1 / (a + jω)."],
    ["According to the time-shifting property of the CTFT, F{x(t - t_0)} equals:", "e^(-jω t_0) X(jω)", "e^(jω t_0) X(jω)", "X(j(ω - t_0))", "X(jω) - t_0", "A shift in the time domain corresponds to multiplying by a linear phase shift e^(-jω t_0) in the frequency domain."],
    ["According to the frequency-shifting (modulation) property of the CTFT, F{x(t) e^(j ω_0 t)} equals:", "X(j(ω - ω_0))", "X(j(ω + ω_0))", "e^(-j ω_0 t) X(jω)", "ω_0 X(jω)", "Multiplication by a complex exponential in time shifts the spectrum in frequency: X(j(ω - ω_0))."],
    ["What is the CTFT of the derivative of a signal, d/dt [x(t)]?", "jω X(jω)", "X(jω) / (jω)", "-jω X(jω)", "ω^2 X(jω)", "Differentiation in time corresponds to multiplication by jω in the frequency domain."],
    ["What is the convolution property of the Continuous-Time Fourier Transform?", "F{x(t) * h(t)} = X(jω) · H(jω)", "F{x(t) * h(t)} = X(jω) * H(jω)", "F{x(t) * h(t)} = X(jω) + H(jω)", "F{x(t) * h(t)} = (1/2π) X(jω) H(jω)", "Convolution in the time domain corresponds to point-by-point multiplication in the frequency domain."],
    ["What does the multiplication property of the CTFT state: F{x_1(t) · x_2(t)} = ?", "(1 / 2π) [X_1(jω) * X_2(jω)]", "X_1(jω) · X_2(jω)", "2π [X_1(jω) * X_2(jω)]", "X_1(jω) + X_2(jω)", "Multiplication in the time domain transforms into convolution in the frequency domain scaled by 1/(2π)."],
    ["What is the Nyquist sampling rate for a bandlimited continuous signal with maximum frequency f_max = 5 kHz?", "10 kHz (f_s ≥ 2 f_max)", "5 kHz", "2.5 kHz", "20 kHz", "The Nyquist criterion states that the sampling rate must be at least twice the maximum frequency: f_s ≥ 2 * 5 kHz = 10 kHz."],
    ["What phenomenon occurs when a continuous signal is sampled at a rate below its Nyquist rate (f_s < 2 f_max)?", "Aliasing (spectral overlap and distortion)", "Phase inversion", "Gain saturation", "Thermal noise amplification", "Undersampling causes higher frequency components to fold over into the baseband spectrum, creating irreversible aliasing distortion."],
    ["What type of filter is placed before sampling to eliminate frequencies above f_s / 2?", "Anti-aliasing low-pass filter", "High-pass notch filter", "Band-stop comb filter", "Bilinear all-pass filter", "An analog low-pass anti-aliasing filter removes frequency components higher than the Nyquist limit before digitization."],
    ["What is the bilateral Laplace transform of a continuous signal x(t)?", "X(s) = ∫_{-∞}^∞ x(t) e^(-s t) dt, where s = σ + jω", "X(s) = ∫ x(t) e^(s t) dt", "X(s) = Σ x[n] z^(-n)", "X(s) = ∫ x(t) cos(st) dt", "The bilateral Laplace transform generalizes the Fourier transform by evaluating along the complex frequency s = σ + jω."],
    ["What is the Region of Convergence (ROC) in the Laplace transform?", "The range of complex variable s values in the s-plane for which the Laplace integral converges", "The range where X(s) = 0", "The unit circle", "The imaginary axis exclusively", "The ROC comprises all points s in the complex plane where ∫ |x(t) e^(-σ t)| dt is finite."],
    ["What is the Laplace transform of x(t) = e^(-a t) u(t) and its ROC?", "1 / (s + a) with ROC Re{s} > -a", "1 / (s - a) with ROC Re{s} > a", "1 / (s + a) with ROC Re{s} < -a", "s / (s + a) with ROC Re{s} > 0", "∫_0^∞ e^(-(s+a)t) dt = 1/(s+a), requiring Re{s+a} > 0 => Re{s} > -a."],
    ["What is the Laplace transform of the left-sided signal x(t) = -e^(-a t) u(-t) and its ROC?", "1 / (s + a) with ROC Re{s} < -a", "1 / (s + a) with ROC Re{s} > -a", "1 / (s - a) with ROC Re{s} < a", "-1 / (s + a) with entire s-plane", "Left-sided exponential signals yield the same algebraic form 1/(s+a) but with a left-half ROC: Re{s} < -a."],
    ["Can the Region of Convergence (ROC) of a rational Laplace transform contain any poles?", "No, the ROC can never contain any poles", "Yes, poles are always inside the ROC", "Only if the system is stable", "Only simple poles can be in the ROC", "By definition, the Laplace integral diverges at pole locations; hence the ROC cannot contain poles."],
    ["For a causal continuous-time LTI system to be BIBO stable, what must be true about its transfer function poles?", "All poles must lie strictly in the open left-half of the s-plane (Re{s} < 0)", "All poles must lie on the imaginary axis", "All poles must be inside the unit circle", "Poles can be anywhere in the s-plane", "BIBO stability requires the ROC to include the jω axis; for a causal system (right-sided ROC), this means all poles have negative real parts."],
    ["What is the Laplace transform of the Dirac delta function δ(t)?", "1 with ROC of the entire s-plane", "1/s with Re{s} > 0", "0", "s", "The Laplace transform of δ(t) is ∫ δ(t) e^(-st) dt = 1 for all complex s."],
    ["What is the Laplace transform of the unit step function u(t)?", "1 / s with ROC Re{s} > 0", "1 with entire plane", "1 / s^2 with Re{s} > 0", "s", "L{u(t)} = ∫_0^∞ e^(-st) dt = 1/s, valid for Re{s} > 0."],
    ["What is the Initial Value Theorem for the unilateral Laplace transform?", "lim_{t -> 0+} x(t) = lim_{s -> ∞} s * X(s)", "lim_{t -> 0+} x(t) = lim_{s -> 0} s * X(s)", "lim_{t -> 0+} x(t) = lim_{s -> ∞} X(s) / s", "lim_{t -> 0+} x(t) = X(0)", "The Initial Value Theorem allows finding x(0+) directly from the s-domain via lim_{s -> ∞} s X(s)."],
    ["What is the Final Value Theorem for the unilateral Laplace transform (assuming all poles of sX(s) are in the open LHP)?", "lim_{t -> ∞} x(t) = lim_{s -> 0} s * X(s)", "lim_{t -> ∞} x(t) = lim_{s -> ∞} s * X(s)", "lim_{t -> ∞} x(t) = X(0)", "lim_{t -> ∞} x(t) = 1", "The Final Value Theorem computes steady-state value lim_{t->∞} x(t) = lim_{s->0} s X(s) provided the limit exists."],
    ["What is the Discrete-Time Fourier Transform (DTFT) of a sequence x[n]?", "X(e^(jΩ)) = Σ_{n=-∞}^∞ x[n] e^(-jΩ n)", "X(e^(jΩ)) = ∫ x(t) e^(-jΩ t) dt", "X(z) = Σ x[n] z^n", "X(e^(jΩ)) = Σ x[n] cos(Ω n)", "The DTFT maps a discrete sequence to a continuous, periodic function of discrete angular frequency Ω with period 2π."],
    ["What is the periodicity of the DTFT spectrum X(e^(jΩ))?", "Periodic with period 2π", "Periodic with period π", "Aperiodic", "Periodic with period 1", "Because e^(-j(Ω + 2π)n) = e^(-jΩ n) e^(-j 2π n) = e^(-jΩ n), the DTFT is fundamentally 2π-periodic."],
    ["What is the definition of the bilateral z-Transform of a discrete sequence x[n]?", "X(z) = Σ_{n=-∞}^∞ x[n] z^(-n)", "X(z) = Σ x[n] z^n", "X(z) = ∫ x[n] e^(-z n) dn", "X(z) = Σ x[n] / z", "The bilateral z-transform is the discrete counterpart of the Laplace transform, where z = r e^(jΩ)."],
    ["What is the Region of Convergence (ROC) in the z-plane for a right-sided (causal) finite sequence?", "The entire z-plane except possibly z = 0", "The region inside the unit circle", "The region outside the largest pole", "The imaginary axis", "For a causal finite-length sequence, X(z) is a polynomial in z^(-1), which converges everywhere except at z = 0 where terms blow up."],
    ["What is the z-transform of x[n] = a^n u[n] and its ROC?", "1 / (1 - a z^(-1)) = z / (z - a) with ROC |z| > |a|", "1 / (1 + a z^(-1)) with |z| < |a|", "z / (z - a) with |z| < |a|", "1 / (z - a) with entire plane", "Σ_{n=0}^∞ (a z^(-1))^n = 1 / (1 - a z^(-1)) for |a z^(-1)| < 1, which implies |z| > |a| (exterior of circle)."],
    ["What is the z-transform of x[n] = -a^n u[-n - 1] and its ROC?", "z / (z - a) with ROC |z| < |a|", "z / (z - a) with ROC |z| > |a|", "1 / (1 - a z) with |z| > 1", "-z / (z + a) with |z| < |a|", "Left-sided exponential sequences produce the same rational form z/(z-a) but with an interior ROC: |z| < |a|."],
    ["For a causal discrete-time LTI system to be BIBO stable, what must be true about its transfer function poles?", "All poles must lie strictly inside the unit circle (|p_k| < 1)", "All poles must lie outside the unit circle", "All poles must lie on the unit circle", "All poles must have negative real parts", "BIBO stability requires the ROC to encompass the unit circle (|z| = 1); for a causal system (|z| > |p_max|), this requires all poles |p_k| < 1."],
    ["What corresponds to the continuous-time imaginary axis (jω axis) in the discrete-time z-plane?", "The unit circle (|z| = 1)", "The real axis", "The origin (z = 0)", "The circle with radius 2π", "Evaluating the z-transform on the unit circle z = e^(jΩ) yields the Discrete-Time Fourier Transform (DTFT), exactly as evaluating s = jω yields the CTFT."],
    ["What is the z-transform of the unit impulse sequence δ[n]?", "1 with ROC of the entire z-plane", "z / (z - 1)", "0", "z^(-1)", "X(z) = Σ δ[n] z^(-n) = 1 * z^0 = 1 for all complex z."],
    ["What is the z-transform of the discrete unit step sequence u[n]?", "1 / (1 - z^(-1)) = z / (z - 1) with ROC |z| > 1", "z / (z + 1) with |z| > 1", "1 / (z - 1) with |z| < 1", "1 with entire plane", "Applying the standard formula with a = 1 gives z / (z - 1) with ROC |z| > 1."],
    ["According to the time-shifting property of the z-transform, Z{x[n - k]} equals:", "z^(-k) X(z)", "z^k X(z)", "X(z - k)", "X(z / k)", "A delay of k samples in the time domain corresponds to multiplication by z^(-k) in the z-domain."],
    ["What does the convolution property of the z-transform state: Z{x[n] * h[n]} = ?", "X(z) · H(z)", "X(z) * H(z)", "X(z) + H(z)", "z * X(z) H(z)", "Convolution of discrete-time sequences corresponds to algebraic multiplication of their z-transforms."],
    ["What is an ideal low-pass filter's impulse response h(t)?", "A sinc function: h(t) = (ω_c / π) sinc(ω_c t / π)", "A rectangular pulse", "An exponential decay e^(-a t) u(t)", "A Gaussian pulse", "The inverse CTFT of a rectangular frequency passband of width 2ω_c is a sinc function in the time domain."],
    ["Why is an ideal brick-wall low-pass filter physically unrealizable in practice?", "Because its impulse response is non-causal (extends to -∞) and infinite in duration", "Because its frequency response is zero everywhere", "Because it requires infinite power gain", "Because it causes zero phase distortion", "The sinc impulse response is non-zero for t < 0, violating causality; practical filters approximate brick-wall behavior with causal rational transfer functions."],
    ["What is the phase response of a system with pure time delay y(t) = x(t - t_d)?", "Linear phase: θ(ω) = -ω t_d", "Constant phase: θ(ω) = -π/2", "Quadratic phase", "Zero phase for all frequencies", "H(jω) = e^(-jω t_d), so magnitude |H(jω)| = 1 and phase angle θ(ω) = -ω t_d is strictly linear with frequency."],
    ["What is the primary benefit of a filter having a LINEAR PHASE response?", "It introduces a constant group delay across all frequencies, preventing waveform shape distortion", "It eliminates stopband ripple completely", "It provides the sharpest cutoff with minimum order", "It consumes zero power", "Linear phase ensures all frequency components are delayed by the exact same amount of time, preserving pulse shapes."],
    ["What is the group delay τ_g(ω) of a filter with phase response θ(ω)?", "τ_g(ω) = -dθ(ω) / dω", "τ_g(ω) = θ(ω) / ω", "τ_g(ω) = d|H(jω)| / dω", "τ_g(ω) = -∫ θ(ω) dω", "Group delay measures the transit delay of the signal envelope and is defined as the negative derivative of phase with respect to frequency."],
    ["How is the Discrete Fourier Transform (DFT) related to the DTFT?", "The DFT is formed by uniformly sampling the DTFT at N discrete frequency points around the unit circle", "The DFT is continuous in frequency", "The DFT cannot be computed with FFT", "The DFT is identical to the Laplace transform", "The N-point DFT samples X(e^(jΩ)) at Ω_k = 2π k / N for k = 0, 1, ..., N-1."],
    ["What is the computational complexity of computing an N-point DFT directly versus using the Fast Fourier Transform (FFT)?", "O(N^2) directly versus O(N log_2 N) using FFT", "O(N) directly versus O(N^2) with FFT", "O(N log N) directly versus O(N) with FFT", "O(N^3) directly versus O(N^2) with FFT", "Cooley-Tukey FFT algorithm reduces computational operations from N^2 complex multiplications down to (N/2) log_2 N."],
    ["What is a minimum-phase system?", "A causal, stable system whose transfer function has both all poles and all zeros inside the unit circle (or in LHP)", "A system with zero phase response", "A system with the minimum number of poles", "An unstable high-pass filter", "Minimum-phase systems have stable and causal inverses because both poles and zeros reside strictly in the stability region."],
    ["What is an all-pass filter?", "A filter that has constant magnitude |H(jω)| = 1 for all frequencies but modifies phase", "A filter that passes all frequencies with zero phase shift", "An ideal bandpass filter", "A filter with no poles or zeros", "All-pass filters maintain flat unity magnitude across the entire spectrum, serving as pure phase equalizers or delay synthesizers."],
    ["What is the relationship between the impulse response h(t) and the step response s(t) of an LTI system?", "h(t) = d/dt [s(t)]", "h(t) = ∫ s(t) dt", "h(t) = s(t) * u(t)", "h(t) = s(t)^2", "By the derivative property of LTI systems, differentiating the step response yields the impulse response."],
    ["What is the 3-dB cutoff frequency of a first-order low-pass system with transfer function H(s) = 1 / (1 + s τ)?", "ω_c = 1 / τ rad/s", "ω_c = τ rad/s", "ω_c = 2π τ rad/s", "ω_c = 1 / (2π τ) rad/s", "At s = j(1/τ), |H(j/τ)| = 1 / |1 + j| = 1 / √2 ≈ -3.01 dB. Thus ω_c = 1/τ rad/s."],
    ["If the input x(t) to an LTI system is periodic with period T_0, the output y(t) will be:", "Periodic with the exact same fundamental period T_0", "Periodic with period 2 T_0", "Aperiodic", "Decaying to zero", "LTI systems preserve periodicity; each harmonic is simply scaled and phase shifted by H(j k ω_0)."],
    ["What happens in time domain when zero-padding is performed on a discrete signal prior to DFT?", "Frequency spectrum is interpolated with finer resolution (sinc interpolation) without changing underlying spectral content", "Actual spectral resolution increases", "Signal duration decreases", "Signal energy increases", "Zero-padding increases DFT length N, evaluating the DTFT at denser frequency grid points without adding new information."],
    ["What is the Bilinear Transform used for in digital signal processing?", "Mapping analog s-plane transfer functions into digital z-plane filters via s = (2/T)(1 - z^(-1))/(1 + z^(-1))", "Evaluating continuous Fourier transforms", "Computing fast convolutions", "Quantizing ADC bits", "The bilinear transform maps the entire left-half s-plane into the interior of the unit circle, avoiding aliasing."],
    ["What artifact is introduced by the Bilinear Transform that requires pre-warping?", "Nonlinear frequency warping between analog and digital frequency axes (ω and Ω)", "Phase discontinuity at DC", "Amplitude distortion in stopband", "Pole instability", "The nonlinear mapping Ω = 2 arctan(ω T / 2) compresses high frequencies; pre-warping ensures critical frequencies match."],
    ["What is Gibbs phenomenon in Fourier series approximations?", "An overshoot of approximately 9% near step discontinuities that does not vanish as the number of terms approaches infinity", "A decay of high frequency components", "A shift in fundamental frequency", "A roundoff error in FFT", "Truncating Fourier series of a discontinuous signal produces a persistent ~8.95% ripple adjacent to the jump discontinuity."],
    ["What is the z-transform of the ramp sequence x[n] = n * u[n]?", "z^(-1) / (1 - z^(-1))^2 = z / (z - 1)^2 with ROC |z| > 1", "z / (z - 1) with |z| > 1", "1 / (z - 1)^2 with |z| < 1", "z^2 / (z - 1)", "Using the differentiation property -z d/dz [z/(z-1)] gives z / (z - 1)^2."],
    ["What does the circular convolution of two N-point sequences correspond to in the DFT domain?", "Point-wise multiplication of their N-point DFTs", "Linear convolution of their DFTs", "Circular cross-correlation", "Division of their DFTs", "The DFT multiplication property corresponds strictly to circular (periodic) convolution in the time domain, not linear convolution."],
    ["How can linear convolution of two sequences of lengths L and M be computed using circular convolution / FFT?", "By zero-padding both sequences to a length of at least L + M - 1 before taking FFTs", "By computing N-point FFT where N = max(L, M)", "By inverting the phase spectrum", "By taking time derivatives first", "Zero-padding to at least L + M - 1 prevents circular aliasing (wrap-around), making circular convolution identical to linear convolution."]
  ];

  finRaw.forEach((m, idx) => {
    q.push(createQuestion(`SIGNALS-FIN-${String(idx+1).padStart(3, '0')}`, 'subj-signals', true, m[0], m[1], m[2], m[3], m[4], m[5], 'Medium', 'Signals & Systems Final Exam.pdf', idx));
  });

  return q;
}

function getControlQuestions() {
  const q = [];
  // Midterm: 32 Questions
  // Open loop vs closed loop, block diagrams, Mason's rule, first & second order response, stability, Routh-Hurwitz
  const midRaw = [
    ["What is the fundamental difference between an open-loop and a closed-loop control system?", "Closed-loop systems utilize feedback to compare output against input reference, whereas open-loop systems do not", "Open-loop systems use feedback sensors", "Closed-loop systems are always unstable", "Open-loop systems have higher accuracy in presence of disturbances", "Closed-loop systems measure actual output and feed it back to reduce error, making them robust against disturbances and parameter variations."],
    ["What is a transfer function of a linear time-invariant system?", "The ratio of the Laplace transform of the output to the Laplace transform of the input, assuming zero initial conditions", "The ratio of output to input in the time domain", "The Fourier transform of the steady state", "The ratio of input to output with non-zero initial state", "By definition, Transfer Function G(s) = Y(s) / X(s) with all initial conditions set to zero."],
    ["For a negative feedback closed-loop system with forward transfer function G(s) and feedback transfer function H(s), the closed-loop transfer function T(s) is:", "G(s) / (1 + G(s) H(s))", "G(s) / (1 - G(s) H(s))", "(1 + G(s) H(s)) / G(s)", "G(s) · H(s)", "Closed-loop transfer function with negative feedback is T(s) = G(s) / [1 + G(s)H(s)]. With positive feedback, the denominator becomes 1 - GH."],
    ["In Mason's Gain Formula, what does the term Δ (determinant of the graph) represent?", "1 - (sum of all individual loop gains) + (sum of gain products of two non-touching loops) - ...", "The product of all forward path gains", "The sum of all node voltages", "The characteristic frequency of the system", "Δ = 1 - Σ L_i + Σ L_j L_k - Σ L_m L_n L_p ..., representing the system characteristic equation."],
    ["What are two loops in a signal flow graph defined as 'non-touching'?", "When they do not share any common node", "When they have opposite signs", "When their loop gains are equal", "When they both touch the input node", "Non-touching loops are completely isolated from each other, sharing no common node or branch."],
    ["What is the time constant τ of a first-order system with transfer function G(s) = 1 / (s + 5)?", "τ = 1/5 = 0.2 seconds", "τ = 5 seconds", "τ = 2.5 seconds", "τ = 0.5 seconds", "Writing in standard form G(s) = K / (τ s + 1) = (1/5) / ((1/5)s + 1) gives time constant τ = 1/5 = 0.2 s."],
    ["For a first-order system subjected to a unit step input, the output reaches approximately what percentage of its final steady-state value after one time constant (t = τ)?", "63.2%", "50%", "86.5%", "98.2%", "Step response is y(t) = 1 - e^(-t/τ). At t = τ, y(τ) = 1 - e^(-1) = 1 - 0.368 = 0.632 = 63.2%."],
    ["For a standard first-order system, what is the settling time T_s for the 2% criterion?", "4 τ", "τ", "2 τ", "8 τ", "The 2% settling criterion requires e^(-t/τ) ≤ 0.02, which yields t = -ln(0.02) τ ≈ 3.91 τ ≈ 4 τ."],
    ["In the standard second-order transfer function G(s) = ω_n^2 / (s^2 + 2 ζ ω_n s + ω_n^2), what does ζ represent?", "Damping ratio", "Undamped natural frequency", "Damped natural frequency", "Steady-state gain", "ζ (zeta) is the dimensionless damping ratio that characterizes the transient oscillation behavior."],
    ["A second-order system is described as UNDERDAMPED if its damping ratio ζ satisfies:", "0 < ζ < 1", "ζ = 1", "ζ > 1", "ζ = 0", "When 0 < ζ < 1, the characteristic roots are complex conjugates, producing decaying oscillatory responses."],
    ["A second-order system is described as CRITICALLY DAMPED if:", "ζ = 1", "ζ = 0", "ζ > 1", "0 < ζ < 1", "Critical damping (ζ = 1) yields two identical real poles, providing the fastest response without overshoot."],
    ["A second-order system is described as OVERDAMPED if:", "ζ > 1", "ζ = 1", "0 < ζ < 1", "ζ < 0", "When ζ > 1, the poles are real and unequal, resulting in a sluggish, non-oscillatory response."],
    ["What is the damped natural frequency ω_d of an underdamped second-order system?", "ω_d = ω_n √(1 - ζ^2)", "ω_d = ω_n √(ζ^2 - 1)", "ω_d = ζ ω_n", "ω_d = ω_n / √(1 - ζ^2)", "The imaginary part of the complex conjugate poles is ω_d = ω_n √(1 - ζ^2)."],
    ["What is the peak time T_p of an underdamped second-order step response?", "T_p = π / ω_d = π / (ω_n √(1 - ζ^2))", "T_p = 2π / ω_n", "T_p = 4 / (ζ ω_n)", "T_p = π / (ζ ω_n)", "The first derivative of step response vanishes at t = π / ω_d, which is the time to reach the first maximum peak."],
    ["What is the formula for the maximum percent overshoot (%OS) of a second-order underdamped system?", "%OS = e^(-π ζ / √(1 - ζ^2)) * 100%", "%OS = e^(-ζ π) * 100%", "%OS = (1 - ζ) * 100%", "%OS = 100% / ζ", "Percent overshoot depends exclusively on the damping ratio ζ: %OS = 100 * exp(-π ζ / √(1 - ζ^2))."],
    ["What is the approximate settling time T_s (2% criterion) for an underdamped second-order system?", "T_s ≈ 4 / (ζ ω_n)", "T_s ≈ π / (ζ ω_n)", "T_s ≈ 1 / (ζ ω_n)", "T_s ≈ 2 / ω_n", "The envelope decays as e^(-ζ ω_n t); reaching 2% residual requires ζ ω_n t ≈ 4 => T_s ≈ 4 / (ζ ω_n)."],
    ["For a unity feedback control system, what is the system 'Type' number?", "The number of pure integrators (poles at s = 0) in the open-loop transfer function G(s)", "The order of the closed-loop characteristic equation", "The number of zeros in G(s)", "The value of damping ratio ζ", "System Type is defined by the number of open-loop poles located exactly at the origin s = 0: G(s) = K / (s^N ...)."],
    ["What is the steady-state error e_ss of a Type 0 system subjected to a unit step input?", "e_ss = 1 / (1 + K_p), where K_p = lim_{s->0} G(s)", "e_ss = 0", "e_ss = ∞", "e_ss = 1 / K_p", "For a unit step 1/s: e_ss = lim_{s->0} s * [1/(1+G(s))] * (1/s) = 1 / (1 + G(0)) = 1 / (1 + K_p)."],
    ["What is the steady-state error of a Type 1 system subjected to a unit step input?", "0", "1 / K_v", "∞", "1 / (1 + K_p)", "A Type 1 system has a pole at s=0, giving position error constant K_p = ∞, hence e_ss = 1 / (1 + ∞) = 0."],
    ["What is the steady-state error of a Type 1 system subjected to a unit ramp input r(t) = t u(t)?", "e_ss = 1 / K_v, where K_v = lim_{s->0} s G(s)", "0", "∞", "1 / K_a", "For ramp input, e_ss = 1 / K_v where velocity error constant K_v = lim_{s->0} s G(s) is finite for Type 1."],
    ["According to the Routh-Hurwitz stability criterion, a system is stable if and only if:", "All elements in the first column of the Routh array are strictly positive (no sign changes)", "The determinant of the matrix is zero", "All roots of the characteristic equation are real", "The number of sign changes is greater than 1", "The number of sign changes in the first column equals the number of roots in the right-half s-plane. Zero sign changes => strictly stable."],
    ["If there are two sign changes in the first column of the Routh array, how many poles lie in the right-half of the s-plane?", "2 poles (the system is unstable)", "0 poles", "1 pole", "4 poles", "Routh's theorem states that the number of right-half plane (RHP) roots equals the number of sign variations in column 1."],
    ["What does an entire row of zeros in a Routh array indicate?", "Symmetric roots with respect to the origin (pairs on jω axis or quad pairs)", "System is unconditionally stable", "Zero steady-state error", "System has no poles", "A row of zeros arises from an auxiliary polynomial possessing roots that are symmetric about the origin, such as purely imaginary jω poles."],
    ["How do you resolve a row of zeros when constructing a Routh array?", "Form an auxiliary polynomial from the preceding row and replace the zeros with its derivative coefficients", "Stop calculation and declare unstable", "Replace all zeros with 1", "Invert the entire table", "Construct auxiliary polynomial A(s) from the row above, differentiate dA(s)/ds, and substitute its coefficients into the zero row."],
    ["What is the characteristic equation of a closed-loop system?", "1 + G(s) H(s) = 0", "G(s) + H(s) = 0", "G(s) H(s) = 1", "d/ds [G(s)] = 0", "The closed-loop denominator 1 + G(s)H(s) set to zero gives the characteristic equation whose roots are the closed-loop poles."],
    ["In the s-plane, moving poles further to the left of the imaginary axis causes the transient response to:", "Decay faster (shorter settling time)", "Oscillate with higher amplitude", "Decay slower", "Become unstable", "Real part -σ determines the exponential decay envelope e^(-σ t). More negative real parts yield faster decay."],
    ["In the s-plane, moving poles vertically further away from the real axis causes:", "Higher frequency of oscillation (larger ω_d)", "Faster settling time", "Zero overshoot", "Increased steady-state error", "The imaginary coordinate corresponds directly to the damped oscillation frequency ω_d."],
    ["What does a pole located in the right-half s-plane (Re{s} > 0) produce in the time domain?", "An exponentially growing unstable response", "A decaying sinusoidal response", "A constant DC offset", "A pure undamped oscillation", "Positive real part gives an exponential factor e^(+σ t) that grows without bound as t -> ∞."],
    ["A system has poles at s = ±j 4. What is its unforced natural response?", "Sustained sinusoidal oscillation at 4 rad/s (marginally stable)", "Exponential growth", "Damped oscillation decaying to zero", "Constant value", "Pure imaginary poles generate sustained sinusoids cos(4t) and sin(4t) with constant amplitude."],
    ["What is the rise time T_r of an underdamped second-order system commonly defined as?", "The time required for the response to rise from 10% to 90% (or 0% to 100%) of its final value", "The time to reach the first peak", "The time to settle within 2%", "The duration of the input pulse", "Rise time measures initial speed of response, commonly taken as the time from 0 to 100% (or 10% to 90%) of final value."],
    ["What effect does adding a zero to the open-loop forward path typically have on closed-loop transient response?", "Increases speed of response and increases overshoot (derivative action)", "Slows down response", "Eliminates steady-state error", "Makes the system overdamped", "Zeros introduce positive phase lead, pulling root locus branches to the left and speeding up transient response, often increasing overshoot."],
    ["What effect does adding a pole to the open-loop forward path typically have on stability?", "Tends to pull root locus branches toward the right half plane, reducing stability margin", "Increases stability margin", "Has zero effect on root locus", "Eliminates all oscillations", "Poles add negative phase lag, bending root locus branches toward the right-half plane and decreasing relative stability."]
  ];

  midRaw.forEach((m, idx) => {
    q.push(createQuestion(`CONTROL-MID-${String(idx+1).padStart(3, '0')}`, 'subj-control', false, m[0], m[1], m[2], m[3], m[4], m[5], 'Medium', 'Control Systems Midterm.pdf', idx));
  });

  // Final: 52 Questions
  // Root locus, frequency response, Bode plots, Nyquist criterion, Gain & Phase Margin, PID controllers, State-space basics
  const finRaw = [
    ["What is the definition of the Root Locus of a feedback control system?", "The graphical path of the closed-loop poles in the s-plane as a system parameter (typically gain K) varies from 0 to ∞", "The locus of system zeros", "The frequency response plot of magnitude versus phase", "The transient step response over time", "Root locus traces the trajectories of closed-loop poles 1 + K G(s)H(s) = 0 as loop gain K increases from 0 to infinity."],
    ["According to the angle condition, a point s_0 lies on the root locus if and only if:", "∠ G(s_0) H(s_0) = ±(2k + 1) * 180° for k = 0, 1, 2, ...", "∠ G(s_0) H(s_0) = 0°", "|G(s_0) H(s_0)| = 0", "∠ G(s_0) H(s_0) = 90°", "From 1 + K GH = 0 => K GH = -1 = 1 ∠(180°), so the sum of angles from zeros minus poles must equal an odd multiple of 180°."],
    ["According to the magnitude condition, the gain K at any valid point s_0 on the root locus is:", "K = 1 / |G(s_0) H(s_0)|", "K = |G(s_0) H(s_0)|", "K = ∠ G(s_0) H(s_0)", "K = s_0", "From |1 + K GH| = 0 => K |GH| = 1 => K = 1 / |GH|."],
    ["How many separate branches does the root locus have?", "Equal to the number of poles (n) of the open-loop transfer function (assuming n ≥ m)", "Equal to the number of open-loop zeros", "Always 2 branches", "Equal to n - m", "Each branch represents the trajectory of one closed-loop pole; there are as many branches as the order of the characteristic equation (number of poles n)."],
    ["A point on the REAL AXIS lies on the root locus if:", "The total number of open-loop real poles and real zeros to its right is ODD", "The total number of real poles and zeros to its right is EVEN", "There are no poles to its left", "It lies between two zeros", "The real axis test evaluates the angle criterion: each real pole/zero to the right contributes 180°, so an odd count gives an odd multiple of 180°."],
    ["What is the formula for the number of asymptotes in a root locus with n poles and m zeros?", "n - m asymptotes", "n + m asymptotes", "m asymptotes", "2n asymptotes", "The n - m branches that do not terminate at finite open-loop zeros must approach infinity along n - m straight-line asymptotes."],
    ["What is the real-axis intersection (center of gravity σ_a) of the root locus asymptotes?", "σ_a = (Σ poles - Σ zeros) / (n - m)", "σ_a = (Σ zeros - Σ poles) / (n + m)", "σ_a = (n - m) / (Σ poles)", "σ_a = Σ poles / n", "The centroid of the asymptotes is given by the sum of real parts of open-loop poles minus zeros divided by (n - m)."],
    ["What are the angles of the asymptotes θ_a in a root locus?", "θ_a = ±(2k + 1) * 180° / (n - m), where k = 0, 1, ..., (n - m - 1)", "θ_a = 360° k / n", "θ_a = 90° * (n - m)", "θ_a = 180° / (n + m)", "The asymptotic angles evenly divide 360°: θ_a = (2k + 1) * 180° / (n - m)."],
    ["How are the breakaway and break-in points on the real axis found analytically in root locus?", "By solving dK/ds = 0 (or d[G(s)H(s)]/ds = 0)", "By setting G(s)H(s) = 0", "By finding the centroid σ_a", "By taking the integral of G(s)", "Breakaway points correspond to local extrema of gain K along the real axis, found by setting dK/ds = 0."],
    ["At what point does the root locus cross the imaginary axis into the unstable region?", "Where the Routh array first column develops a zero, or by substituting s = jω into the characteristic equation", "At s = 0 always", "At the asymptote centroid", "Where K = 0", "Crossing the imaginary axis occurs at critical marginal stability, determined via Routh array auxiliary equation or by setting 1 + K G(jω)H(jω) = 0."],
    ["What is a Bode plot?", "A frequency response plot consisting of two graphs: Log Magnitude (in dB) vs log frequency, and Phase angle vs log frequency", "A plot of real vs imaginary parts of G(jω)", "A root locus in polar coordinates", "A plot of impulse response vs time", "Bode plots display magnitude in dB (20 log_10 |G(jω)|) and phase in degrees versus angular frequency on a logarithmic scale."],
    ["In a Bode magnitude plot, what is the slope corresponding to a single first-order real pole 1 / (1 + jω/ω_c) past its cutoff frequency?", "-20 dB / decade (or -6 dB / octave)", "+20 dB / decade", "-40 dB / decade", "-10 dB / decade", "Past the corner frequency, each pole rolls off the magnitude response at -20 dB per decade (-6 dB/octave)."],
    ["In a Bode magnitude plot, what is the slope of an ideal integrator 1 / s across all frequencies?", "-20 dB / decade passing through 0 dB at ω = 1 rad/s", "+20 dB / decade", "-40 dB / decade", "0 dB / decade", "An integrator 1/(jω) has magnitude 20 log(1/ω) = -20 log(ω) dB, a straight line with slope -20 dB/decade crossing 0 dB at ω = 1."],
    ["What is the phase shift contributed by a single pole at s = -a at its corner frequency ω = a?", "-45°", "-90°", "0°", "-180°", "At ω = a, G(ja) = 1 / (1 + j) => phase = -arctan(1) = -45°. Total asymptotic phase transitions from 0° to -90°."],
    ["What is the Gain Margin (GM) of a feedback control system?", "The factor by which the open-loop gain can be increased before the system becomes unstable, measured at the phase crossover frequency", "The gain at ω = 0", "The phase difference from -180° at gain crossover", "The maximum peak in closed-loop frequency response", "Gain Margin GM = -20 log_10 |G(jω_pc)| dB, where ω_pc is the frequency where phase equals -180°."],
    ["What is the Phase Margin (PM) of a feedback control system?", "The amount of additional phase lag required to bring the system to marginal stability at the gain crossover frequency: PM = 180° + ∠G(jω_gc)", "The phase angle at ω = 0", "The phase at peak overshoot", "The difference between pole angles", "Phase Margin is evaluated at the gain crossover frequency (where |G(jω)| = 1 = 0 dB): PM = 180° + ∠G(jω_gc)."],
    ["For a closed-loop system to be stable, its Gain Margin and Phase Margin must typically be:", "Both positive (GM > 0 dB, PM > 0°)", "Both negative", "GM > 100 dB, PM < 0°", "Zero", "Positive GM and positive PM indicate that closed-loop poles reside strictly in the stable left-half s-plane."],
    ["What is the Gain Crossover Frequency (ω_gc)?", "The frequency at which the open-loop magnitude |G(jω)H(jω)| equals 1 (0 dB)", "The frequency where phase is -180°", "The frequency of maximum overshoot", "The resonant frequency of the closed-loop system", "By definition, ω_gc is the frequency where the loop gain magnitude is exactly unity (0 dB)."],
    ["What is the Phase Crossover Frequency (ω_pc)?", "The frequency at which the open-loop phase angle equals -180°", "The frequency where magnitude is 0 dB", "The frequency where phase is -90°", "The bandwidth frequency", "Phase crossover frequency ω_pc is where the open-loop Nyquist plot crosses the negative real axis (phase = -180°)."],
    ["What does the Nyquist Stability Criterion state: Z = N + P. What does Z represent?", "The number of closed-loop poles in the right-half s-plane (must be 0 for stability)", "The number of open-loop zeros", "The number of encirclements of -1", "The damping ratio", "Z is the count of unstable closed-loop poles; for stability, Z must equal zero (Z = N + P = 0 => N = -P)."],
    ["In the Nyquist criterion Z = N + P, what does N represent?", "The number of clockwise encirclements of the critical point (-1 + j0) by the Nyquist contour mapping", "The number of open-loop poles in RHP", "The number of integrator poles", "The system order", "N is the number of clockwise encirclements of (-1 + j0). Counter-clockwise encirclements are counted as negative."],
    ["In the Nyquist criterion Z = N + P, what does P represent?", "The number of open-loop poles in the right-half s-plane", "The number of closed-loop poles in RHP", "The number of open-loop zeros in RHP", "The phase crossover frequency", "P is the number of open-loop poles lying in the right-half s-plane. If the open-loop system is stable, P = 0."],
    ["If an open-loop system is stable (P = 0), what is the Nyquist condition for the closed-loop system to be stable?", "The Nyquist plot must NOT encircle the critical point (-1 + j0) at all (N = 0)", "The plot must encircle (-1 + j0) once clockwise", "The plot must pass directly through (-1 + j0)", "The plot must encircle (-1 + j0) P times", "Since Z = N + P and P = 0, stability requires Z = 0, which means N = 0 (no encirclements of -1+j0)."],
    ["What are the three components of a standard PID controller?", "Proportional, Integral, and Derivative control actions", "Pole, Integrator, Delay", "Parallel, Inverting, Differential", "Predictive, Iterative, Dynamic", "PID stands for Proportional, Integral, and Derivative control terms combined in parallel."],
    ["What is the primary effect of adding an INTEGRAL (I) action in a controller?", "It increases the system type by 1, completely eliminating steady-state error to step inputs", "It speeds up the transient response", "It reduces peak overshoot", "It improves high-frequency noise immunity", "The integral term integrates error over time; as long as any steady-state error exists, the control output ramps until error becomes strictly zero."],
    ["What is a potential negative side-effect of adding INTEGRAL (I) control action?", "It introduces phase lag, which tends to reduce stability margin and increase overshoot", "It causes steady-state error", "It slows down computational speed only", "It eliminates system damping", "Adding a pole at s=0 adds -90° phase lag, moving the Nyquist plot closer to -1 and decreasing phase margin."],
    ["What is the primary effect of adding DERIVATIVE (D) action in a controller?", "It introduces phase lead (anticipatory action), reducing overshoot and improving stability and settling time", "It eliminates steady-state error", "It amplifies DC signals", "It eliminates high-frequency sensor noise", "Derivative action responds to the rate of error change, providing predictive damping that quenches overshoot."],
    ["Why is pure derivative action rarely used alone in physical analog or digital controllers?", "Because derivative action severely amplifies high-frequency noise", "Because it is nonlinear", "Because it causes negative feedback to become positive", "Because it requires infinite gain at DC", "The transfer function s multiplies amplitude by ω; high-frequency measurement noise is amplified drastically, so a low-pass filter is always added."],
    ["What is the transfer function of an ideal PID controller?", "G_c(s) = K_p + K_i / s + K_d * s = K_p (1 + 1/(T_i s) + T_d s)", "G_c(s) = K_p * K_i * K_d / s", "G_c(s) = (K_p s + K_i) / (K_d s)", "G_c(s) = K_p / (s + 1)", "The parallel PID controller combines proportional gain K_p, integral gain K_i/s, and derivative gain K_d s."],
    ["What is 'Integrator Windup' in a PID control loop?", "The continuous accumulation of error in the integrator during actuator saturation, causing sluggish recovery and large overshoot", "The physical overheating of an op-amp", "The oscillation of derivative terms", "A reset of controller coefficients", "When the actuator saturates, error cannot be eliminated immediately, causing the integral term to wind up to a huge value."],
    ["What is a Lead Compensator primarily used for?", "To provide phase lead near crossover frequency, increasing phase margin and improving transient speed and damping", "To eliminate steady-state error", "To attenuate high frequency noise", "To provide infinite DC gain", "A lead compensator G(s) = (s + z)/(s + p) with z < p provides positive phase lead, improving phase margin and transient response."],
    ["In a Lead Compensator G(s) = (s + z) / (s + p), where are the pole and zero located?", "The zero is closer to the origin than the pole (|z| < |p|)", "The pole is closer to the origin than the zero (|p| < |z|)", "The pole and zero are at the same location", "Both are in the right-half s-plane", "Phase lead requires the zero to act first at lower frequencies, so |z| < |p|."],
    ["What is a Lag Compensator primarily used for?", "To increase low-frequency gain and reduce steady-state error without significantly degrading phase margin", "To increase system bandwidth", "To speed up transient rise time", "To eliminate overshoot completely", "A lag compensator provides high gain at low frequencies to minimize steady-state error while maintaining high-frequency gain and phase margin."],
    ["In a Lag Compensator G(s) = (s + z) / (s + p), where are the pole and zero located?", "The pole is closer to the origin than the zero (|p| < |z|)", "The zero is closer to the origin than the pole (|z| < |p|)", "The pole is on the imaginary axis", "Both are complex conjugates", "High DC gain requires the pole to be very close to the origin, so |p| < |z|."],
    ["In the Ziegler-Nichols frequency response tuning method, what is the 'Ultimate Gain' K_u?", "The value of proportional gain K at which the closed-loop system exhibits sustained, stable marginal oscillations", "The maximum possible gain before amplifier saturation", "The gain at zero frequency", "The gain that gives zero overshoot", "K_u is determined by increasing proportional gain until the closed-loop system reaches the verge of instability (pure sinusoidal oscillation)."],
    ["In state-space representation, what are the state equations for a linear continuous-time system?", "x_dot(t) = A x(t) + B u(t), and y(t) = C x(t) + D u(t)", "x(t) = A x_dot(t) + B y(t)", "y(t) = A x(t) + B u(t)", "x(t) = C y(t) + D", "State-space models use a system of first-order differential equations: state equation x_dot = Ax + Bu and output equation y = Cx + Du."],
    ["What is the formula for the transfer function G(s) derived from the state-space matrices (A, B, C, D)?", "G(s) = C (s I - A)^(-1) B + D", "G(s) = B (s I - A)^(-1) C + D", "G(s) = (s I - A) / (B C)", "G(s) = C A B + D", "Taking the Laplace transform with zero initial conditions: X(s) = (sI - A)^(-1) B U(s), substituting into Y(s) gives G(s) = C(sI - A)^(-1)B + D."],
    ["What are the poles of a system described in state-space form?", "The eigenvalues of the system matrix A (roots of det(s I - A) = 0)", "The diagonal elements of matrix B", "The eigenvalues of matrix C", "The determinant of matrix D", "The characteristic polynomial is det(sI - A) = 0; its roots (the eigenvalues of matrix A) are the system poles."],
    ["What does controllability of a state-space system mean?", "An input exists that can transfer the system from any initial state to any arbitrary final state in finite time", "The outputs can be observed from measurements", "The matrix A is diagonal", "All eigenvalues are real", "A system is controllable if control inputs can steer every state variable across the entire state space."],
    ["What is the Controllability Matrix C_M for an n-th order system?", "C_M = [B  AB  A^2 B ... A^(n-1) B]", "C_M = [C; CA; CA^2; ... CA^(n-1)]", "C_M = A * B", "C_M = det(A - B)", "The system is controllable if and only if the controllability matrix [B, AB, ..., A^(n-1)B] has full rank n."],
    ["What does observability of a state-space system mean?", "The initial state x(0) can be uniquely determined from observations of the output y(t) over a finite time interval", "The inputs can be computed from states", "The system matrix A is symmetric", "All poles are in the left-half plane", "Observability ensures internal state trajectories can be reconstructed purely from measurable output histories."],
    ["What is the Observability Matrix O_M for an n-th order system?", "O_M = [C;  CA;  CA^2; ... CA^(n-1)]", "O_M = [B  AB  A^2 B ... A^(n-1) B]", "O_M = C^(-1) A", "O_M = det(s I - A)", "A system is observable if and only if the observability matrix O_M has full rank n."],
    ["What is state-feedback control u(t) = -K x(t) used for?", "Arbitrary closed-loop pole placement to achieve desired transient dynamics (Ackermann's formula)", "Eliminating sensor noise", "Measuring open-loop gain", "Computing the transfer function", "State feedback allows moving all closed-loop poles to any desired locations in the s-plane, provided the system is controllable."],
    ["What is the state transition matrix Φ(t) of a linear continuous-time system?", "Φ(t) = e^(A t) = L^(-1){(s I - A)^(-1)}", "Φ(t) = A * t", "Φ(t) = det(s I - A)", "Φ(t) = C e^(A t) B", "The matrix exponential e^(At) maps states forward in time: x(t) = e^(At) x(0) + ∫ e^(A(t-τ)) B u(τ) dτ."],
    ["What is the bandwidth (BW) of a control system?", "The frequency range over which the closed-loop magnitude response remains within -3 dB of its DC value", "The frequency where phase is 0°", "The maximum gain frequency", "The sampling frequency", "Bandwidth characterizes the system's speed of response and noise rejection capability."],
    ["What is the relationship between bandwidth and system response speed?", "A larger bandwidth corresponds to a faster rise time and quicker transient response", "A larger bandwidth makes the system slower", "Bandwidth has no effect on speed", "Larger bandwidth eliminates overshoot", "Higher bandwidth allows higher frequency components of the input to pass, reducing rise time."],
    ["In digital control systems, what is the effect of the Zero-Order Hold (ZOH)?", "It introduces an effective time delay of T/2, which adds phase lag and reduces stability margins", "It doubles the system bandwidth", "It eliminates all sampling ripple", "It increases phase lead", "The ZOH transfer function (1 - e^(-sT))/s has an average delay of half the sampling period T/2, adding phase lag."],
    ["What does a deadbeat controller achieve in discrete-time control?", "Brings the output to steady state in a minimum finite number of sampling periods with zero steady-state error", "Eliminates all pole locations", "Continuously oscillates", "Requires infinite sampling frequency", "Deadbeat response places all closed-loop poles at the origin z = 0, terminating transients in at most n sampling steps."],
    ["What is the condition for asymptotic stability in discrete-time state-space x[k+1] = A_d x[k]?", "All eigenvalues of matrix A_d must have absolute magnitude strictly less than 1 (|λ_i| < 1)", "All eigenvalues must have negative real parts", "Matrix A_d must be symmetric", "Trace(A_d) = 0", "In discrete time, stability requires all eigenvalues to lie strictly inside the unit circle of the complex plane."],
    ["What does the sensitivity function S(s) = 1 / (1 + G(s) H(s)) represent?", "The fractional change in closed-loop transfer function relative to changes in the plant transfer function G(s)", "The sensor calibration error", "The controller gain margin", "The noise amplification factor only", "Sensitivity S(s) quantifies how parameter variations in the plant affect overall closed-loop performance; small S(s) means high robustness."],
    ["What does the Complementary Sensitivity function T(s) = G(s)H(s) / (1 + G(s)H(s)) represent?", "The closed-loop tracking transfer function, satisfying S(s) + T(s) = 1", "The sensor noise sensitivity alone", "The open-loop gain", "The inverse controller", "T(s) describes reference tracking and sensor noise transmission; the fundamental constraint S + T = 1 represents trade-offs between tracking and noise rejection."],
    ["In modern robust control, what does the H-infinity norm of a stable transfer function matrix represent?", "The peak gain over all frequencies (worst-case maximum singular value)", "The total energy of the impulse response", "The pole with the slowest decay", "The DC steady-state gain", "The H-infinity norm ||G||_∞ = sup_ω σ_max(G(jω)) quantifies the worst-case peak gain across all frequencies, central to robust stability analysis."]
  ];

  finRaw.forEach((m, idx) => {
    q.push(createQuestion(`CONTROL-FIN-${String(idx+1).padStart(3, '0')}`, 'subj-control', true, m[0], m[1], m[2], m[3], m[4], m[5], 'Medium', 'Control Systems Final Exam.pdf', idx));
  });

  return q;
}

function getLogicSignalsControlQuestions() {
  return [
    ...getLogicQuestions(),
    ...getSignalsQuestions(),
    ...getControlQuestions()
  ];
}

module.exports = { getLogicSignalsControlQuestions };
