const { createQuestion } = require('./bank_factory');

function getNumAndStatsQuestions() {
  const qs = [];

  // ==========================================
  // NUMERICAL METHODS (subj-numerical)
  // Mid: 32 (Errors, Bisection, False Position, Fixed-Point, Newton-Raphson, Secant, Gauss Elimination with pivoting, LU Decomposition, Jacobi, Gauss-Seidel)
  // Final: 52 (Lagrange interpolation, Newton divided differences, Splines, Numerical differentiation, Trapezoidal, Simpson 1/3 and 3/8, Romberg, Gauss quadrature, Euler, RK4)
  // ==========================================
  const numMid = [
    { q: 'The absolute error between true value x and approximate value x* is defined as:', c: '|x - x*|', w1: '|x - x*| / |x|', w2: '(x - x*)²', w3: '|x| / |x*|', exp: 'Definition of absolute error.', d: 'Easy' },
    { q: 'The relative error between true value x (x ≠ 0) and approximate value x* is:', c: '|x - x*| / |x|', w1: '|x - x*|', w2: '|x| - |x*|', w3: '|x - x*| / 100', exp: 'Definition of relative error.', d: 'Easy' },
    { q: 'Truncation error occurs in numerical computing due to:', c: 'Approximating an exact mathematical procedure by a finite process (e.g., truncating Taylor series)', w1: 'Finite computer word length (rounding bits)', w2: 'Human error during typing', w3: 'Hardware memory failure', exp: 'Truncation error stems from the mathematical discretization.', d: 'Easy' },
    { q: 'Round-off error occurs primarily because:', c: 'Computers represent real numbers with a finite number of bits/digits', w1: 'Formulas are truncated', w2: 'Functions are discontinuous', w3: 'Roots are complex', exp: 'Floating-point representations have finite precision.', d: 'Easy' },
    { q: 'The Bisection Method for finding a root of f(x) = 0 on [a, b] requires that:', c: 'f(x) is continuous on [a, b] and f(a) * f(b) < 0', w1: 'f\'(x) ≠ 0 on [a, b]', w2: 'f(x) is differentiable everywhere', w3: 'f(a) = f(b)', exp: 'Intermediate Value Theorem requires continuity and sign change.', d: 'Easy' },
    { q: 'The rate of convergence of the Bisection Method is:', c: 'Linear with factor 1/2 (error halves each iteration)', w1: 'Quadratic', w2: 'Cubic', w3: 'Superlinear (1.618)', exp: 'Interval length after n iterations is (b - a)/2^n.', d: 'Easy' },
    { q: 'To guarantee that the error in Bisection is less than ε, the minimum iterations n satisfies:', c: 'n > [ln(b - a) - ln(ε)] / ln(2)', w1: 'n > (b - a) / ε', w2: 'n > 2^(b - a)', w3: 'n > ln(ε)', exp: '(b - a)/2^n < ε => 2^n > (b - a)/ε => n > log₂((b - a)/ε).', d: 'Medium' },
    { q: 'The False Position (Regula Falsi) method finds the next approximation c by:', c: 'The x-intercept of the secant line connecting (a, f(a)) and (b, f(b))', w1: 'The midpoint (a + b)/2', w2: 'The tangent line at a', w3: 'The average of derivatives', exp: 'c = [a f(b) - b f(a)] / [f(b) - f(a)].', d: 'Easy' },
    { q: 'In Fixed-Point Iteration x_{n+1} = g(x_n), convergence to root p is guaranteed if:', c: '|g\'(x)| ≤ k < 1 in an interval containing p', w1: '|g\'(x)| > 1', w2: 'g\'(x) = 0 everywhere', w3: 'g(x) is a constant', exp: 'Contraction Mapping Theorem requires |g\'(x)| < 1.', d: 'Medium' },
    { q: 'The Newton-Raphson iteration formula is:', c: 'x_{n+1} = x_n - f(x_n) / f\'(x_n)', w1: 'x_{n+1} = x_n - f\'(x_n) / f(x_n)', w2: 'x_{n+1} = x_n + f(x_n) / f\'(x_n)', w3: 'x_{n+1} = f(x_n) / f\'(x_n)', exp: 'Derived from linear Taylor expansion f(x) ≈ f(x_n) + f\'(x_n)(x - x_n) = 0.', d: 'Easy' },
    { q: 'The order of convergence of the Newton-Raphson method for a simple root is:', c: 'Quadratic (order 2)', w1: 'Linear (order 1)', w2: 'Superlinear (order 1.618)', w3: 'Cubic (order 3)', exp: 'e_{n+1} ≈ [f\'\'(p)/(2f\'(p))] * e_n² for a simple root.', d: 'Easy' },
    { q: 'The Newton-Raphson method fails or divides by zero if:', c: 'f\'(x_n) = 0 (horizontal tangent line)', w1: 'f(x_n) = 0', w2: 'f\'\'(x_n) = 0', w3: 'x_n > 0', exp: 'Division by f\'(x_n) causes failure if derivative is zero.', d: 'Easy' },
    { q: 'For a multiple root of multiplicity m > 1, standard Newton-Raphson exhibits:', c: 'Linear convergence', w1: 'Quadratic convergence', w2: 'Superlinear convergence', w3: 'Divergence always', exp: 'For multiple roots, standard Newton converges only linearly unless modified.', d: 'Medium' },
    { q: 'The Secant Method formula approximates f\'(x_n) by:', c: '[f(x_n) - f(x_{n-1})] / [x_n - x_{n-1}]', w1: '[f(x_n) + f(x_{n-1})] / 2', w2: 'f\'(x_n) exactly', w3: '(x_n - x_{n-1}) / 2', exp: 'Replaces true derivative with finite difference quotient.', d: 'Easy' },
    { q: 'The order of convergence of the Secant Method is:', c: 'Golden ratio ≈ 1.618 (superlinear)', w1: 'Linear (1.0)', w2: 'Quadratic (2.0)', w3: 'Cubic (3.0)', exp: 'Order is (1 + √5)/2 ≈ 1.618.', d: 'Medium' },
    { q: 'Unlike the Bisection and Regula Falsi methods, Newton-Raphson and Secant methods:', c: 'Are open methods that do not require bracketing the root', w1: 'Always guarantee convergence', w2: 'Never diverge', w3: 'Do not use function evaluations', exp: 'Open methods need initial guesses, not necessarily bracketing.', d: 'Easy' },
    { q: 'Partial pivoting in Gaussian elimination consists of:', c: 'Swapping rows to place the element with the largest absolute value in the pivot position', w1: 'Swapping columns only', w2: 'Dividing the entire row by 2', w3: 'Multiplying the row by -1', exp: 'Prevents division by small numbers and reduces round-off error amplification.', d: 'Medium' },
    { q: 'In LU Decomposition of a matrix A (A = LU), L is:', c: 'A lower triangular matrix (often with 1s on the diagonal)', w1: 'An upper triangular matrix', w2: 'A diagonal matrix', w3: 'An orthogonal matrix', exp: 'L = Lower triangular, U = Upper triangular.', d: 'Easy' },
    { q: 'In Doolittle\'s method for LU decomposition:', c: 'L has diagonal entries equal to 1 (unit lower triangular)', w1: 'U has diagonal entries equal to 1', w2: 'Both L and U are symmetric', w3: 'L = U^T', exp: 'Doolittle sets l_ii = 1; Crout sets u_ii = 1.', d: 'Medium' },
    { q: 'In Crout\'s method for LU decomposition:', c: 'U has diagonal entries equal to 1 (unit upper triangular)', w1: 'L has diagonal entries equal to 1', w2: 'A is assumed orthogonal', w3: 'U is lower triangular', exp: 'Crout sets u_ii = 1.', d: 'Medium' },
    { q: 'Cholesky decomposition A = L L^T is applicable if and only if A is:', c: 'Symmetric and positive definite', w1: 'Any invertible matrix', w2: 'Skew-symmetric', w3: 'Singular', exp: 'Cholesky requires symmetry and all positive eigenvalues.', d: 'Medium' },
    { q: 'In Jacobi iteration for solving Ax = b, the (k+1)-th estimate x_i^{(k+1)} is computed using:', c: 'Only values from the previous iteration k: x^{(k)}', w1: 'Newly computed values from current iteration (k+1)', w2: 'Random values', w3: 'A single matrix inverse', exp: 'Jacobi uses all old values; Gauss-Seidel uses updated values as soon as available.', d: 'Medium' },
    { q: 'In Gauss-Seidel iteration, the computation of x_i^{(k+1)} uses:', c: 'The newly computed values x_1^{(k+1)}, ..., x_{i-1}^{(k+1)} immediately', w1: 'Only iteration k values', w2: 'Future iteration (k+2) values', w3: 'No previous values', exp: 'Immediate reuse accelerates convergence.', d: 'Medium' },
    { q: 'A matrix A is strictly diagonally dominant if for every row i:', c: '|a_ii| > Σ_{j ≠ i} |a_ij|', w1: '|a_ii| < Σ_{j ≠ i} |a_ij|', w2: 'a_ii = 0', w3: 'a_ii = Σ a_ij', exp: 'Diagonal entry absolute value strictly exceeds sum of other entries in the row.', d: 'Easy' },
    { q: 'If A is strictly diagonally dominant, both Jacobi and Gauss-Seidel methods:', c: 'Are guaranteed to converge for any initial guess', w1: 'Diverge', w2: 'Converge in exactly 1 iteration', w3: 'Fail due to zero pivot', exp: 'Strict diagonal dominance is a sufficient condition for convergence.', d: 'Easy' },
    { q: 'The spectral radius ρ(T) of iteration matrix T must satisfy which condition for convergence?', c: 'ρ(T) < 1', w1: 'ρ(T) > 1', w2: 'ρ(T) = 1', w3: 'ρ(T) = 0 only', exp: 'Theorem: x^{(k)} → x* for any x^{(0)} iff ρ(T) < 1.', d: 'Hard' },
    { q: 'Successive Over-Relaxation (SOR) introduces relaxation parameter ω. For convergence, ω must be in:', c: '(0, 2)', w1: '[1, ∞)', w2: '(-1, 1)', w3: '(0, 1) only', exp: 'Kahan\'s theorem: SOR diverges if ω ∉ (0, 2).', d: 'Hard' },
    { q: 'Use Newton-Raphson to find next guess for f(x) = x² - 2 starting at x₀ = 1:', c: '1.5', w1: '1.414', w2: '2.0', w3: '1.25', exp: 'x₁ = 1 - (1 - 2)/(2*1) = 1 - (-1/2) = 1.5.', d: 'Easy' },
    { q: 'Number of operations (multiplications/divisions) in Gaussian elimination for n unknowns is of order:', c: 'O(n³ / 3)', w1: 'O(n²)', w2: 'O(n!)', w3: 'O(n log n)', exp: 'Triangular reduction requires ~n³/3 operations.', d: 'Medium' },
    { q: 'Forward substitution solves L y = b in operations of order:', c: 'O(n²)', w1: 'O(n³)', w2: 'O(n)', w3: 'O(1)', exp: 'Solving triangular systems requires n²/2 multiplications.', d: 'Easy' },
    { q: 'Ill-conditioned systems of linear equations are characterized by:', c: 'A large condition number κ(A), making solutions highly sensitive to perturbations', w1: 'A condition number equal to 1', w2: 'det(A) = 1', w3: 'Strict diagonal dominance', exp: 'Large condition number indicates numerical instability.', d: 'Medium' },
    { q: 'If f(x) = x³ - x - 1, in which interval does a root exist by Intermediate Value Theorem?', c: '[1, 2], since f(1) = -1 < 0 and f(2) = 5 > 0', w1: '[0, 1]', w2: '[2, 3]', w3: '[-1, 0]', exp: 'f(1) = -1, f(2) = 5. Signs are opposite.', d: 'Easy' }
  ];

  const numFinal = [
    { q: 'Given n + 1 distinct points, there exists a unique polynomial of degree at most:', c: 'n that passes through all points', w1: 'n + 1', w2: 'n - 1', w3: '2n', exp: 'Fundamental theorem of polynomial interpolation.', d: 'Easy' },
    { q: 'The Lagrange interpolating polynomial formula is P_n(x) =', c: 'Σ_{i=0}^n y_i L_i(x)', w1: 'Σ_{i=0}^n y_i (x - x_i)', w2: 'Π_{i=0}^n (x - x_i)', w3: 'Σ x_i / y_i', exp: 'Linear combination of Lagrange basis polynomials L_i(x).', d: 'Easy' },
    { q: 'The Lagrange cardinal basis polynomial L_i(x) satisfies:', c: 'L_i(x_j) = 1 if i = j, and 0 if i ≠ j (Kronecker delta δ_ij)', w1: 'L_i(x_j) = 1 always', w2: 'L_i(x_j) = 0 always', w3: 'L_i(x_i) = 0', exp: 'Standard defining property of Lagrange basis.', d: 'Easy' },
    { q: 'In Newton\'s divided difference interpolation, the divided difference f[x₀, x₁] is:', c: '[f(x₁) - f(x₀)] / (x₁ - x₀)', w1: '[f(x₁) + f(x₀)] / 2', w2: 'f(x₁) - f(x₀)', w3: '(x₁ - x₀) / [f(x₁) - f(x₀)]', exp: 'Definition of 1st divided difference.', d: 'Easy' },
    { q: 'A cubic spline S(x) on [a, b] is twice continuously differentiable, meaning:', c: 'S(x), S\'(x), and S\'\'(x) are continuous across all internal knots', w1: 'S\'\'\'(x) is continuous', w2: 'Only S(x) is continuous', w3: 'S(x) is a straight line', exp: 'Cubic splines ensure C² continuity.', d: 'Medium' },
    { q: 'A natural (free) cubic spline satisfies the boundary conditions at endpoints a and b:', c: 'S\'\'(a) = 0 and S\'\'(b) = 0', w1: 'S\'(a) = 0 and S\'(b) = 0', w2: 'S(a) = 0 and S(b) = 0', w3: 'S\'\'\'(a) = 0', exp: 'Zero second derivatives at endpoints define natural splines.', d: 'Medium' },
    { q: 'The clamped (complete) cubic spline specifies:', c: 'S\'(a) = f\'(a) and S\'(b) = f\'(b)', w1: 'S\'\'(a) = 0', w2: 'S(a) = S(b)', w3: 'Knots are equally spaced only', exp: 'Clamped splines fix first derivatives at both boundaries.', d: 'Medium' },
    { q: 'Runge\'s phenomenon refers to:', c: 'Wild oscillations near interval endpoints when using high-degree polynomial interpolation with equidistant nodes', w1: 'Convergence of splines to zero', w2: 'Round-off error in Simpson\'s rule', w3: 'Instability in Euler\'s method', exp: 'Classic example f(x) = 1/(1 + 25x²) shows oscillations as n increases.', d: 'Medium' },
    { q: 'Chebyshev nodes are used in polynomial interpolation to:', c: 'Minimize the maximum interpolation error and eliminate Runge\'s phenomenon', w1: 'Make knots equally spaced', w2: 'Avoid computing derivatives', w3: 'Make all divided differences zero', exp: 'Chebyshev roots minimize the polynomial product ||Π (x - x_i)||.', d: 'Hard' },
    { q: 'The forward difference approximation for f\'(x₀) is:', c: '[f(x₀ + h) - f(x₀)] / h with truncation error O(h)', w1: '[f(x₀ + h) - f(x₀ - h)] / 2h', w2: '[f(x₀) - f(x₀ - h)] / h', w3: 'f(x₀ + h) / h', exp: 'Forward difference has first order error O(h).', d: 'Easy' },
    { q: 'The backward difference approximation for f\'(x₀) is:', c: '[f(x₀) - f(x₀ - h)] / h with truncation error O(h)', w1: '[f(x₀ + h) - f(x₀)] / h', w2: '[f(x₀ + h) - f(x₀ - h)] / 2h', w3: 'f\'(x₀) - h', exp: 'Backward difference has first order error O(h).', d: 'Easy' },
    { q: 'The central difference approximation for f\'(x₀) is:', c: '[f(x₀ + h) - f(x₀ - h)] / (2h) with truncation error O(h²)', w1: '[f(x₀ + h) - f(x₀)] / h', w2: '[f(x₀ + h) + f(x₀ - h)] / h', w3: 'f\'(x₀) / h', exp: 'Central difference cancels odd terms, giving second order accuracy O(h²).', d: 'Easy' },
    { q: 'The central difference formula for the second derivative f\'\'(x₀) is:', c: '[f(x₀ + h) - 2 f(x₀) + f(x₀ - h)] / h² with error O(h²)', w1: '[f(x₀ + h) - f(x₀ - h)] / h²', w2: '[f(x₀ + h) + f(x₀ - h)] / 2h²', w3: 'f(x₀) / h²', exp: 'Standard three-point central second derivative formula.', d: 'Medium' },
    { q: 'Richardson extrapolation combines two estimates of order O(h²) to produce an estimate of order:', c: 'O(h⁴)', w1: 'O(h³)', w2: 'O(h²)', w3: 'O(h⁶)', exp: 'Cancels the leading h² error term: [4 I(h/2) - I(h)] / 3.', d: 'Medium' },
    { q: 'The Trapezoidal rule approximates ∫ₐᵇ f(x) dx by:', c: '(b - a) * [f(a) + f(b)] / 2', w1: '(b - a) * [f(a) - f(b)] / 2', w2: '(b - a) * f((a+b)/2)', w3: '[f(a) + f(b)] / (b - a)', exp: 'Area of a trapezoid under linear interpolant.', d: 'Easy' },
    { q: 'The local truncation error of the single Trapezoidal rule is proportional to:', c: '-(1/12) h³ f\'\'(ξ)', w1: '-(1/90) h⁵ f⁽⁴⁾(ξ)', w2: 'h f\'(ξ)', w3: 'h²', exp: 'Standard error term for single trapezoidal rule.', d: 'Medium' },
    { q: 'The global error of the Composite Trapezoidal rule with n subintervals (step h) is:', c: 'O(h²)', w1: 'O(h)', w2: 'O(h⁴)', w3: 'O(h³)', exp: 'Sum of n intervals of local error O(h³) gives global error O(h²).', d: 'Easy' },
    { q: 'Simpson\'s 1/3 rule approximates the integral by fitting a parabola over:', c: '2 subintervals (3 equally spaced points)', w1: '1 subinterval', w2: '3 subintervals', w3: '4 subintervals', exp: 'Requires 2 subintervals: (h/3)[f₀ + 4f₁ + f₂].', d: 'Easy' },
    { q: 'Simpson\'s 1/3 rule formula for 2 subintervals is:', c: '(h / 3) * [f(x₀) + 4 f(x₁) + f(x₂)]', w1: '(h / 2) * [f(x₀) + 2 f(x₁) + f(x₂)]', w2: '(3h / 8) * [f(x₀) + 3 f(x₁) + 3 f(x₂)]', w3: 'h * [f(x₀) + f(x₁)]', exp: 'Standard weights 1, 4, 1 scaled by h/3.', d: 'Easy' },
    { q: 'The Composite Simpson\'s 1/3 rule requires the total number of subintervals n to be:', c: 'An even integer', w1: 'An odd integer', w2: 'A prime number', w3: 'Any integer', exp: 'Pairs of subintervals are required, so n must be even.', d: 'Easy' },
    { q: 'The global truncation error of the Composite Simpson\'s 1/3 rule is:', c: 'O(h⁴)', w1: 'O(h²)', w2: 'O(h³)', w3: 'O(h⁵)', exp: 'Fourth-order accuracy: integrates polynomials up to degree 3 exactly.', d: 'Medium' },
    { q: 'Simpson\'s 3/8 rule requires:', c: '3 subintervals (4 points)', w1: '2 subintervals', w2: '1 subinterval', w3: '8 subintervals', exp: 'Formula: (3h/8)[f₀ + 3f₁ + 3f₂ + f₃].', d: 'Easy' },
    { q: 'Romberg integration applies Richardson extrapolation to which integration rule?', c: 'The Composite Trapezoidal rule', w1: 'Simpson\'s rule', w2: 'Euler\'s rule', w3: 'Midpoint rule only', exp: 'Successively eliminates h², h⁴, h⁶ error terms from trapezoidal estimates.', d: 'Medium' },
    { q: 'Gauss-Legendre quadrature evaluates integrals ∫₋₁¹ f(x) dx by choosing:', c: 'Optimal non-equidistant nodes (roots of Legendre polynomials) and weights', w1: 'Equidistant nodes only', w2: 'Endpoints only', w3: 'Integer nodes', exp: 'n-point Gauss quadrature is exact for polynomials of degree up to 2n - 1.', d: 'Hard' },
    { q: 'A 2-point Gauss-Legendre quadrature rule has degree of precision equal to:', c: '3 (exact for polynomials up to degree 2(2) - 1 = 3)', w1: '1', w2: '2', w3: '4', exp: 'Formula 2n - 1 with n = 2 gives precision 3.', d: 'Hard' },
    { q: 'Euler\'s method for the initial value problem y\' = f(t, y), y(t₀) = y₀ is:', c: 'y_{n+1} = y_n + h * f(t_n, y_n)', w1: 'y_{n+1} = y_n + (h/2) [f(t_n, y_n) + f(t_{n+1}, y_{n+1})]', w2: 'y_{n+1} = y_n + h * f(t_{n+1}, y_{n+1})', w3: 'y_{n+1} = y_n / h', exp: 'Explicit first-order Taylor approximation.', d: 'Easy' },
    { q: 'The local truncation error of Euler\'s method is O(h²), while its global error is:', c: 'O(h)', w1: 'O(h²)', w2: 'O(h³)', w3: 'O(1)', exp: 'Accumulating n = (T - t₀)/h steps of O(h²) yields O(h) global error.', d: 'Medium' },
    { q: 'Heun\'s method (Improved Euler / Predictor-Corrector) has global truncation error:', c: 'O(h²)', w1: 'O(h)', w2: 'O(h⁴)', w3: 'O(h³)', exp: 'Second-order Runge-Kutta method.', d: 'Medium' },
    { q: 'The classical Runge-Kutta 4th Order method (RK4) evaluates the slope at how many points per step?', c: '4 points (k₁, k₂, k₃, k₄)', w1: '2 points', w2: '1 point', w3: '6 points', exp: 'Four stage evaluations combined with weights (1/6)[k₁ + 2k₂ + 2k₃ + k₄].', d: 'Easy' },
    { q: 'The global error of the classical Runge-Kutta 4th Order method (RK4) is:', c: 'O(h⁴)', w1: 'O(h²)', w2: 'O(h)', w3: 'O(h⁵)', exp: 'RK4 is a fourth-order accurate scheme.', d: 'Easy' },
    { q: 'A numerical ODE method is called explicit if:', c: 'y_{n+1} is given directly in terms of known previous values (t_n, y_n)', w1: 'y_{n+1} appears on both sides of the equation', w2: 'It requires solving a nonlinear equation at each step', w3: 'The step size h is zero', exp: 'Explicit methods compute the next state without solving implicit equations.', d: 'Easy' },
    { q: 'An implicit numerical method (such as Backward Euler y_{n+1} = y_n + h f(t_{n+1}, y_{n+1})) is preferred for:', c: 'Stiff differential equations, due to superior numerical stability', w1: 'Problems where f is linear only', w2: 'Faster execution with fewer calculations', w3: 'Problems with no solutions', exp: 'A-stability of implicit methods allows larger step sizes for stiff systems.', d: 'Hard' },
    { q: 'In solving boundary value problems (BVPs), the Finite Difference Method replaces derivatives with:', c: 'Finite difference approximations at discrete grid points, forming a linear system', w1: 'Integration by parts', w2: 'Euler\'s method step by step', w3: 'Newton-Raphson iteration', exp: 'Converts continuous differential equations into algebraic matrix equations.', d: 'Medium' },
    { q: 'The shooting method for boundary value problems solves a BVP by:', c: 'Treating it as an initial value problem (IVP) and adjusting initial slope guesses iteratively', w1: 'Using Simpson\'s rule directly', w2: 'Finding eigenvalues of A', w3: 'Inverting a tridiagonal matrix', exp: 'Iteratively shoots trajectories until boundary condition is hit.', d: 'Medium' },
    { q: 'Evaluate ∫₀² x dx using the single Trapezoidal rule:', c: '2', w1: '1', w2: '4', w3: '0', exp: '(2 - 0) * (0 + 2) / 2 = 2 (exact for linear functions).', d: 'Easy' },
    { q: 'Simpson\'s 1/3 rule is exact for all polynomials of degree at most:', c: '3', w1: '1', w2: '2', w3: '4', exp: 'Error term involves fourth derivative f⁽⁴⁾(ξ), so exact up to degree 3.', d: 'Medium' },
    { q: 'Using Euler\'s method with h = 0.1 for y\' = y, y(0) = 1, find y(0.1):', c: '1.1', w1: '1.0', w2: '1.2', w3: '1.01', exp: 'y₁ = 1 + 0.1*(1) = 1.1.', d: 'Easy' },
    { q: 'In the Composite Trapezoidal rule, internal nodes have weight:', c: '2', w1: '1', w2: '4', w3: '3', exp: '(h/2)[f₀ + 2f₁ + 2f₂ + ... + 2f_{n-1} + f_n].', d: 'Easy' },
    { q: 'In the Composite Simpson\'s 1/3 rule, the alternating weights for internal nodes are:', c: '4 and 2', w1: '3 and 3', w2: '1 and 1', w3: '2 and 2', exp: '(h/3)[f₀ + 4f₁ + 2f₂ + 4f₃ + 2f₄ + ... + 4f_{n-1} + f_n].', d: 'Medium' },
    { q: 'For y\' = -100y, the test equation for stability, the step size h for explicit Euler must satisfy:', c: 'h < 2 / 100 = 0.02', w1: 'h < 1', w2: 'h > 0.02', w3: 'h can be any value', exp: '|1 + hλ| < 1 => |1 - 100h| < 1 => -1 < 1 - 100h < 1 => 0 < h < 0.02.', d: 'Hard' },
    { q: 'Which method requires only 1 function evaluation per step?', c: 'Euler\'s method', w1: 'Heun\'s method', w2: 'RK4', w3: 'Simpson\'s rule', exp: 'Only f(t_n, y_n) is computed.', d: 'Easy' },
    { q: 'To evaluate ∫ₐᵇ f(x) dx using Gauss-Legendre quadrature on [a, b], one must first change variables using:', c: 'x = [(b - a) t + (b + a)] / 2 for t ∈ [-1, 1]', w1: 'x = (b - a) t', w2: 't = x - a', w3: 't = x / (b - a)', exp: 'Standard affine transformation mapping [-1, 1] to [a, b].', d: 'Medium' },
    { q: 'The error formula for Lagrange interpolation includes the factor:', c: '(x - x₀)(x - x₁) ... (x - x_n)', w1: '(x - x₀) + (x - x₁)', w2: 'f\'(x)', w3: '1 / n!', exp: 'Error is [f⁽ⁿ⁺¹⁾(ξ) / (n+1)!] * Π_{i=0}^n (x - x_i).', d: 'Medium' },
    { q: 'The Neville\'s algorithm is used to:', c: 'Evaluate interpolating polynomials recursively without explicitly finding coefficients', w1: 'Solve nonlinear systems', w2: 'Perform numerical integration', w3: 'Compute matrix inverses', exp: 'Recursive table-based interpolation evaluation.', d: 'Hard' },
    { q: 'The tridiagonal matrix algorithm (TDMA / Thomas algorithm) solves a tridiagonal system in:', c: 'O(n) operations', w1: 'O(n³) operations', w2: 'O(n²)', w3: 'O(log n)', exp: 'Elimination on tridiagonal matrices requires only O(n) work.', d: 'Medium' },
    { q: 'What is the divided difference f[x₀] of a single point?', c: 'f(x₀)', w1: 'f\'(x₀)', w2: '0', w3: 'x₀', exp: '0th order divided difference is the function value.', d: 'Easy' },
    { q: 'The forward difference operator Δ is defined as:', c: 'Δ f_i = f_{i+1} - f_i', w1: 'Δ f_i = f_i - f_{i-1}', w2: 'Δ f_i = f_{i+1} + f_i', w3: 'Δ f_i = f_i / h', exp: 'Definition of forward difference.', d: 'Easy' },
    { q: 'The backward difference operator ∇ is defined as:', c: '∇ f_i = f_i - f_{i-1}', w1: '∇ f_i = f_{i+1} - f_i', w2: '∇ f_i = f_{i+1} - f_{i-1}', w3: '∇ f_i = f_i', exp: 'Definition of backward difference.', d: 'Easy' },
    { q: 'The central difference operator δ is defined as:', c: 'δ f_i = f_{i + 1/2} - f_{i - 1/2}', w1: 'δ f_i = f_{i+1} - f_{i-1}', w2: 'δ f_i = f_i', w3: 'δ f_i = f_i²', exp: 'Definition of central difference operator.', d: 'Medium' },
    { q: 'If f(x) = 5 is a constant function, what is its first divided difference f[x₀, x₁]?', c: '0', w1: '5', w2: '1', w3: 'Undefined', exp: '(5 - 5)/(x₁ - x₀) = 0.', d: 'Easy' },
    { q: 'Adaptive quadrature methods automatically:', c: 'Refine the step size h in regions where the integrand has rapid variations', w1: 'Keep h strictly constant everywhere', w2: 'Avoid computing any integrals', w3: 'Double the interval length', exp: 'Divides intervals until local error estimate falls below tolerance.', d: 'Medium' },
    { q: 'The multi-step Adams-Bashforth methods are:', c: 'Explicit linear multi-step methods', w1: 'Implicit Runge-Kutta methods', w2: 'Single-step methods', w3: 'Root finding algorithms', exp: 'Adams-Bashforth is explicit; Adams-Moulton is implicit.', d: 'Hard' }
  ];

  numMid.forEach((it, idx) => qs.push(createQuestion(`NUM-MID-${String(idx + 1).padStart(3, '0')}`, 'subj-numerical', false, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'Numerical Methods Mid.pdf', idx)));
  numFinal.forEach((it, idx) => qs.push(createQuestion(`NUM-FIN-${String(idx + 1).padStart(3, '0')}`, 'subj-numerical', true, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'Numerical Methods Final.pdf', idx)));

  // ==========================================
  // PROBABILITY AND STATISTICS (subj-stats)
  // Mid: 32 (Sample space, Events, Probability axioms, Conditional, Bayes, Discrete RVs, PMF, CDF, Binomial, Poisson, Geometric)
  // Final: 52 (Continuous RVs, PDF, Exponential, Normal distribution, Standard Z, Central Limit Theorem, Joint, Covariance, Confidence intervals, Hypothesis testing)
  // ==========================================
  const statsMid = [
    { q: 'The set of all possible outcomes of a random experiment is called the:', c: 'Sample space S', w1: 'Event space', w2: 'Probability distribution', w3: 'Population mean', exp: 'Definition of sample space.', d: 'Easy' },
    { q: 'For any event A, the probability P(A) must satisfy:', c: '0 ≤ P(A) ≤ 1', w1: 'P(A) ≥ 1', w2: '-1 ≤ P(A) ≤ 1', w3: 'P(A) > 0', exp: 'First axiom of probability (Kolmogorov).', d: 'Easy' },
    { q: 'If A and B are mutually exclusive (disjoint) events, then P(A ∩ B) equals:', c: '0', w1: '1', w2: 'P(A) * P(B)', w3: 'P(A) + P(B)', exp: 'Mutually exclusive events cannot happen together.', d: 'Easy' },
    { q: 'The general addition rule for any two events A and B is:', c: 'P(A ∪ B) = P(A) + P(B) - P(A ∩ B)', w1: 'P(A ∪ B) = P(A) + P(B)', w2: 'P(A ∪ B) = P(A) * P(B)', w3: 'P(A ∪ B) = P(A) - P(B)', exp: 'Prevents double counting of intersection.', d: 'Easy' },
    { q: 'The conditional probability of A given B (where P(B) > 0) is defined as:', c: 'P(A | B) = P(A ∩ B) / P(B)', w1: 'P(A | B) = P(A ∩ B) / P(A)', w2: 'P(A | B) = P(A) * P(B)', w3: 'P(A | B) = P(A) / P(B)', exp: 'Definition of conditional probability.', d: 'Easy' },
    { q: 'Two events A and B are independent if and only if:', c: 'P(A ∩ B) = P(A) * P(B)', w1: 'P(A ∩ B) = 0', w2: 'P(A | B) = 0', w3: 'P(A) + P(B) = 1', exp: 'Multiplication rule for independent events.', d: 'Easy' },
    { q: 'If A and B are independent with P(A) = 0.4 and P(B) = 0.5, then P(A ∩ B) is:', c: '0.2', w1: '0.9', w2: '0.1', w3: '0.8', exp: '0.4 * 0.5 = 0.2.', d: 'Easy' },
    { q: 'The probability of the complement of event A, P(A\'), is:', c: '1 - P(A)', w1: 'P(A)', w2: '1 / P(A)', w3: '-P(A)', exp: 'P(A) + P(A\') = 1.', d: 'Easy' },
    { q: 'Bayes\' Theorem calculates:', c: 'The posterior probability P(B_i | A) from prior probabilities and likelihoods', w1: 'The sample variance', w2: 'The joint CDF', w3: 'The critical value Z', exp: 'P(B_i | A) = [P(A | B_i) P(B_i)] / Σ [P(A | B_j) P(B_j)].', d: 'Medium' },
    { q: 'The number of permutations of n distinct objects taken r at a time, nPr, is:', c: 'n! / (n - r)!', w1: 'n! / [r! (n - r)!]', w2: 'n! * r!', w3: '(n - r)! / n!', exp: 'Order matters in permutations.', d: 'Easy' },
    { q: 'The number of combinations of n objects taken r at a time, nCr or (n choose r), is:', c: 'n! / [r! (n - r)!]', w1: 'n! / (n - r)!', w2: 'r! / n!', w3: 'n! / r!', exp: 'Order does not matter in combinations.', d: 'Easy' },
    { q: 'For a discrete random variable X, the probability mass function (PMF) p(x) satisfies:', c: 'p(x) ≥ 0 and Σ p(x) = 1', w1: 'p(x) ≤ 1 and Σ p(x) = 0', w2: '∫ p(x) dx = 1', w3: 'p(x) can be negative', exp: 'Axioms of discrete probability mass function.', d: 'Easy' },
    { q: 'The expected value (mean) of a discrete random variable X is:', c: 'E[X] = Σ x * p(x)', w1: 'E[X] = Σ p(x)', w2: 'E[X] = Σ x² * p(x)', w3: 'E[X] = (Σ x) / n', exp: 'Definition of mathematical expectation.', d: 'Easy' },
    { q: 'The variance of random variable X is defined as:', c: 'Var(X) = E[X²] - (E[X])²', w1: 'Var(X) = E[X] - E[X²]', w2: 'Var(X) = (E[X])²', w3: 'Var(X) = E[X²]', exp: 'Var(X) = E[(X - μ)²] = E[X²] - μ².', d: 'Easy' },
    { q: 'For any constant c, Var(c X) equals:', c: 'c² * Var(X)', w1: 'c * Var(X)', w2: 'Var(X)', w3: 'c² + Var(X)', exp: 'Scaling property of variance: Var(aX + b) = a² Var(X).', d: 'Easy' },
    { q: 'For any constants a and b, E[a X + b] equals:', c: 'a E[X] + b', w1: 'a E[X]', w2: 'a² E[X] + b', w3: 'E[X] + b', exp: 'Linearity of expectation.', d: 'Easy' },
    { q: 'The standard deviation σ of a random variable is:', c: 'The positive square root of its variance, √Var(X)', w1: 'Var(X)²', w2: 'E[X]', w3: 'Var(X) / 2', exp: 'σ = √Var(X).', d: 'Easy' },
    { q: 'A Bernoulli random variable with success probability p has variance:', c: 'p(1 - p)', w1: 'p', w2: 'p²', w3: '1 - p', exp: 'Var(X) = E[X²] - (E[X])² = p - p² = p(1 - p).', d: 'Easy' },
    { q: 'A Binomial random variable X ~ Bin(n, p) models:', c: 'The number of successes in n independent Bernoulli trials with constant probability p', w1: 'The number of trials until the first success', w2: 'The time between arrivals', w3: 'Continuous measurements', exp: 'Definition of binomial experiment.', d: 'Easy' },
    { q: 'The PMF of X ~ Bin(n, p) is P(X = k) =', c: '(n choose k) * p^k * (1 - p)^(n - k)', w1: 'p^k * (1 - p)^(n - k)', w2: '(n choose k) * p^k', w3: 'n * p^k', exp: 'Binomial probability formula.', d: 'Easy' },
    { q: 'The mean μ and variance σ² of X ~ Bin(n, p) are:', c: 'μ = n p, and σ² = n p (1 - p)', w1: 'μ = p, and σ² = p(1 - p)', w2: 'μ = n p, and σ² = n p', w3: 'μ = n / p, and σ² = n / p²', exp: 'Expectation and variance of binomial distribution.', d: 'Easy' },
    { q: 'A coin is tossed 4 times. What is the probability of getting exactly 2 heads?', c: '6 / 16 = 3 / 8', w1: '1 / 4', w2: '1 / 2', w3: '4 / 16', exp: '(4 choose 2)(1/2)⁴ = 6 * (1/16) = 3/8.', d: 'Easy' },
    { q: 'The Poisson distribution with parameter λ models:', c: 'The number of events occurring in a fixed interval of time or space at a constant average rate', w1: 'The number of trials until the first success', w2: 'Continuous variables with normal distribution', w3: 'Coin tosses with varying p', exp: 'Definition of Poisson process.', d: 'Easy' },
    { q: 'The PMF of a Poisson random variable X ~ Poisson(λ) is P(X = k) =', c: '(e^(-λ) * λ^k) / k!', w1: 'e^(-λ) * λ^k', w2: 'λ^k / k!', w3: '(1 - e^(-λ))^k', exp: 'Standard Poisson PMF formula.', d: 'Easy' },
    { q: 'For a Poisson distribution with parameter λ, the variance is:', c: 'λ (equal to the mean)', w1: 'λ²', w2: '√λ', w3: 'λ(1 - λ)', exp: 'A unique property of Poisson: Mean = Variance = λ.', d: 'Easy' },
    { q: 'The Geometric distribution models:', c: 'The number of Bernoulli trials required to get the first success', w1: 'The number of successes in n trials', w2: 'The number of defective items in a batch without replacement', w3: 'The sum of two dies', exp: 'Definition of geometric distribution.', d: 'Easy' },
    { q: 'The PMF of a Geometric random variable with success probability p is P(X = k) =', c: '(1 - p)^(k - 1) * p for k = 1, 2, ...', w1: 'p^k * (1 - p)', w2: '(1 - p)^k', w3: 'p / k', exp: 'k - 1 failures followed by 1 success.', d: 'Easy' },
    { q: 'The memoryless property of the Geometric distribution means:', c: 'P(X > s + t | X > s) = P(X > t)', w1: 'P(X = s + t) = P(X = s) P(X = t)', w2: 'Var(X) = 0', w3: 'The mean is independent of p', exp: 'Future trials do not depend on past failures.', d: 'Medium' },
    { q: 'Sampling WITHOUT replacement from a finite population of size N containing K successes follows:', c: 'The Hypergeometric distribution', w1: 'The Binomial distribution', w2: 'The Poisson distribution', w3: 'The Geometric distribution', exp: 'Non-replacement causes trials to be dependent, described by Hypergeometric.', d: 'Medium' },
    { q: 'If E[X] = 3 and E[X²] = 13, then Var(X) is:', c: '4', w1: '10', w2: '7', w3: '16', exp: 'Var(X) = 13 - 3² = 13 - 9 = 4.', d: 'Easy' },
    { q: 'If P(A) = 0.7, P(B) = 0.4, and P(A ∩ B) = 0.3, find P(A ∪ B):', c: '0.8', w1: '1.1', w2: '0.4', w3: '0.5', exp: '0.7 + 0.4 - 0.3 = 0.8.', d: 'Easy' },
    { q: 'The cumulative distribution function (CDF) F(x) of a random variable X is defined as:', c: 'F(x) = P(X ≤ x)', w1: 'F(x) = P(X = x)', w2: 'F(x) = P(X > x)', w3: 'F(x) = E[X]', exp: 'Fundamental definition of CDF.', d: 'Easy' }
  ];

  const statsFinal = [
    { q: 'For a continuous random variable X with probability density function (PDF) f(x), P(X = c) for any exact value c is:', c: '0', w1: 'f(c)', w2: '1', w3: 'Undefined', exp: 'The probability of any specific single point for a continuous RV is always zero.', d: 'Easy' },
    { q: 'A valid probability density function f(x) must satisfy:', c: 'f(x) ≥ 0 for all x, and ∫_{-∞}^∞ f(x) dx = 1', w1: 'f(x) ≤ 1 and Σ f(x) = 1', w2: '∫ f(x) dx = 0', w3: 'f(x) is constant', exp: 'Two fundamental conditions for any continuous PDF.', d: 'Easy' },
    { q: 'The relationship between the CDF F(x) and the PDF f(x) of a continuous random variable is:', c: 'f(x) = F\'(x) = dF/dx', w1: 'F(x) = f\'(x)', w2: 'f(x) = F(x)²', w3: 'f(x) = 1 / F(x)', exp: 'By Fundamental Theorem of Calculus: F(x) = ∫_{-∞}^x f(t) dt => F\'(x) = f(x).', d: 'Easy' },
    { q: 'If X is uniformly distributed on [a, b], its PDF is:', c: 'f(x) = 1 / (b - a) for a ≤ x ≤ b', w1: 'f(x) = 1 / (b + a)', w2: 'f(x) = (b - a)', w3: 'f(x) = x / (b - a)', exp: 'Constant height 1/(b - a) so total area is 1.', d: 'Easy' },
    { q: 'The mean and variance of a uniform distribution U(a, b) are:', c: 'μ = (a + b) / 2, and σ² = (b - a)² / 12', w1: 'μ = (a + b) / 2, and σ² = (b - a) / 2', w2: 'μ = b - a, and σ² = (b - a)²', w3: 'μ = 0, and σ² = 1', exp: 'Standard formulas for continuous uniform distribution.', d: 'Easy' },
    { q: 'The Exponential distribution X ~ Exp(λ) has PDF:', c: 'f(x) = λ e^(-λx) for x ≥ 0', w1: 'f(x) = e^(-λx)', w2: 'f(x) = λ e^(λx)', w3: 'f(x) = (1/λ) e^(-x)', exp: 'Standard PDF of exponential distribution.', d: 'Easy' },
    { q: 'The mean and variance of an Exponential distribution with parameter λ are:', c: 'μ = 1 / λ, and σ² = 1 / λ²', w1: 'μ = λ, and σ² = λ', w2: 'μ = 1 / λ, and σ² = 1 / λ', w3: 'μ = λ, and σ² = λ²', exp: 'Mean is 1/λ and standard deviation is also 1/λ.', d: 'Easy' },
    { q: 'The only continuous probability distribution that possesses the memoryless property is:', c: 'The Exponential distribution', w1: 'The Normal distribution', w2: 'The Uniform distribution', w3: 'The Student t-distribution', exp: 'P(X > s + t | X > s) = P(X > t) holds uniquely for exponential.', d: 'Medium' },
    { q: 'The Normal (Gaussian) distribution N(μ, σ²) is symmetric about:', c: 'Its mean μ (where mean = median = mode)', w1: 'x = 0 always', w2: 'x = σ', w3: 'x = 1', exp: 'Bell curve is perfectly symmetric around μ.', d: 'Easy' },
    { q: 'A normal random variable X ~ N(μ, σ²) is standardized to Z ~ N(0, 1) using the transformation:', c: 'Z = (X - μ) / σ', w1: 'Z = (X - σ) / μ', w2: 'Z = (X - μ)² / σ', w3: 'Z = X - μ', exp: 'Z-score formula: subtract mean and divide by standard deviation.', d: 'Easy' },
    { q: 'The standard normal distribution Z has mean and variance:', c: 'μ = 0, and σ² = 1', w1: 'μ = 1, and σ² = 0', w2: 'μ = 0, and σ² = 0', w3: 'μ = 1, and σ² = 1', exp: 'By definition of standard normal distribution.', d: 'Easy' },
    { q: 'According to the Empirical Rule (68-95-99.7 rule) for a normal distribution:', c: '68% of data falls within μ ± σ, 95% within μ ± 2σ, and 99.7% within μ ± 3σ', w1: '50% within μ ± σ', w2: '90% within μ ± σ', w3: '100% within μ ± 2σ', exp: 'Standard three-sigma rule of thumb.', d: 'Easy' },
    { q: 'For standard normal Z, the value of P(Z < 0) is:', c: '0.5', w1: '0', w2: '1', w3: '0.68', exp: 'Symmetry of the bell curve about 0 divides area in half.', d: 'Easy' },
    { q: 'The Central Limit Theorem (CLT) states that for a random sample of size n from any population with mean μ and variance σ²:', c: 'The sample mean X̄ approaches N(μ, σ²/n) as n becomes large (typically n ≥ 30)', w1: 'The sample mean is always exactly equal to μ', w2: 'The sample variance approaches 0', w3: 'The population distribution becomes normal', exp: 'Foundation of statistical inference.', d: 'Medium' },
    { q: 'The standard error of the sample mean X̄ is given by:', c: 'σ / √n', w1: 'σ / n', w2: 'σ² / n', w3: 'σ * √n', exp: 'Standard deviation of the sampling distribution of X̄.', d: 'Easy' },
    { q: 'The covariance between two random variables X and Y is defined as:', c: 'Cov(X, Y) = E[XY] - E[X] E[Y]', w1: 'Cov(X, Y) = E[X] E[Y]', w2: 'Cov(X, Y) = E[X + Y]', w3: 'Cov(X, Y) = Var(X) Var(Y)', exp: 'Cov(X, Y) = E[(X - μ_X)(Y - μ_Y)].', d: 'Easy' },
    { q: 'If X and Y are independent random variables, their covariance Cov(X, Y) is:', c: '0', w1: '1', w2: '-1', w3: 'Undefined', exp: 'Independence implies E[XY] = E[X]E[Y], so Cov = 0.', d: 'Easy' },
    { q: 'Does Cov(X, Y) = 0 imply that X and Y are independent?', c: 'No, uncorrelated does not necessarily imply independence (except for bivariate normal)', w1: 'Yes, always', w2: 'Only if both are uniform', w3: 'Only if n > 30', exp: 'Nonlinear relationships can have zero linear correlation.', d: 'Medium' },
    { q: 'The Pearson correlation coefficient ρ between X and Y is defined as:', c: 'ρ = Cov(X, Y) / (σ_X * σ_Y)', w1: 'ρ = Cov(X, Y) / (σ_X² * σ_Y²)', w2: 'ρ = Cov(X, Y) * σ_X * σ_Y', w3: 'ρ = Var(X) / Var(Y)', exp: 'Normalized covariance.', d: 'Easy' },
    { q: 'The range of the Pearson correlation coefficient ρ is:', c: '[-1, 1]', w1: '[0, 1]', w2: '(-∞, ∞)', w3: '[-100, 100]', exp: 'Cauchy-Schwarz inequality guarantees |ρ| ≤ 1.', d: 'Easy' },
    { q: 'If ρ = +1, this indicates:', c: 'A perfect positive linear relationship between X and Y', w1: 'No relationship', w2: 'A weak relationship', w3: 'A negative relationship', exp: 'Points fall exactly on a line with positive slope.', d: 'Easy' },
    { q: 'If X and Y are independent, then Var(X - Y) equals:', c: 'Var(X) + Var(Y)', w1: 'Var(X) - Var(Y)', w2: 'Var(X) * Var(Y)', w3: '0', exp: 'Variances always add: Var(aX + bY) = a²Var(X) + b²Var(Y) for independent variables.', d: 'Medium' },
    { q: 'The sample variance s² of a sample of size n is computed with denominator n - 1 (Bessel\'s correction) to make s²:', c: 'An unbiased estimator of the population variance σ²', w1: 'Easier to compute', w2: 'Always an integer', w3: 'Equal to the mean', exp: 'Dividing by n - 1 corrects the downward bias.', d: 'Medium' },
    { q: 'A 95% confidence interval for population mean μ when σ is known uses critical value Z_{α/2} equal to:', c: '1.96', w1: '1.645', w2: '2.576', w3: '3.0', exp: 'Standard two-tailed critical Z for α = 0.05 is 1.96.', d: 'Easy' },
    { q: 'When population variance σ² is UNKNOWN and sample size n is small (< 30), which distribution is used for confidence intervals of μ?', c: 'Student\'s t-distribution with n - 1 degrees of freedom', w1: 'Standard normal distribution Z', w2: 'Chi-square distribution', w3: 'F-distribution', exp: 'William Gosset\'s Student\'s t-distribution compensates for estimating σ with s.', d: 'Medium' },
    { q: 'As the degrees of freedom increase to infinity, Student\'s t-distribution approaches:', c: 'The Standard Normal distribution Z', w1: 'The Uniform distribution', w2: 'The Poisson distribution', w3: 'A constant value', exp: 'Heavier tails converge to normal as sample size grows.', d: 'Easy' },
    { q: 'In hypothesis testing, a Type I error occurs when:', c: 'The null hypothesis H₀ is rejected when it is actually true (false positive)', w1: 'H₀ is accepted when it is false', w2: 'The sample size is too small', w3: 'The test statistic is zero', exp: 'P(Type I error) = α (significance level).', d: 'Easy' },
    { q: 'In hypothesis testing, a Type II error occurs when:', c: 'The null hypothesis H₀ is NOT rejected when it is actually false (false negative)', w1: 'H₀ is rejected when true', w2: 'The significance level is 0.05', w3: 'The p-value is zero', exp: 'P(Type II error) = β; Power of the test = 1 - β.', d: 'Easy' },
    { q: 'The p-value of a statistical test is:', c: 'The probability of observing a test statistic as extreme as, or more extreme than, the observed value, assuming H₀ is true', w1: 'The probability that H₀ is true', w2: 'The probability of making a Type I error', w3: 'The critical value Z', exp: 'Standard definition of p-value.', d: 'Medium' },
    { q: 'If the p-value is less than or equal to the significance level α (e.g., p ≤ 0.05), we:', c: 'Reject the null hypothesis H₀ in favor of H₁ (statistically significant result)', w1: 'Fail to reject H₀', w2: 'Accept H₀ as completely proven', w3: 'Restart the experiment', exp: 'Decision rule: p ≤ α => Reject H₀.', d: 'Easy' },
    { q: 'The Chi-Square (χ²) goodness-of-fit test is used to:', c: 'Determine whether observed categorical frequencies match expected theoretical frequencies', w1: 'Compare two population means', w2: 'Find the correlation coefficient', w3: 'Compute the median', exp: 'χ² = Σ (O - E)² / E.', d: 'Medium' },
    { q: 'The F-distribution is used primarily in:', c: 'Analysis of Variance (ANOVA) and testing equality of two population variances', w1: 'Testing a single proportion', w2: 'Finding the sample median', w3: 'Normal probability plots', exp: 'Ratio of two independent chi-square variables divided by their degrees of freedom.', d: 'Medium' },
    { q: 'The mode of a dataset is defined as:', c: 'The value that appears most frequently', w1: 'The middle value when sorted', w2: 'The arithmetic average', w3: 'The difference between max and min', exp: 'Definition of statistical mode.', d: 'Easy' },
    { q: 'If a dataset has a mean of 50 and a median of 65, the distribution is most likely:', c: 'Negatively skewed (skewed to the left)', w1: 'Positively skewed (skewed to the right)', w2: 'Symmetric (normal)', w3: 'Uniform', exp: 'Mean < Median indicates a tail pulling to the left (negative skew).', d: 'Medium' },
    { q: 'If a distribution is positively skewed (skewed to the right):', c: 'Mean > Median > Mode', w1: 'Mode > Median > Mean', w2: 'Mean = Median = Mode', w3: 'Median > Mean > Mode', exp: 'Long right tail pulls the mean upward.', d: 'Medium' },
    { q: 'The interquartile range (IQR) is calculated as:', c: 'Q₃ - Q₁ (75th percentile minus 25th percentile)', w1: 'Max - Min', w2: 'Q₂ - Q₁', w3: 'Q₃ + Q₁', exp: 'Measures the spread of the middle 50% of observations.', d: 'Easy' },
    { q: 'In a boxplot, an outlier is conventionally defined as any point lying beyond:', c: '1.5 * IQR below Q₁ or above Q₃', w1: '3 * IQR', w2: '0.5 * IQR', w3: 'The mean', exp: 'Tukey\'s standard fence rule.', d: 'Easy' },
    { q: 'The power of a statistical test is defined as:', c: '1 - β (the probability of correctly rejecting a false null hypothesis)', w1: '1 - α', w2: 'β', w3: 'α', exp: 'Statistical power = P(Reject H₀ | H₀ is false) = 1 - β.', d: 'Medium' },
    { q: 'For independent random variables X ~ N(10, 4) and Y ~ N(15, 9), the distribution of X + Y is:', c: 'N(25, 13)', w1: 'N(25, 5)', w2: 'N(25, 25)', w3: 'N(150, 36)', exp: 'Means add (10 + 15 = 25), variances add (4 + 9 = 13).', d: 'Medium' },
    { q: 'If a random variable has moment generating function M_X(t) = e^(3t + 2t²), then X is distributed as:', c: 'Normal N(μ = 3, σ² = 4)', w1: 'Normal N(3, 2)', w2: 'Poisson(3)', w3: 'Exponential(3)', exp: 'MGF of normal is e^(μt + σ²t²/2). Here σ²/2 = 2 => σ² = 4.', d: 'Hard' },
    { q: 'Chebyshev\'s Inequality states that for any distribution, P(|X - μ| ≥ k σ) is at most:', c: '1 / k²', w1: '1 / k', w2: 'k²', w3: '1 - 1/k²', exp: 'P(|X - μ| ≥ kσ) ≤ 1/k² for any k > 1.', d: 'Medium' },
    { q: 'A paired t-test is used when:', c: 'Observations are paired or matched (e.g., before-and-after measurements on the same subjects)', w1: 'Two samples are completely independent', w2: 'Data is categorical', w3: 'Sample sizes are greater than 1000', exp: 'Reduces to a one-sample t-test on the differences d_i = x_{1i} - x_{2i}.', d: 'Easy' },
    { q: 'The coefficient of determination R² in simple linear regression represents:', c: 'The proportion of total variation in Y explained by the linear regression model with X', w1: 'The slope of the regression line', w2: 'The correlation coefficient without sign', w3: 'The error variance', exp: 'R² = SSR / SST = 1 - (SSE / SST).', d: 'Medium' },
    { q: 'In simple linear regression y = β₀ + β₁ x + ε, the least squares estimator b₁ for slope is:', c: 'Cov(x, y) / Var(x) = S_xy / S_xx', w1: 'S_xx / S_xy', w2: 'ȳ - b₀', w3: 'r²', exp: 'b₁ = Σ(x - x̄)(y - ȳ) / Σ(x - x̄)².', d: 'Medium' },
    { q: 'What is the sum of the residuals Σ (y_i - ŷ_i) in an OLS regression that includes an intercept?', c: 'Exactly 0', w1: '1', w2: 'Equal to the variance', w3: 'Depends on the sample size', exp: 'Normal equations guarantee residuals sum to zero.', d: 'Medium' },
    { q: 'The joint probability density function f(x, y) of independent RVs X and Y satisfies:', c: 'f(x, y) = f_X(x) * f_Y(y)', w1: 'f(x, y) = f_X(x) + f_Y(y)', w2: 'f(x, y) = 0', w3: 'f(x, y) = f_X(x) / f_Y(y)', exp: 'Independence factorizes the joint density.', d: 'Easy' },
    { q: 'The marginal PDF f_X(x) is obtained from joint PDF f(x, y) by:', c: 'Integrating out y: ∫_{-∞}^∞ f(x, y) dy', w1: 'Differentiating with respect to y', w2: 'Setting y = 0', w3: 'Multiplying by y', exp: 'Marginalization integrates over the unwanted variable.', d: 'Easy' },
    { q: 'If X ~ N(0, 1), what is the distribution of X²?', c: 'Chi-Square distribution with 1 degree of freedom (χ²₁)', w1: 'Standard normal N(0, 1)', w2: 'Exponential(1)', w3: 'Uniform(0, 1)', exp: 'Square of a standard normal is chi-square with df = 1.', d: 'Medium' },
    { q: 'The sum of k independent squared standard normal variables Σ_{i=1}^k Z_i² has:', c: 'Chi-Square distribution with k degrees of freedom (χ²_k)', w1: 'Normal distribution N(0, k)', w2: 'Student t-distribution with k df', w3: 'F-distribution', exp: 'Definition of the Chi-Square distribution.', d: 'Medium' },
    { q: 'The ratio [Z / √(V / k)] where Z ~ N(0, 1) and V ~ χ²_k are independent follows:', c: 'Student\'s t-distribution with k degrees of freedom', w1: 'F-distribution', w2: 'Chi-Square distribution', w3: 'Standard normal Z', exp: 'Exact mathematical definition of Student\'s t-distribution.', d: 'Hard' },
    { q: 'The ratio (U / d₁) / (V / d₂) of two independent chi-square variables divided by their degrees of freedom follows:', c: 'Snedecor\'s F-distribution with (d₁, d₂) degrees of freedom', w1: 'Student\'s t-distribution', w2: 'Chi-Square distribution', w3: 'Normal distribution', exp: 'Definition of the F-distribution.', d: 'Hard' },
    { q: 'A 99% confidence interval is:', c: 'Wider than a 95% confidence interval for the same sample', w1: 'Narrower than a 95% confidence interval', w2: 'The same width', w3: 'Always centered at 0', exp: 'Higher confidence requires a larger critical value Z or t, widening the interval.', d: 'Easy' }
  ];

  statsMid.forEach((it, idx) => qs.push(createQuestion(`STAT-MID-${String(idx + 1).padStart(3, '0')}`, 'subj-stats', false, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'Probability Mid Exam.pdf', idx)));
  statsFinal.forEach((it, idx) => qs.push(createQuestion(`STAT-FIN-${String(idx + 1).padStart(3, '0')}`, 'subj-stats', true, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'Probability Final Exam.pdf', idx)));

  return qs;
}

module.exports = { getNumAndStatsQuestions };
