const { createQuestion } = require('./bank_factory');

function getCppAndOopQuestions() {
  const qs = [];

  // =========================================================================
  // 1. C++ PROGRAMMING FOR ENGINEERS (subj-cpp) - 100% PROCEDURAL (NO OOP!)
  // Mid: 32 Questions (Variables, Data types, Operators, Control flow, Loops, Functions, Overloading, References)
  // Final: 52 Questions (1D & 2D Arrays, Searching/Sorting, Pointers, C-Strings, std::string, Structs, File I/O, Recursion, Tracing)
  // =========================================================================
  const cppMid = [
    { q: 'Which header file is required in C++ for standard input and output streams like cin and cout?', c: '#include <iostream>', w1: '#include <stdio.h>', w2: '#include <conio.h>', w3: '#include <stream.h>', exp: '<iostream> defines the standard input/output stream objects cin, cout, cerr, and clog.', d: 'Easy' },
    { q: 'What is the correct syntax to output "Hello World" in C++ followed by a new line?', c: 'cout << "Hello World" << endl;', w1: 'System.out.print("Hello World");', w2: 'print("Hello World");', w3: 'Console.WriteLine("Hello World");', exp: 'C++ uses the stream insertion operator (<<) with cout and endl.', d: 'Easy' },
    { q: 'Which C++ operator is used to calculate the remainder of integer division?', c: '% (modulo operator)', w1: '/', w2: '//', w3: 'mod', exp: 'The % operator computes the remainder of integer division.', d: 'Easy' },
    { q: 'What is the value of x and a after: int a = 5; int x = ++a; ?', c: 'x = 6, a = 6', w1: 'x = 5, a = 6', w2: 'x = 6, a = 5', w3: 'x = 5, a = 5', exp: 'Pre-increment (++a) increments variable a first, then evaluates and assigns the new value to x.', d: 'Easy' },
    { q: 'What is the value of y and a after: int a = 5; int y = a++; ?', c: 'y = 5, a = 6', w1: 'y = 6, a = 6', w2: 'y = 6, a = 5', w3: 'y = 5, a = 5', exp: 'Post-increment (a++) assigns the current value of a to y first, then increments a to 6.', d: 'Easy' },
    { q: 'What is the size of the fundamental data type \'char\' in C++ according to the ISO standard?', c: '1 byte (at least 8 bits)', w1: '2 bytes', w2: '4 bytes', w3: '8 bytes', exp: 'sizeof(char) is defined to be exactly 1 byte in C++.', d: 'Easy' },
    { q: 'Which data type is used to store boolean true or false values in C++?', c: 'bool', w1: 'boolean', w2: 'bit', w3: 'int only', exp: 'The native keyword in C++ for boolean logical values is bool.', d: 'Easy' },
    { q: 'What is the output of: cout << (10 / 4); in C++?', c: '2', w1: '2.5', w2: '2.0', w3: '3', exp: 'Integer division between integer 10 and integer 4 truncates the decimal portion, yielding 2.', d: 'Easy' },
    { q: 'How can you obtain the exact floating-point division result 2.5 from integer variables a = 10 and b = 4?', c: '(double)a / b or static_cast<double>(a) / b', w1: 'a / b', w2: 'double(a / b)', w3: 'int(a) / int(b)', exp: 'Casting at least one operand to double or float forces floating-point arithmetic.', d: 'Easy' },
    { q: 'In a switch statement in C++, what happens if a matching case does NOT contain a \'break\' statement?', c: 'Execution falls through to the subsequent cases until a break or the end of the switch block is reached', w1: 'The program terminates with a runtime error', w2: 'The switch immediately exits', w3: 'The default case executes immediately', exp: 'Without a break statement, control flows into subsequent cases regardless of their case values (fall-through).', d: 'Easy' },
    { q: 'What is the output of the loop: for (int i = 0; i < 5; i += 2) cout << i << " "; ?', c: '0 2 4 ', w1: '0 1 2 3 4 ', w2: '0 2 4 6 ', w3: '2 4 ', exp: 'Loop executes for i = 0, i = 2, and i = 4. When i becomes 6, 6 < 5 is false and loop terminates.', d: 'Easy' },
    { q: 'How many times will a do-while loop execute its body at minimum?', c: 'At least 1 time', w1: '0 times', w2: 'Infinitely', w3: '2 times', exp: 'do-while is a post-test loop; the loop condition is evaluated at the bottom, guaranteeing at least one execution.', d: 'Easy' },
    { q: 'Which control statement immediately terminates and exits the innermost enclosing loop or switch?', c: 'break;', w1: 'continue;', w2: 'exit;', w3: 'return 0;', exp: 'break immediately jumps execution out of the current loop or switch block.', d: 'Easy' },
    { q: 'Which statement skips the remaining statements in the current loop iteration and proceeds to the next iteration?', c: 'continue;', w1: 'break;', w2: 'goto;', w3: 'skip;', exp: 'continue jumps immediately to the loop update expression and condition evaluation.', d: 'Easy' },
    { q: 'What is the logical AND operator in C++?', c: '&&', w1: '&', w2: 'AND', w3: '||', exp: '&& is the logical AND operator featuring short-circuit evaluation; & is the bitwise AND operator.', d: 'Easy' },
    { q: 'What is short-circuit evaluation in C++ boolean expressions (e.g. A && B)?', c: 'If operand A evaluates to false, operand B is not evaluated at all', w1: 'Both operands are always evaluated simultaneously', w2: 'If A is true, B is not evaluated', w3: 'An electrical short in the CPU', exp: 'In logical AND (A && B), if the first expression is false, the overall outcome must be false, so B is skipped.', d: 'Medium' },
    { q: 'Which header file is required to use mathematical functions like sqrt(), pow(), and abs()?', c: '#include <cmath>', w1: '#include <math>', w2: '#include <algorithm>', w3: '#include <numbers>', exp: '<cmath> provides standard C++ mathematical functions.', d: 'Easy' },
    { q: 'What does the function pow(2.0, 3.0) from <cmath> return?', c: '8.0 (2 raised to the power 3)', w1: '6.0', w2: '9.0', w3: '5.0', exp: 'pow(base, exponent) calculates base^exponent: 2^3 = 8.', d: 'Easy' },
    { q: 'What is the return type of a function that does not return any value to the caller?', c: 'void', w1: 'int', w2: 'null', w3: 'empty', exp: 'void indicates that the function performs an action but returns no value.', d: 'Easy' },
    { q: 'What is a function prototype (forward declaration) in C++?', c: 'A declaration specifying the function name, return type, and parameter types before main() so the compiler knows it exists', w1: 'The full function body with code', w2: 'A macro definition', w3: 'A built-in library function', exp: 'Prototypes inform the compiler of a function signature before its full definition appears.', d: 'Easy' },
    { q: 'What happens when an argument is passed BY VALUE to a function (e.g. void func(int x))?', c: 'A copy of the argument value is made; changes to x inside the function do NOT affect the caller original variable', w1: 'The caller variable is modified directly', w2: 'The memory address is passed', w3: 'A compiler error occurs', exp: 'Pass-by-value copies the parameter, insulating the caller variable from modification.', d: 'Easy' },
    { q: 'What happens when an argument is passed BY REFERENCE (e.g. void swap(int &a, int &b))?', c: 'The function receives an alias to the original variable; modifications inside the function directly change the caller variable', w1: 'A duplicate copy is made', w2: 'The function cannot modify the variable', w3: 'Memory leaks occur', exp: 'The reference (&) passes the actual variable itself, allowing direct updates.', d: 'Easy' },
    { q: 'What is function overloading in procedural C++?', c: 'Defining multiple functions with the SAME name but DIFFERENT parameter lists (types, number of parameters)', w1: 'Functions with the same name and parameters but different return types only', w2: 'Calling a function too many times in a loop', w3: 'Defining a function inside another function', exp: 'C++ distinguishes overloaded functions by their parameter signature, not return type alone.', d: 'Medium' },
    { q: 'Can a C++ function be overloaded based solely on a different return type (e.g. int f(); vs double f();)?', c: 'No, function overloading requires different parameter types or parameter count', w1: 'Yes, always', w2: 'Only if declared inline', w3: 'Only in header files', exp: 'Return type alone is not sufficient to distinguish overloaded function calls.', d: 'Medium' },
    { q: 'What is a default argument in a C++ function parameter list?', c: 'A value automatically assigned to a parameter if the caller does not supply an argument for it', w1: 'The return value of main()', w2: 'The zero value of global variables', w3: 'A mandatory parameter', exp: 'Default parameters allow optional function arguments (e.g. void print(int x = 10)).', d: 'Easy' },
    { q: 'Where must default parameters be positioned in a function parameter list?', c: 'At the end of the parameter list (all parameters to the right of a default parameter must also have defaults)', w1: 'At the beginning only', w2: 'Anywhere in the list', w3: 'Only on the first parameter', exp: 'Default arguments must trail non-default arguments to avoid ambiguity during calling.', d: 'Medium' },
    { q: 'What is the scope and lifetime of a local variable declared inside a function block?', c: 'Scope is limited to that block; lifetime begins upon declaration and ends when the block exits', w1: 'Scope is global; lifetime is program duration', w2: 'Lifetime is permanent in RAM', w3: 'Scope is across all files', exp: 'Automatic local variables are allocated on the stack and destroyed upon block exit.', d: 'Easy' },
    { q: 'What is a static local variable inside a C++ function (e.g. static int count = 0;)?', c: 'A variable initialized only once that retains its value between multiple calls to that function', w1: 'A variable that cannot be changed (constant)', w2: 'A variable allocated on stack every call', w3: 'A global variable accessible everywhere', exp: 'static local variables have local block scope but static storage duration (lifetime of the program).', d: 'Medium' },
    { q: 'Which header file is required to format stream output with manipulators like setw(), setprecision(), and fixed?', c: '#include <iomanip>', w1: '#include <format>', w2: '#include <iostream>', w3: '#include <string>', exp: '<iomanip> defines parameterized stream manipulators such as setw, setprecision, and setfill.', d: 'Easy' },
    { q: 'What is the effect of: cout << fixed << setprecision(2) << 3.14159; ?', c: 'Displays 3.14 (fixed-point notation with exactly 2 digits after the decimal point)', w1: 'Displays 3.1', w2: 'Displays 3', w3: 'Displays 3.141', exp: 'fixed combined with setprecision(n) fixes the number of fractional decimal digits to n.', d: 'Easy' },
    { q: 'What does the setw(5) manipulator do when printing output with cout?', c: 'Sets the minimum field width for the next printed output item to 5 character positions', w1: 'Sets the font size to 5', w2: 'Prints 5 spaces unconditionally', w3: 'Truncates output to 5 letters', exp: 'setw(w) pads the next single output value with spaces so it occupies at least w characters.', d: 'Easy' },
    { q: 'What is the ternary conditional operator in C++?', c: 'condition ? expression_if_true : expression_if_false', w1: 'if then else', w2: 'condition ?? true :: false', w3: 'condition : true ? false', exp: 'The ternary operator (?:) provides an inline compact conditional expression.', d: 'Easy' }
  ];

  const cppFinal = [
    // 52 Questions: 100% PURE PROCEDURAL (1D & 2D Arrays, Searching/Sorting, Pointers, C-Strings, std::string, Structs, File I/O, Recursion, Tracing)
    { q: 'How do you declare a static 1D array of 10 integers in procedural C++?', c: 'int arr[10];', w1: 'int arr(10);', w2: 'array<int> arr = 10;', w3: 'int arr[] = 10;', exp: 'Standard C-style 1D array declaration: type name[size];', d: 'Easy' },
    { q: 'What is the valid index range for an array declared as int arr[10]?', c: '0 to 9', w1: '1 to 10', w2: '0 to 10', w3: '-1 to 9', exp: 'C++ uses zero-based indexing, so an array of size N has indices 0 through N-1.', d: 'Easy' },
    { q: 'What happens if a program reads or writes to arr[15] in an array declared as int arr[10]?', c: 'Undefined behavior (out-of-bounds access: memory corruption, garbage value, or crash)', w1: 'The array automatically expands to size 16', w2: 'The compiler always issues a compile-time syntax error', w3: 'It safely returns 0', exp: 'Raw C++ arrays do not perform runtime bounds checking.', d: 'Medium' },
    { q: 'How is a 1D array initialized with all zeros upon declaration?', c: 'int arr[10] = {0};', w1: 'int arr[10] = 0;', w2: 'int arr[10] = {zeros};', w3: 'int arr[10] = NULL;', exp: 'Initializing with {0} explicitly sets the first element to 0 and implicitly zero-initializes all remaining elements.', d: 'Easy' },
    { q: 'If an array is declared as int arr[5] = {3, 7};, what are the values of arr[2], arr[3], and arr[4]?', c: '0, 0, 0', w1: '3, 7, 3', w2: 'Garbage values', w3: 'Undefined', exp: 'When an initializer list has fewer elements than array size, the remaining elements are initialized to 0.', d: 'Easy' },
    { q: 'When passing a 1D array to a function (e.g. void process(int arr[], int size)), how is the array passed?', c: 'By pointer / reference to the first element (array decays to pointer int *arr)', w1: 'By value (an entire copy of all elements is created)', w2: 'By dynamic allocation', w3: 'By string stream', exp: 'Array names decay to a pointer to their first element (&arr[0]) when passed as function arguments.', d: 'Medium' },
    { q: 'Why is the size of an array typically passed as a separate parameter to functions in procedural C++?', c: 'Because the array decays to a pointer, losing information about its length (sizeof(arr) returns pointer size, not array size)', w1: 'To make the function run faster', w2: 'Because C++ limits function calls to 2 parameters', w3: 'It is optional and never needed', exp: 'Inside the function, sizeof(arr) evaluates to sizeof(int*), typically 4 or 8 bytes, so length must be passed explicitly.', d: 'Medium' },
    { q: 'How do you declare a 2D array (matrix) of integers with 3 rows and 4 columns?', c: 'int matrix[3][4];', w1: 'int matrix[4][3];', w2: 'int matrix[3, 4];', w3: 'int matrix(3, 4);', exp: 'Declaration syntax is type name[rows][columns]; so 3 rows and 4 columns is matrix[3][4].', d: 'Easy' },
    { q: 'In C++, how are multi-dimensional arrays stored in memory?', c: 'Row-Major Order (row by row contiguously in memory)', w1: 'Column-Major Order', w2: 'Diagonal-Major Order', w3: 'Random heap blocks', exp: 'C and C++ store 2D arrays in row-major order: all elements of row 0 are followed contiguously by row 1, etc.', d: 'Medium' },
    { q: 'Given int m[2][3] = {{1, 2, 3}, {4, 5, 6}};, what is the value of m[1][0]?', c: '4', w1: '1', w2: '2', w3: '5', exp: 'Row index 1 refers to the second row {4, 5, 6}, and column index 0 refers to the first element: 4.', d: 'Easy' },
    { q: 'How many elements are in a 2D array declared as double table[5][8]?', c: '40 elements (5 * 8)', w1: '13 elements', w2: '35 elements', w3: '80 elements', exp: 'Total elements = rows * columns = 5 * 8 = 40.', d: 'Easy' },
    { q: 'When passing a 2D array to a function, which dimension MUST be explicitly specified in the parameter declaration?', c: 'The column dimension (e.g. void func(int arr[][4], int rows))', w1: 'The row dimension only', w2: 'Neither dimension', w3: 'Both dimensions can be omitted', exp: 'The compiler needs the column width to compute memory offset address: *(arr + i * cols + j).', d: 'Medium' },
    { q: 'In a square matrix of size N x N, what condition identifies elements on the MAIN DIAGONAL?', c: 'row index equals column index (i == j)', w1: 'i + j == N - 1', w2: 'i > j', w3: 'i < j', exp: 'Main diagonal elements are matrix[0][0], matrix[1][1], matrix[2][2], etc., where i == j.', d: 'Easy' },
    { q: 'In an N x N square matrix, what condition identifies elements on the SECONDARY (anti) DIAGONAL?', c: 'i + j == N - 1 (or j == N - 1 - i)', w1: 'i == j', w2: 'i == 0', w3: 'i + j == N', exp: 'For 3x3: secondary diagonal entries are (0,2), (1,1), and (2,0), where i + j = 2 = N - 1.', d: 'Medium' },
    { q: 'What is the Linear Search algorithm time complexity to find an element in an unsorted 1D array of size n?', c: 'O(n) worst case', w1: 'O(1)', w2: 'O(log n)', w3: 'O(n^2)', exp: 'Linear search inspects elements sequentially from beginning to end, taking up to n comparisons.', d: 'Easy' },
    { q: 'What precondition is strictly required before performing a Binary Search on an array?', c: 'The array elements must be SORTED in ascending or descending order', w1: 'The array must contain only positive integers', w2: 'The array size must be an even number', w3: 'The array must be dynamic', exp: 'Binary search repeatedly divides the search space in half, which is valid only on ordered datasets.', d: 'Easy' },
    { q: 'What is the worst-case time complexity of Binary Search on a sorted array of size n?', c: 'O(log n)', w1: 'O(n)', w2: 'O(1)', w3: 'O(n log n)', exp: 'Binary search cuts the remaining search space in half at each step: log_2(n) comparisons.', d: 'Easy' },
    { q: 'In the Bubble Sort algorithm, how are adjacent elements sorted?', c: 'By repeatedly comparing adjacent elements and swapping them if they are in the wrong order', w1: 'By finding the global minimum and placing it at the front', w2: 'By dividing the array into two halves recursively', w3: 'By inserting elements into a binary heap', exp: 'Bubble sort bubbles the largest unsorted element to its correct final position in each pass.', d: 'Easy' },
    { q: 'What is the average and worst-case time complexity of Bubble Sort on an array of size n?', c: 'O(n^2)', w1: 'O(n log n)', w2: 'O(n)', w3: 'O(log n)', exp: 'Nested loops perform approximately n*(n-1)/2 comparisons, resulting in quadratic O(n^2) complexity.', d: 'Easy' },
    { q: 'How does Selection Sort work?', c: 'By finding the smallest element in the unsorted portion and swapping it with the first unsorted element', w1: 'By comparing adjacent pairs and swapping them', w2: 'By shifting elements one position to the right', w3: 'By hashing values into buckets', exp: 'Selection sort repeatedly selects the minimum element from the unsorted sub-array.', d: 'Easy' },
    { q: 'How is a C-style string represented in memory?', c: 'As an array of characters terminated by the null character \'\\0\'', w1: 'As an integer array with length at index 0', w2: 'As a linked list', w3: 'As a vector without terminator', exp: 'C-strings use a sentinel null byte (ASCII 0, \'\\0\') to mark the end of the text.', d: 'Easy' },
    { q: 'How many bytes of storage does the C-string literal "Jordan" require in memory?', c: '7 bytes (6 letters + 1 null terminator \'\\0\')', w1: '6 bytes', w2: '8 bytes', w3: '5 bytes', exp: '"Jordan" has 6 characters: \'J\',\'o\',\'r\',\'d\',\'a\',\'n\' plus the terminating \'\\0\', total 7 bytes.', d: 'Easy' },
    { q: 'Which function from <cstring> calculates the length of a C-string excluding the null terminator?', c: 'strlen(str)', w1: 'sizeof(str)', w2: 'str.length()', w3: 'strlength(str)', exp: 'strlen() counts characters up to (but not including) the terminating \'\\0\'.', d: 'Easy' },
    { q: 'Which function from <cstring> is used to copy string src into destination buffer dest?', c: 'strcpy(dest, src);', w1: 'dest = src;', w2: 'strcopy(dest, src);', w3: 'copy(src, dest);', exp: 'strcpy(dest, src) copies characters from src into dest including the null terminator.', d: 'Easy' },
    { q: 'What does the function strcmp(str1, str2) return if str1 is alphabetically identical to str2?', c: '0', w1: '1', w2: '-1', w3: 'true', exp: 'strcmp returns 0 when strings match, a negative value if str1 < str2, and positive if str1 > str2.', d: 'Easy' },
    { q: 'Which <cstring> function concatenates (appends) string src onto the end of string dest?', c: 'strcat(dest, src);', w1: 'dest + src;', w2: 'stradd(dest, src);', w3: 'append(dest, src);', exp: 'strcat appends src to dest, overwriting dest\'s null terminator and adding a new null terminator at the end.', d: 'Easy' },
    { q: 'Why does standard cin >> str; fail to read a full line of text with spaces (e.g. "Computer Networks")?', c: 'Because operator >> stops reading upon encountering whitespace (space, tab, newline)', w1: 'Because cin can only read numbers', w2: 'Because buffer overflow occurs', w3: 'Because string length is limited to 8 chars', exp: 'cin >> treats whitespace as a delimiter; to read full lines with spaces, cin.getline() or getline() must be used.', d: 'Easy' },
    { q: 'How do you read a full line of text with spaces into a C-string char name[50];?', c: 'cin.getline(name, 50);', w1: 'cin >> name;', w2: 'cin.get(name);', w3: 'scanf("%s", name);', exp: 'cin.getline(buffer, maxSize) reads up to (maxSize - 1) characters including spaces until newline.', d: 'Easy' },
    { q: 'How do you read a full line of text with spaces into a C++ string object (std::string line)?', c: 'getline(cin, line);', w1: 'cin >> line;', w2: 'cin.getline(line);', w3: 'line.read(cin);', exp: 'The standalone function getline(cin, line) from <string> reads a full line into a std::string.', d: 'Easy' },
    { q: 'What does the member function s.substr(2, 4) return for string s = "ABCDEFGH"?', c: '"CDEF" (4 characters starting at index 2)', w1: '"CDE"', w2: '"BCDE"', w3: '"DEFG"', exp: 's.substr(pos, count) extracts count characters beginning at 0-based index pos: indices 2,3,4,5 are "CDEF".', d: 'Medium' },
    { q: 'What does s.find("cat") return if the substring "cat" is NOT found in string s?', c: 'string::npos', w1: '-1', w2: '0', w3: 'NULL', exp: 'std::string::find returns the constant string::npos (maximum value of size_t) upon lookup failure.', d: 'Medium' },
    { q: 'What is a pointer variable in C++?', c: 'A variable that stores the physical memory address of another variable', w1: 'A variable that stores decimals', w2: 'A variable that points to a screen pixel', w3: 'A function pointer only', exp: 'A pointer stores the memory location (&var) of a data entity in system RAM.', d: 'Easy' },
    { q: 'What is the output of: int val = 25; int *ptr = &val; *ptr = 50; cout << val; ?', c: '50', w1: '25', w2: 'Memory address of val', w3: 'Garbage value', exp: '*ptr dereferences the pointer, directly updating the memory cell of val to 50.', d: 'Easy' },
    { q: 'If int arr[5] = {10, 20, 30, 40, 50}; and int *p = arr;, what does *(p + 2) evaluate to?', c: '30 (identical to arr[2])', w1: '12', w2: '20', w3: 'Address of arr[2]', exp: 'Pointer arithmetic: *(p + i) is mathematically identical to array indexing arr[i].', d: 'Easy' },
    { q: 'In pointer arithmetic, what does p++ do if p is a pointer to an integer (int *p) on a 32-bit integer system?', c: 'Advances the pointer address forward by sizeof(int) = 4 bytes', w1: 'Increments the stored integer value by 1', w2: 'Increases address by 1 byte', w3: 'Sets pointer to NULL', exp: 'Pointer increments scale by the size of the underlying target data type (sizeof(T)).', d: 'Medium' },
    { q: 'What is a null pointer (nullptr in modern C++ / NULL in C)?', c: 'A pointer that points to no valid memory address (evaluates to 0/false)', w1: 'An uninitialized pointer with garbage address', w2: 'A pointer to the number 0', w3: 'A deleted variable', exp: 'nullptr signifies that the pointer is intentionally not pointing to any valid object or memory cell.', d: 'Easy' },
    { q: 'What is a dangling pointer?', c: 'A pointer that continues to reference a memory location after the storage has been deallocated or gone out of scope', w1: 'A pointer with value nullptr', w2: 'A pointer inside a loop', w3: 'A pointer to a constant', exp: 'Dereferencing dangling pointers causes undefined behavior and segmentation faults.', d: 'Medium' },
    { q: 'Which operator is used to allocate an array of 50 integers dynamically on the heap in C++?', c: 'int *arr = new int[50];', w1: 'int *arr = malloc(50);', w2: 'int arr = new int(50);', w3: 'int *arr = alloc[50];', exp: 'The new[] operator dynamically allocates contiguous memory for an array on the heap.', d: 'Easy' },
    { q: 'Which operator MUST be used to free an array allocated dynamically with new[] to prevent memory leaks?', c: 'delete[] arr;', w1: 'delete arr;', w2: 'free(arr);', w3: 'remove arr;', exp: 'delete[] is mandatory for arrays allocated with new[]; using plain delete leads to undefined behavior.', d: 'Easy' },
    { q: 'What is a struct in procedural C++?', c: 'A user-defined composite data type that groups variables of different data types under a single name', w1: 'A loop structure', w2: 'A built-in math function', w3: 'A pointer type', exp: 'struct allows bundling related heterogeneous fields (e.g. name, age, GPA) into a single record.', d: 'Easy' },
    { q: 'Given struct Student { int id; double gpa; }; Student s1;, how do you access the gpa member?', c: 's1.gpa', w1: 's1->gpa', w2: 's1::gpa', w3: 's1[gpa]', exp: 'The dot operator (.) accesses members of a struct object instance.', d: 'Easy' },
    { q: 'Given Student *sPtr = &s1;, how do you access the gpa member through the pointer sPtr?', c: 'sPtr->gpa (or (*sPtr).gpa)', w1: 'sPtr.gpa', w2: 'sPtr::gpa', w3: '&sPtr.gpa', exp: 'The arrow operator (->) dereferences the pointer and accesses the member field.', d: 'Easy' },
    { q: 'Can an array of structs be declared in C++ (e.g. Student classList[100];)?', c: 'Yes, creating a collection of 100 individual Student struct records accessible by index', w1: 'No, structs cannot be in arrays', w2: 'Only dynamically with pointers', w3: 'Only up to 10 elements', exp: 'Arrays of structs represent database-like tables of structured records.', d: 'Easy' },
    { q: 'Which header file is required for file input and output stream operations in C++?', c: '#include <fstream>', w1: '#include <file.h>', w2: '#include <iostream>', w3: '#include <stdio>', exp: '<fstream> defines ifstream (input file stream), ofstream (output file stream), and fstream.', d: 'Easy' },
    { q: 'Which stream data type from <fstream> is used specifically for READING data from a file on disk?', c: 'ifstream', w1: 'ofstream', w2: 'iostream', w3: 'filein', exp: 'ifstream stands for input file stream, used to open and read files.', d: 'Easy' },
    { q: 'Which stream data type from <fstream> is used specifically for WRITING data to a file on disk?', c: 'ofstream', w1: 'ifstream', w2: 'ostream', w3: 'fileout', exp: 'ofstream stands for output file stream, creating or overwriting disk files.', d: 'Easy' },
    { q: 'What is the file opening mode used to append new data to the end of an existing file without erasing its contents?', c: 'ios::app', w1: 'ios::in', w2: 'ios::out', w3: 'ios::trunc', exp: 'ios::app (append mode) positions write operations at the end of the file.', d: 'Easy' },
    { q: 'How do you check whether a file stream fin successfully opened the target file?', c: 'if (fin.is_open()) or if (fin)', w1: 'if (fin.exists())', w2: 'if (fin == 1)', w3: 'if (fin.ready())', exp: 'is_open() returns true if the stream is successfully associated with an open file.', d: 'Easy' },
    { q: 'What loop condition is commonly used to read integers from a file stream fin until End-Of-File (EOF)?', c: 'while (fin >> num)', w1: 'while (!EOF)', w2: 'for (int i=0; fin; i++)', w3: 'while (fin.read())', exp: 'fin >> num evaluates to false when extraction fails due to EOF or invalid data format.', d: 'Medium' },
    { q: 'Why is it good practice to call fout.close(); after finishing file writing operations?', c: 'To flush remaining buffer data to disk and release the OS file handle lock', w1: 'To delete the file from disk', w2: 'To prevent the computer from crashing', w3: 'It is required by syntax or compiler errors occur', exp: 'close() flushes internal stream buffers and frees the operating system file descriptor.', d: 'Easy' },
    { q: 'What is the base case in a recursive function calculating the factorial of n (int fact(int n))?', c: 'if (n <= 1) return 1;', w1: 'if (n == 0) return 0;', w2: 'while (n > 0)', w3: 'return fact(n - 1);', exp: '0! = 1 and 1! = 1; the base case halts recursion to prevent infinite stack depth.', d: 'Easy' },
    { q: 'What happens if a recursive function does NOT have a valid base case or never reaches it?', c: 'Infinite recursion causing Stack Overflow and program crash', w1: 'It returns 0 automatically', w2: 'Compiler generates a warning and stops', w3: 'Execution becomes multithreaded', exp: 'Each call consumes stack frame memory; boundless recursion exhausts call stack space, triggering a segmentation fault.', d: 'Easy' }
  ];

  cppMid.forEach((it, idx) => qs.push(createQuestion(`CPP-MID-${String(idx + 1).padStart(3, '0')}`, 'subj-cpp', false, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'Bara C-- Mid.pdf', idx)));
  cppFinal.forEach((it, idx) => qs.push(createQuestion(`CPP-FIN-${String(idx + 1).padStart(3, '0')}`, 'subj-cpp', true, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'c-- Final.pdf', idx)));

  // =========================================================================
  // 2. OBJECT-ORIENTED PROGRAMMING (subj-oop) - ALL OOP QUESTIONS ARE HERE!
  // Mid: 32 Questions (Pillars, Classes, Objects, Access specifiers, Constructors, Destructors, Encapsulation, Copy, Operator Overloading)
  // Final: 52 Questions (Inheritance, Polymorphism, Virtual functions, Abstract classes, Templates, STL, Exceptions, Dynamic binding)
  // =========================================================================
  const oopMid = [
    { q: 'Which of the following is NOT one of the four primary pillars of Object-Oriented Programming?', c: 'Compilation', w1: 'Encapsulation', w2: 'Inheritance', w3: 'Polymorphism', exp: 'The four pillars are Encapsulation, Abstraction, Inheritance, and Polymorphism.', d: 'Easy' },
    { q: 'Encapsulation is best demonstrated by:', c: 'Making member variables private and providing public getter and setter methods', w1: 'Creating multiple derived classes', w2: 'Writing global functions', w3: 'Using templates for generic types', exp: 'Data hiding combined with accessor methods encapsulates internal object state.', d: 'Easy' },
    { q: 'An instance of a class is known as:', c: 'An object', w1: 'A method', w2: 'An interface', w3: 'A template', exp: 'A class is a blueprint; an object is an instantiated physical instance in memory.', d: 'Easy' },
    { q: 'A constructor that initializes all member variables with default values when no arguments are provided is a:', c: 'Default constructor', w1: 'Parameterized constructor', w2: 'Copy constructor', w3: 'Destructor', exp: 'Invoked automatically when an object is declared with no arguments.', d: 'Easy' },
    { q: 'What is constructor overloading?', c: 'Defining multiple constructors with different parameter lists in the same class', w1: 'Having constructors in both base and derived classes', w2: 'Calling a constructor inside a loop', w3: 'A constructor that calls a destructor', exp: 'Permits object initialization in multiple distinct ways based on provided arguments.', d: 'Easy' },
    { q: 'In C++, constructor delegation allows:', c: 'A constructor to call another constructor of the same class in its member initializer list', w1: 'A constructor to call a destructor', w2: 'A class to delegate construction to a global function', w3: 'A derived class constructor to be private', exp: 'Constructor delegation eliminates code duplication across multiple constructors.', d: 'Medium' },
    { q: 'The initialization list of a constructor is executed:', c: 'Before the constructor body executes', w1: 'After the constructor body finishes', w2: 'Only when an error occurs', w3: 'During object destruction', exp: 'The member initialization list initializes attributes directly upon allocation before body execution.', d: 'Medium' },
    { q: 'Which members MUST be initialized in the constructor initialization list rather than inside the body?', c: 'const members and reference members (&)', w1: 'int variables only', w2: 'Static members', w3: 'Private members', exp: 'References and const members must be initialized when constructed; they cannot be assigned later.', d: 'Hard' },
    { q: 'When is a copy constructor invoked in C++?', c: 'When an object is passed by value to a function, returned by value, or initialized from an existing object of the same class', w1: 'When assigning an object using the = operator after initialization', w2: 'When deleting an object', w3: 'Only during compilation', exp: 'Copy constructor initializes a new object from an existing instance.', d: 'Medium' },
    { q: 'What is the signature of a standard copy constructor for class Complex?', c: 'Complex(const Complex &other);', w1: 'Complex(Complex other);', w2: 'void Complex(Complex *other);', w3: 'Complex copy(Complex other);', exp: 'Must take its argument by reference (typically const); passing by value would cause infinite recursive calls.', d: 'Hard' },
    { q: 'A deep copy differs from a shallow copy because a deep copy:', c: 'Allocates new independent heap memory and copies the actual values rather than copying raw pointer addresses', w1: 'Only copies the first member', w2: 'Is automatically generated by default by the compiler', w3: 'Uses less memory', exp: 'Deep copying prevents shared pointer aliasing and double-free memory corruption.', d: 'Medium' },
    { q: 'The "is-a" relationship in object-oriented design is modeled using:', c: 'Inheritance', w1: 'Composition', w2: 'Aggregation', w3: 'Friendship', exp: 'Inheritance models taxonomic specialization: a Dog is-an Animal.', d: 'Easy' },
    { q: 'The "has-a" relationship in object-oriented design is modeled using:', c: 'Composition or Aggregation', w1: 'Inheritance', w2: 'Polymorphism', w3: 'Template specialization', exp: 'Composition/aggregation models parts-to-whole: a Car has-an Engine.', d: 'Easy' },
    { q: 'In composition (strong "has-a"):', c: 'The contained sub-object cannot exist independently of the containing object (shared lifetime)', w1: 'The contained object exists independently', w2: 'The relationship is defined using the \'is\' keyword', w3: 'The base class must be abstract', exp: 'Destroying a Car destroys its composed Engine sub-object.', d: 'Medium' },
    { q: 'In aggregation (weak "has-a"):', c: 'The contained object can exist independently of the containing object (e.g., Department has Teachers)', w1: 'The lifetime of both objects is strictly identical', w2: 'Inheritance is required', w3: 'Private inheritance is enforced', exp: 'Teachers continue to exist even if their Department is disbanded.', d: 'Medium' },
    { q: 'The keyword \'explicit\' on a single-parameter constructor prevents:', c: 'Implicit type conversions and copy-initialization', w1: 'The constructor from being called', w2: 'Memory allocation', w3: 'Inheritance of the constructor', exp: 'explicit Complex(double r) prevents accidental implicit conversions like Complex c = 5.0.', d: 'Hard' },
    { q: 'Operator overloading enables user-defined classes to:', c: 'Define custom behavior for standard operators (+, -, *, ==, <<, etc.) when applied to class objects', w1: 'Change the precedence and associativity of C++ operators', w2: 'Invent new operator symbols like @ or $', w3: 'Bypass encapsulation completely', exp: 'Operator overloading provides intuitive syntax for user-defined classes.', d: 'Easy' },
    { q: 'Which operator should return *this by reference to allow chaining (e.g. a = b = c;)?', c: 'The copy assignment operator (operator=)', w1: 'The addition operator (operator+)', w2: 'The equality operator (operator==)', w3: 'The destructor', exp: 'MyClass& operator=(const MyClass &rhs) { return *this; } permits assignment chaining.', d: 'Medium' },
    { q: 'Why is self-assignment check (if (this == &rhs) return *this;) essential in operator=?', c: 'To prevent deleting your own heap resources before copying when an object is assigned to itself (x = x)', w1: 'To make assignment run faster', w2: 'To prevent infinite recursion', w3: 'It is optional and never needed', exp: 'Deleting current dynamically allocated memory in self-assignment destroys the source data.', d: 'Hard' },
    { q: 'A static member function in C++:', c: 'Can be invoked using ClassName::functionName() without creating an instance, and cannot access non-static members', w1: 'Has access to non-static member variables', w2: 'Has a this pointer', w3: 'Cannot be public', exp: 'Static methods belong to the class type itself and lack an implicit this pointer.', d: 'Easy' },
    { q: 'A const member function (e.g., int getX() const;):', c: 'Promises not to modify any member variables of the calling object (*this)', w1: 'Can only be called on const objects', w2: 'Cannot return any value', w3: 'Must be static', exp: 'const member functions guarantee read-only inspection of object state.', d: 'Medium' },
    { q: 'Which keyword allows a specific member variable to be modified even inside a const member function?', c: 'mutable', w1: 'volatile', w2: 'dynamic', w3: 'register', exp: 'mutable member variables (e.g. debug counters, cache) can be altered in const methods.', d: 'Hard' },
    { q: 'What is the purpose of getter and setter methods?', c: 'To control and validate access to private data members, maintaining data encapsulation', w1: 'To speed up execution', w2: 'To replace constructors', w3: 'To make all variables public', exp: 'Accessors and mutators enforce validation logic and protect internal invariants.', d: 'Easy' },
    { q: 'What is a friend function in C++?', c: 'A non-member function granted access to the private and protected members of a class via the friend keyword', w1: 'A member function that is public', w2: 'A function that cannot be overloaded', w3: 'A derived class method', exp: 'friend functions have privileged access to private members while remaining external to class scope.', d: 'Medium' },
    { q: 'Can a constructor be declared as virtual in C++?', c: 'No, constructors CANNOT be virtual', w1: 'Yes, always', w2: 'Only in abstract classes', w3: 'Only default constructors', exp: 'An object exact type must be known at compile time to construct it; vtable is set up during construction.', d: 'Medium' },
    { q: 'Can a destructor be declared as virtual in C++?', c: 'Yes, and base classes designed for polymorphic deletion must always have a virtual destructor', w1: 'No, destructors cannot be virtual', w2: 'Only private destructors', w3: 'Only in structs', exp: 'A virtual destructor ensures that deleting a derived object via a base pointer calls the derived destructor.', d: 'Easy' },
    { q: 'In C++, protected members of a base class are accessible by:', c: 'Member functions of the base class and member functions of derived (sub) classes', w1: 'The public world directly', w2: 'Only the base class itself', w3: 'Unrelated classes', exp: 'protected grants visibility down the inheritance hierarchy while shielding from outside callers.', d: 'Easy' },
    { q: 'What is the return type of the overloaded comparison operator operator==(const MyClass &other) const?', c: 'bool', w1: 'int', w2: 'void', w3: 'MyClass', exp: 'Comparison operators return boolean true or false.', d: 'Easy' },
    { q: 'When an object is passed BY VALUE to a function:', c: 'The copy constructor is called to create a local copy inside the function stack frame', w1: 'The address of the original object is passed', w2: 'The destructor is called immediately', w3: 'The object cannot be read', exp: 'Pass-by-value invokes the copy constructor.', d: 'Easy' },
    { q: 'When an object is passed BY CONST REFERENCE (const MyClass &obj):', c: 'No copy is made (zero overhead) and the function cannot modify the caller object (safe)', w1: 'A deep copy is made', w2: 'The object is destroyed upon return', w3: 'Only public members can be read', exp: 'Best practice in C++: combines reference efficiency with immutability guarantees.', d: 'Medium' },
    { q: 'What is an anonymous (temporary) object in C++?', c: 'An unnamed temporary object created on the fly (e.g. return Complex(1.0, 2.0);)', w1: 'An object with no class', w2: 'A null pointer', w3: 'A leaked memory block', exp: 'Temporary rvalue objects are destroyed at the end of the full expression in which they are created.', d: 'Medium' },
    { q: 'The scope of an automatic stack object declared inside a block { ... } ends when:', c: 'Execution reaches the closing brace }, at which point its destructor is called automatically', w1: 'The program terminates', w2: 'delete is called manually', w3: 'After 10 seconds', exp: 'RAII (Resource Acquisition Is Initialization) relies on automatic destructor invocation at block exit.', d: 'Easy' }
  ];

  const oopFinal = [
    { q: 'Runtime Polymorphism in C++ is primarily achieved through:', c: 'Inheritance and virtual functions (dynamic binding)', w1: 'Friend functions', w2: 'Global variables', w3: 'Preprocessor macros', exp: 'Virtual functions enable runtime dynamic dispatch based on actual object type.', d: 'Easy' },
    { q: 'A class containing at least one pure virtual function (e.g. virtual void draw() = 0;) is:', c: 'An abstract class, which cannot be instantiated directly', w1: 'A concrete class', w2: 'An empty class', w3: 'A sealed class', exp: 'Abstract classes define generic interfaces that must be implemented by concrete derived classes.', d: 'Easy' },
    { q: 'If a derived class does NOT override an inherited pure virtual function from an abstract base class:', c: 'The derived class also remains an abstract class and cannot be instantiated', w1: 'The code compiles and runs using the base implementation', w2: 'The pure virtual function is ignored', w3: 'A runtime exception is thrown on startup', exp: 'A derived class must implement all inherited pure virtual methods to become concrete.', d: 'Medium' },
    { q: 'What is the Virtual Method Table (vtable)?', c: 'A lookup table of function pointers maintained by the compiler to resolve virtual function calls at runtime', w1: 'A table of object variables in RAM', w2: 'A database table', w3: 'A debug log file', exp: 'vtable enables dynamic binding by storing addresses of virtual member functions.', d: 'Medium' },
    { q: 'Every object of a polymorphic class containing virtual functions contains a hidden pointer called:', c: 'vptr (virtual pointer), which points to the class vtable', w1: 'this pointer', w2: 'base pointer', w3: 'heap pointer', exp: 'The vptr is injected into object memory layout by the compiler to find the appropriate vtable.', d: 'Medium' },
    { q: 'What is an interface in object-oriented C++ design?', c: 'An abstract class containing ONLY pure virtual functions and no non-static data members', w1: 'A graphical user interface (GUI)', w2: 'A class with only private members', w3: 'A template function', exp: 'Pure abstract classes specify behavioral contracts without implementation details.', d: 'Easy' },
    { q: 'What does the dynamic_cast operator do in polymorphic C++ hierarchies?', c: 'Safely converts a base class pointer to a derived class pointer at runtime, returning nullptr if invalid', w1: 'Converts integers to floats', w2: 'Forces a cast without any runtime check', w3: 'Allocates dynamic memory', exp: 'dynamic_cast uses Run-Time Type Information (RTTI) to safely downcast pointers.', d: 'Hard' },
    { q: 'What does the typeid operator return when applied to an expression in C++?', c: 'A reference to a std::type_info object representing the runtime type of the object', w1: 'The size of the object in bytes', w2: 'The memory address', w3: 'A string copy', exp: 'typeid requires #include <typeinfo> and polymorphic classes for runtime type identification.', d: 'Medium' },
    { q: 'What are function templates in C++?', c: 'Generic blueprints that allow writing a single function that works with any data type', w1: 'Macros that replace text', w2: 'Virtual functions in base classes', w3: 'Inline assembly functions', exp: 'template <typename T> T max(T a, T b) generates type-specific functions at compile time.', d: 'Easy' },
    { q: 'What are class templates in C++?', c: 'Generic class definitions parameterized by types (e.g. template <typename T> class Stack { ... };)', w1: 'Classes that cannot have members', w2: 'Inherited classes only', w3: 'Abstract classes with no methods', exp: 'Class templates form the foundation of generic data structures like std::vector.', d: 'Easy' },
    { q: 'The C++ Standard Template Library (STL) consists of which three major architectural components?', c: 'Containers, Iterators, and Algorithms', w1: 'Classes, Objects, and Functions', w2: 'Pointers, References, and Arrays', w3: 'Compilers, Linkers, and Debuggers', exp: 'The classic STL design separates storage (containers), traversal (iterators), and processing (algorithms).', d: 'Easy' },
    { q: 'Which STL container represents a dynamically resizable array with contiguous memory storage?', c: 'std::vector', w1: 'std::list', w2: 'std::set', w3: 'std::map', exp: 'std::vector provides O(1) indexed random access and contiguous element layout.', d: 'Easy' },
    { q: 'What is the time complexity of accessing an element by index (vec[i]) in a std::vector?', c: 'O(1) constant time', w1: 'O(n)', w2: 'O(log n)', w3: 'O(n^2)', exp: 'Contiguous memory allows instantaneous pointer arithmetic address calculation.', d: 'Easy' },
    { q: 'What is the time complexity of inserting an element at the back of a std::vector (push_back)?', c: 'Amortized O(1)', w1: 'O(n) always', w2: 'O(log n)', w3: 'O(n^2)', exp: 'Geometric capacity doubling ensures amortized constant time per insertion.', d: 'Medium' },
    { q: 'Which STL container implements a doubly-linked list with non-contiguous memory nodes?', c: 'std::list', w1: 'std::vector', w2: 'std::deque', w3: 'std::array', exp: 'std::list is a doubly linked list providing O(1) insertions anywhere given an iterator.', d: 'Easy' },
    { q: 'Which STL container stores unique elements sorted automatically in logarithmic time?', c: 'std::set (implemented as a self-balancing Red-Black Tree)', w1: 'std::vector', w2: 'std::list', w3: 'std::stack', exp: 'std::set guarantees O(log n) search, insertion, and deletion.', d: 'Medium' },
    { q: 'Which STL container stores key-value pairs sorted by key?', c: 'std::map', w1: 'std::set', w2: 'std::vector', w3: 'std::pair', exp: 'std::map is an associative sorted container mapping unique keys to values.', d: 'Easy' },
    { q: 'Which STL container adapter provides Last-In First-Out (LIFO) access?', c: 'std::stack', w1: 'std::queue', w2: 'std::priority_queue', w3: 'std::deque', exp: 'std::stack adapts an underlying container with push(), pop(), and top() LIFO semantics.', d: 'Easy' },
    { q: 'Which STL container adapter provides First-In First-Out (FIFO) access?', c: 'std::queue', w1: 'std::stack', w2: 'std::vector', w3: 'std::set', exp: 'std::queue provides push() at rear and pop() from front.', d: 'Easy' },
    { q: 'What is an iterator in C++ STL?', c: 'An object that acts as a generalized pointer used to traverse elements of an STL container', w1: 'An integer index', w2: 'A loop counter variable', w3: 'A function return type', exp: 'Iterators abstract container traversal across vectors, lists, sets, and maps.', d: 'Easy' },
    { q: 'What is the purpose of exception handling in C++ (try, catch, throw)?', c: 'To separate error detection from error handling and transfer control gracefully when runtime anomalies occur', w1: 'To make programs compile faster', w2: 'To replace if statements', w3: 'To allocate dynamic memory', exp: 'Structured exception handling decouples error generation from corrective recovery logic.', d: 'Easy' },
    { q: 'What happens if a thrown exception is NOT caught by any matching catch block in the program?', c: 'std::terminate() is called, aborting program execution', w1: 'The program ignores the error and continues', w2: 'The exception converts to integer 0', w3: 'The function returns null', exp: 'Unhandled exceptions invoke std::terminate, which calls abort() by default.', d: 'Medium' },
    { q: 'In C++ inheritance, what is the "Diamond Problem" in multiple inheritance?', c: 'Ambiguity that occurs when a derived class inherits from two classes that both inherit from the same common base class', w1: 'A syntax error in single inheritance', w2: 'A pointer memory leak', w3: 'A recursive constructor call', exp: 'The derived class receives two duplicate copies of the common grand-base class subobject.', d: 'Medium' },
    { q: 'How is the Diamond Problem resolved in C++ multiple inheritance?', c: 'Using Virtual Inheritance (e.g. class B : virtual public A)', w1: 'Using private inheritance', w2: 'By renaming the classes', w3: 'By making all functions pure virtual', exp: 'Virtual base classes ensure only a single shared instance of the base subobject is inherited.', d: 'Hard' },
    { q: 'What is method overriding in C++?', c: 'A derived class providing a specific implementation of a virtual function already defined in its base class', w1: 'Defining multiple functions with different parameter types in the same class', w2: 'Calling a base class method with different arguments', w3: 'Hiding a variable', exp: 'Overriding redefines base class polymorphic behavior in a derived class.', d: 'Easy' },
    { q: 'What is the purpose of the \'override\' specifier (introduced in C++11)?', c: 'Tells the compiler to verify that the method actually overrides a virtual method in the base class, catching typo bugs', w1: 'Makes the method private', w2: 'Forces the function to be inline', w3: 'Prevents further inheritance', exp: 'override catches subtle signature mismatches at compile time.', d: 'Medium' },
    { q: 'What is the purpose of the \'final\' specifier on a class or virtual function?', c: 'Prevents a class from being inherited, or prevents a virtual function from being further overridden in derived classes', w1: 'Marks a function for immediate execution', w2: 'Destroys an object', w3: 'Releases heap memory', exp: 'final prohibits downstream inheritance or polymorphic overriding.', d: 'Medium' },
    { q: 'In derived class construction, what is the order of constructor execution?', c: 'Base class constructor executes FIRST, followed by Derived class constructor', w1: 'Derived class constructor executes first', w2: 'Both execute concurrently', w3: 'Only the derived constructor executes', exp: 'Base subobjects must be fully initialized before derived class members are constructed.', d: 'Easy' },
    { q: 'In derived class destruction, what is the order of destructor execution?', c: 'Derived class destructor executes FIRST, followed by Base class destructor (reverse order of construction)', w1: 'Base class destructor executes first', w2: 'Only the base destructor executes', w3: 'Destruction order is undefined', exp: 'Derived components are cleaned up before base class foundation subobjects are torn down.', d: 'Easy' },
    { q: 'When a base class constructor requires arguments, how does the derived class pass them?', c: 'In the derived class constructor member initializer list (e.g. Derived(int x) : Base(x) { ... })', w1: 'Inside the derived constructor body', w2: 'Via global variables', w3: 'Through the destructor', exp: 'Base class constructors are called explicitly in the derived initializer list.', d: 'Medium' },
    { q: 'What is slicing (object slicing) in C++?', c: 'When a derived class object is assigned by value to a base class object, stripping away the derived attributes and methods', w1: 'Dividing an array into two halves', w2: 'Splitting strings with delimiters', w3: 'A syntax error in switch statements', exp: 'Assigning by value copies only the base slice of the derived object, destroying polymorphism.', d: 'Hard' },
    { q: 'How is object slicing prevented when passing polymorphic objects to functions?', c: 'By passing objects by reference (Base &) or by pointer (Base *) rather than by value', w1: 'By using private inheritance', w2: 'By casting to void*', w3: 'By using static functions', exp: 'References and pointers preserve the full dynamic derived instance and its vtable.', d: 'Medium' },
    { q: 'What does the friend keyword achieve when applied to an entire class (e.g. friend class B; inside class A)?', c: 'All member functions of class B can access private and protected members of class A', w1: 'Class A can access private members of class B', w2: 'Both classes share the same vtable', w3: 'Class B automatically inherits class A', exp: 'Friendship is not mutual unless explicitly declared in both classes, and is not inherited.', d: 'Medium' },
    { q: 'What is RAII (Resource Acquisition Is Initialization) in C++?', c: 'A programming idiom where resource lifecycle is bound to object lifetime; acquired in constructor, released in destructor', w1: 'A method for accelerating compilation', w2: 'A technique for writing recursive algorithms', w3: 'A library for network sockets', exp: 'RAII guarantees leak-free resource management (memory, file handles, mutexes) even during exceptions.', d: 'Hard' },
    { q: 'What is a smart pointer in modern C++ (e.g. std::unique_ptr)?', c: 'A wrapper class managing a dynamic heap pointer that automatically deallocates memory when it goes out of scope', w1: 'A pointer with artificial intelligence', w2: 'A raw void* pointer', w3: 'A pointer that never uses memory', exp: 'unique_ptr enforces exclusive ownership and automatic deletion without manual delete.', d: 'Medium' },
    { q: 'What is std::shared_ptr in modern C++?', c: 'A smart pointer that implements reference counting, deallocating the managed object when the last shared_ptr is destroyed', w1: 'A pointer shared between different computers', w2: 'A raw pointer with no destructor', w3: 'A pointer to global variables only', exp: 'Reference-counted shared ownership smart pointer.', d: 'Medium' },
    { q: 'What is the purpose of std::weak_ptr?', c: 'Observes an object managed by std::shared_ptr without increasing its reference count, breaking cyclic references', w1: 'A pointer that can only hold small numbers', w2: 'An uninitialized pointer', w3: 'A pointer to private members', exp: 'weak_ptr prevents circular dependency memory leaks in shared_ptr graphs.', d: 'Hard' },
    { q: 'What is the Rule of Three in classic C++ (prior to C++11)?', c: 'If a class needs a custom Destructor, Copy Constructor, or Copy Assignment Operator, it almost certainly needs all three', w1: 'A class should have at most three attributes', w2: 'A program must have three classes', w3: 'Functions cannot have more than three parameters', exp: 'Classes managing raw dynamic memory require all three to prevent double-free and memory leaks.', d: 'Hard' },
    { q: 'What is the Rule of Five in modern C++11?', c: 'Destructor, Copy Constructor, Copy Assignment, Move Constructor, and Move Assignment Operator', w1: 'Five inheritance levels', w2: 'Five design patterns', w3: 'Five access specifiers', exp: 'Adds move semantics (rvalue references &&) to the Rule of Three for efficient resource transfers.', d: 'Hard' },
    { q: 'What is a move constructor (e.g. MyClass(MyClass &&other) noexcept)?', c: 'Transfers ownership of resources from a temporary rvalue object without copying, setting source pointers to nullptr', w1: 'Moves an object across CPU cores', w2: 'A constructor that shifts bitwise', w3: 'A destructor that saves data', exp: 'Move semantics avoid expensive deep copies of temporary objects.', d: 'Hard' },
    { q: 'What is an abstract factory design pattern?', c: 'A creational pattern providing an interface for creating families of related objects without specifying their concrete classes', w1: 'A factory building cars', w2: 'A loop generating arrays', w3: 'An abstract class with no methods', exp: 'Gang of Four creational design pattern.', d: 'Medium' },
    { q: 'What is the Singleton design pattern?', c: 'A pattern ensuring a class has only ONE instance throughout program execution and providing a global access point to it', w1: 'A class with only one method', w2: 'A single-threaded program', w3: 'A function that takes one parameter', exp: 'Classic pattern: private constructor + static instance getter.', d: 'Easy' },
    { q: 'What is an upcast in C++ inheritance (e.g. Base *b = new Derived();)?', c: 'Converting a derived class pointer/reference to a base class pointer/reference (always safe and implicit)', w1: 'Converting base pointer to derived pointer', w2: 'Converting float to int', w3: 'An unsafe downcast', exp: 'Upcasting moves up the inheritance tree and is always safe because a Derived is-a Base.', d: 'Easy' },
    { q: 'What is a downcast in C++ inheritance?', c: 'Converting a base class pointer/reference down to a derived class pointer/reference (requires explicit or dynamic_cast)', w1: 'Converting derived to base', w2: 'Deleting an object', w3: 'Lowering volume', exp: 'Downcasting is potentially unsafe because the base pointer might not actually point to the requested derived type.', d: 'Medium' },
    { q: 'Why should base classes intended for polymorphic deletion declare their destructors as virtual?', c: 'To ensure that deleting an object via a base class pointer correctly calls the derived class destructor first', w1: 'To make destruction run faster', w2: 'Because non-virtual destructors cannot delete memory', w3: 'It is a compilation error otherwise', exp: 'Deleting a derived instance through a non-virtual base pointer yields undefined behavior and resource leaks.', d: 'Medium' },
    { q: 'What is operator overloading for stream insertion operator << (e.g. ostream& operator<<(ostream &out, const MyClass &obj))?', c: 'Allows printing class objects directly with cout << obj;, typically implemented as a friend or non-member function', w1: 'A member function inside ostream only', w2: 'A method to shift bits in integers', w3: 'A private constructor', exp: 'Binary operator where left operand is ostream&, so it cannot be a member function of MyClass.', d: 'Medium' },
    { q: 'What is operator overloading for stream extraction operator >> (e.g. istream& operator>>(istream &in, MyClass &obj))?', c: 'Allows reading input directly into class objects with cin >> obj;, implemented as a non-member function', w1: 'A member method of MyClass taking no parameters', w2: 'A bit shift right', w3: 'A destructor', exp: 'Left operand is istream&, enabling chained stream inputs (cin >> a >> b).', d: 'Medium' },
    { q: 'What does the keyword noexcept signify on a C++ function?', c: 'Specifies that the function promises not to throw any exceptions, allowing compiler optimizations', w1: 'Forces the function to throw exceptions', w2: 'Catches all exceptions', w3: 'Exits the program immediately', exp: 'Used especially on move constructors to allow std::vector to safely move elements during reallocation.', d: 'Hard' },
    { q: 'In C++ templates, what is template specialization?', c: 'Defining a customized implementation of a generic template for a specific, designated data type', w1: 'A template with only one argument', w2: 'A function that cannot be templated', w3: 'A class with no template', exp: 'template <> class MyClass<bool> provides specialized bit-packing for boolean types.', d: 'Hard' },
    { q: 'What is the difference between a function template and a template function?', c: 'Function template is the generic blueprint; template function is the concrete instantiated function generated by the compiler', w1: 'They are completely unrelated', w2: 'One is written in C and one in C++', w3: 'Function template has no return type', exp: 'Instantiation produces concrete template functions from the generic template blueprint.', d: 'Medium' },
    { q: 'What is early binding (static binding) versus late binding (dynamic binding)?', c: 'Early binding resolves function calls at compile time; late binding resolves virtual function calls at runtime via vtable', w1: 'Early binding is slower than late binding', w2: 'Late binding is used for non-virtual functions', w3: 'Early binding requires inheritance', exp: 'Non-virtual calls use compile-time early binding; virtual calls use runtime late binding.', d: 'Medium' },
    { q: 'What does the keyword auto do when declaring a variable in modern C++ (e.g. auto it = vec.begin();)?', c: 'Instructs the compiler to deduce the variable type automatically from its initializer expression at compile time', w1: 'Allocates the variable automatically on heap', w2: 'Creates an object of any type at runtime', w3: 'Makes the variable static', exp: 'Compile-time type deduction simplifies verbose type declarations like iterators.', d: 'Easy' }
  ];

  oopMid.forEach((it, idx) => qs.push(createQuestion(`OOP-MID-${String(idx + 1).padStart(3, '0')}`, 'subj-oop', false, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'questions object oriented.pdf', idx)));
  oopFinal.forEach((it, idx) => qs.push(createQuestion(`OOP-FIN-${String(idx + 1).padStart(3, '0')}`, 'subj-oop', true, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'questions object oriented.pdf', idx)));

  return qs;
}

module.exports = { getCppAndOopQuestions };
