const { createQuestion } = require('./bank_factory');

function getCppAndOopQuestions() {
  const qs = [];

  // ==========================================
  // C++ PROGRAMMING (subj-cpp)
  // Mid: 32 (Variables, Data types, Operators, Control flow, Loops, Functions, Arrays, Pointers, References, Strings, Basic Structs)
  // Final: 52 (Comprehensive + OOP IN C++: Classes, Objects, Access specifiers, Constructors/Destructors, this pointer, Operator Overloading, Inheritance, Dynamic memory new/delete, Pointers to objects)
  // ==========================================
  const cppMid = [
    { q: 'Which header file is required in C++ for standard input and output streams like cin and cout?', c: '#include <iostream>', w1: '#include <stdio.h>', w2: '#include <conio.h>', w3: '#include <stream.h>', exp: '<iostream> defines the standard input/output stream objects.', d: 'Easy' },
    { q: 'What is the correct syntax to output "Hello World" in C++?', c: 'cout << "Hello World";', w1: 'System.out.print("Hello World");', w2: 'print("Hello World");', w3: 'Console.WriteLine("Hello World");', exp: 'C++ uses the insertion operator (<<) with cout.', d: 'Easy' },
    { q: 'Which C++ operator is used to calculate the remainder of integer division?', c: '% (modulo operator)', w1: '/', w2: '//', w3: 'mod', exp: '% yields the integer remainder.', d: 'Easy' },
    { q: 'What is the value of x after: int a = 5; int x = ++a; ?', c: 'x = 6, a = 6', w1: 'x = 5, a = 6', w2: 'x = 6, a = 5', w3: 'x = 5, a = 5', exp: 'Pre-increment (++a) increments a first, then assigns the new value to x.', d: 'Easy' },
    { q: 'What is the value of y after: int a = 5; int y = a++; ?', c: 'y = 5, a = 6', w1: 'y = 6, a = 6', w2: 'y = 6, a = 5', w3: 'y = 5, a = 5', exp: 'Post-increment (a++) assigns the current value of a to y first, then increments a.', d: 'Easy' },
    { q: 'What is the size of the fundamental data type \'char\' in C++ according to the standard?', c: '1 byte (at least 8 bits)', w1: '2 bytes', w2: '4 bytes', w3: '8 bytes', exp: 'sizeof(char) is defined to be exactly 1.', d: 'Easy' },
    { q: 'Which data type is used to store boolean true or false in C++?', c: 'bool', w1: 'boolean', w2: 'bit', w3: 'int only', exp: 'The native keyword in C++ is bool.', d: 'Easy' },
    { q: 'What is the output of: cout << (10 / 4); in C++?', c: '2', w1: '2.5', w2: '2.0', w3: '3', exp: 'Integer division between 10 and 4 truncates the decimal part, yielding 2.', d: 'Easy' },
    { q: 'How to get floating-point division 2.5 from integers 10 and 4 in C++?', c: '(float)10 / 4 or 10.0 / 4', w1: '10 / 4', w2: 'float(10 / 4)', w3: 'int(10.0 / 4)', exp: 'Casting at least one operand to float/double performs floating-point division.', d: 'Easy' },
    { q: 'In a switch statement in C++, what happens if a matching case does NOT have a \'break\' statement?', c: 'Execution falls through to the subsequent cases until a break or end of switch is reached', w1: 'The program terminates with a runtime error', w2: 'The switch immediately exits', w3: 'The default case executes immediately', exp: 'Fall-through behavior in C/C++ switch statements.', d: 'Easy' },
    { q: 'What is the output of the loop: for (int i = 0; i < 5; i += 2) cout << i << " "; ?', c: '0 2 4 ', w1: '0 1 2 3 4 ', w2: '0 2 4 6 ', w3: '2 4 ', exp: 'Loop runs for i = 0, 2, 4. When i = 6, the condition i < 5 is false.', d: 'Easy' },
    { q: 'How many times will a do-while loop execute its body at minimum?', c: 'At least 1 time', w1: '0 times', w2: 'Infinitely', w3: '2 times', exp: 'do-while is a post-test loop; condition is checked after the first execution.', d: 'Easy' },
    { q: 'Which statement immediately exits a loop in C++?', c: 'break;', w1: 'continue;', w2: 'exit;', w3: 'return 0;', exp: 'break exits the innermost enclosing loop or switch.', d: 'Easy' },
    { q: 'Which statement skips the rest of the current iteration and jumps to the next iteration of the loop?', c: 'continue;', w1: 'break;', w2: 'goto;', w3: 'skip;', exp: 'continue begins the next iteration of the enclosing loop.', d: 'Easy' },
    { q: 'How do you declare a static array of 10 integers in C++?', c: 'int arr[10];', w1: 'int arr(10);', w2: 'array<int> arr = new array(10);', w3: 'int arr[] = 10;', exp: 'Standard C-style array declaration in C++.', d: 'Easy' },
    { q: 'What is the index of the first element in a C++ array?', c: '0', w1: '1', w2: '-1', w3: 'Any integer', exp: 'C++ uses 0-based indexing.', d: 'Easy' },
    { q: 'What happens if you access arr[15] in an array declared as int arr[10] in C++?', c: 'Undefined behavior (out-of-bounds memory access, potential crash or corrupted data)', w1: 'Array automatically resizes to 16', w2: 'Compiler generates a guaranteed syntax error', w3: 'It returns 0', exp: 'C++ does not perform bounds checking on raw arrays.', d: 'Medium' },
    { q: 'What is a pointer in C++?', c: 'A variable that stores the memory address of another variable', w1: 'A variable that stores floating-point numbers', w2: 'A special function', w3: 'A reference counter', exp: 'Definition of pointer in C++.', d: 'Easy' },
    { q: 'Which operator is used to obtain the memory address of a variable x?', c: '&x (address-of operator)', w1: '*x', w2: '->x', w3: '@x', exp: '& operator returns the memory address.', d: 'Easy' },
    { q: 'Which operator is used to access or modify the value stored at the address pointed to by a pointer ptr?', c: '*ptr (dereference operator)', w1: '&ptr', w2: 'ptr->val', w3: '#ptr', exp: '* dereferences a pointer.', d: 'Easy' },
    { q: 'What is the output of: int a = 10; int *p = &a; *p = 20; cout << a; ?', c: '20', w1: '10', w2: 'Address of a', w3: 'Garbage value', exp: '*p = 20 modifies the value at address &a, so a becomes 20.', d: 'Easy' },
    { q: 'What is a reference in C++ (e.g., int &ref = a;)?', c: 'An alias (alternative name) for an existing variable', w1: 'A separate pointer variable that can be null', w2: 'A copy of the variable', w3: 'A constant integer', exp: 'References cannot be null and cannot be reseated to another variable.', d: 'Medium' },
    { q: 'When passing an argument by reference (void func(int &x)), changes to x inside the function:', c: 'Modify the original argument passed from the caller', w1: 'Only affect a local copy', w2: 'Cause a compilation error', w3: 'Require dynamic memory allocation', exp: 'Pass-by-reference shares the same memory location as caller.', d: 'Easy' },
    { q: 'What is the return type of a function that does not return any value?', c: 'void', w1: 'int', w2: 'null', w3: 'empty', exp: 'void specifies the absence of a return value.', d: 'Easy' },
    { q: 'Function overloading in C++ allows multiple functions with:', c: 'The same name but different parameter lists (types, number of parameters)', w1: 'The same name and identical parameter lists but different return types only', w2: 'Different names in the same class', w3: 'Only void return types', exp: 'Overloading is resolved by signature (parameter types/counts), not return type alone.', d: 'Medium' },
    { q: 'What is recursion in C++?', c: 'A function calling itself directly or indirectly to solve a smaller subproblem', w1: 'A loop that never terminates', w2: 'A pointer pointing to itself', w3: 'An array of functions', exp: 'Definition of recursion.', d: 'Easy' },
    { q: 'Every recursive function must have a:', c: 'Base case to terminate recursion and prevent stack overflow', w1: 'Global variable', w2: 'Pointer parameter', w3: 'While loop', exp: 'Base case halts repeated calls.', d: 'Easy' },
    { q: 'What is the default value of uninitialized local variables inside a function in C++?', c: 'Garbage (indeterminate) value from whatever was in that memory location', w1: '0', w2: 'NULL', w3: '1', exp: 'Local automatic variables are not zero-initialized by default in C++.', d: 'Easy' },
    { q: 'What is the value of strcmp("apple", "banana") in C-string library <cstring>?', c: 'A negative integer (since "apple" < "banana" alphabetically)', w1: '0', w2: 'A positive integer', w3: 'true', exp: 'strcmp returns negative if first string precedes second alphabetically.', d: 'Medium' },
    { q: 'How is a C-style string terminated in memory?', c: 'With a null terminator character \'\\0\'', w1: 'With a newline \'\\n\'', w2: 'With a space \' \'', w3: 'With EOF', exp: 'Null byte 0 marks the end of C strings.', d: 'Easy' },
    { q: 'What does the \'const\' keyword signify when applied to a variable (e.g., const int MAX = 100;)?', c: 'The variable is read-only and its value cannot be modified after initialization', w1: 'The variable is global', w2: 'The variable is stored in heap', w3: 'The variable can only be positive', exp: 'const enforces compile-time immutability.', d: 'Easy' },
    { q: 'In C++, what is a struct by default compared to a class?', c: 'A struct has default public access for members, while a class has default private access', w1: 'A struct cannot have methods', w2: 'A struct cannot have constructors', w3: 'A struct is stored on the heap', exp: 'The only difference in C++ between struct and class is default member visibility.', d: 'Medium' }
  ];

  const cppFinal = [
    { q: 'What is a class in C++?', c: 'A user-defined data type that bundles data (attributes) and functions (methods) together', w1: 'A built-in data type like int', w2: 'A collection of global functions only', w3: 'A pointer to memory', exp: 'Core blueprint construct in C++.', d: 'Easy' },
    { q: 'What is the default access specifier for members of a C++ class if not specified?', c: 'private', w1: 'public', w2: 'protected', w3: 'friend', exp: 'Class members are private by default; struct members are public by default.', d: 'Easy' },
    { q: 'Members declared as \'private\' in a class are accessible:', c: 'Only within the member functions and friends of that class', w1: 'Everywhere in the program', w2: 'In derived classes only', w3: 'Inside main() directly', exp: 'Encapsulation restricts private access to class scope.', d: 'Easy' },
    { q: 'Members declared as \'protected\' in a class are accessible:', c: 'Within the class itself and within derived (inherited) classes', w1: 'Outside the class by anyone', w2: 'Only inside main()', w3: 'Only by friend functions', exp: 'protected allows inheritance access while hiding from public.', d: 'Easy' },
    { q: 'What is a constructor in C++?', c: 'A special member function with the same name as the class that is called automatically upon object creation', w1: 'A function that destroys an object', w2: 'A function that returns void', w3: 'A function called by delete', exp: 'Constructors initialize object state.', d: 'Easy' },
    { q: 'Which of the following is true about constructors in C++?', c: 'They have no return type, not even void', w1: 'They must return an int', w2: 'They must be private', w3: 'A class can have only one constructor', exp: 'Constructors never declare a return type.', d: 'Easy' },
    { q: 'What is a default constructor in C++?', c: 'A constructor that can be called with no arguments', w1: 'A constructor generated only when you write one', w2: 'A constructor that takes all integer arguments', w3: 'A constructor that deletes the object', exp: 'Takes zero parameters or has all parameters with default arguments.', d: 'Easy' },
    { q: 'What is a destructor in C++?', c: 'A member function named with a tilde (~ClassName) called automatically when an object goes out of scope or is deleted', w1: 'A function that creates an object', w2: 'A function that takes multiple parameters', w3: 'A static class method', exp: 'Destructors clean up resources (e.g. freeing heap memory).', d: 'Easy' },
    { q: 'How many destructors can a C++ class have?', c: 'Exactly one (it cannot be overloaded and takes no parameters)', w1: 'As many as needed (overloaded)', w2: 'Zero', w3: 'Two', exp: 'Destructors take no parameters and cannot be overloaded.', d: 'Easy' },
    { q: 'What is the \'this\' pointer in C++ member functions?', c: 'An implicit pointer holding the memory address of the current object on which the method was called', w1: 'A pointer to the base class', w2: 'A global variable', w3: 'A reference to the main function', exp: 'this points to the calling instance (*this).', d: 'Easy' },
    { q: 'Which operator is used to allocate dynamic memory on the heap in C++?', c: 'new', w1: 'malloc()', w2: 'alloc', w3: 'create', exp: 'new allocates memory and calls the class constructor.', d: 'Easy' },
    { q: 'Which operator is used to deallocate single-object memory allocated with new in C++?', c: 'delete', w1: 'free()', w2: 'remove', w3: 'destroy', exp: 'delete invokes the destructor and frees memory.', d: 'Easy' },
    { q: 'Which operator is used to deallocate an array dynamically allocated with new[] (e.g. int *arr = new int[50];)?', c: 'delete[] arr;', w1: 'delete arr;', w2: 'free(arr);', w3: 'delete[50] arr;', exp: 'delete[] ensures destructors of all array elements are called.', d: 'Easy' },
    { q: 'What is a memory leak in C++?', c: 'Allocating memory with new on the heap but failing to deallocate it with delete, wasting system RAM', w1: 'Accessing an uninitialized pointer', w2: 'Dereferencing a null pointer', w3: 'Stack overflow due to recursion', exp: 'Lost memory references that cannot be freed.', d: 'Easy' },
    { q: 'What is a copy constructor in C++?', c: 'A constructor of the form ClassName(const ClassName &other) that initializes an object from another object of the same class', w1: 'A function that assigns two integers', w2: 'A destructor copy', w3: 'A method in the math library', exp: 'Enables deep copies when objects contain pointers.', d: 'Medium' },
    { q: 'What is the danger of relying on the default compiler-generated copy constructor when a class contains raw pointers?', c: 'Shallow copy: both objects point to the same heap memory, causing double-free crashes on destruction', w1: 'Memory overflow during compilation', w2: 'Constructors become private', w3: 'Virtual table corruption', exp: 'Shallow copy copies the pointer value rather than allocating new heap memory.', d: 'Hard' },
    { q: 'What is inheritance in C++?', c: 'A mechanism where a derived class acquires the properties and methods of a base class', w1: 'Hiding data inside private scope', w2: 'Writing multiple functions with the same name', w3: 'Dynamically allocating arrays', exp: 'Fundamental OOP pillar representing an "is-a" relationship.', d: 'Easy' },
    { q: 'What is the syntax for a class Dog inheriting publicly from class Animal in C++?', c: 'class Dog : public Animal { ... };', w1: 'class Dog extends Animal { ... };', w2: 'class Dog implements Animal { ... };', w3: 'class Dog inherits Animal { ... };', exp: 'C++ uses a colon : followed by access specifier and base class name.', d: 'Easy' },
    { q: 'In public inheritance, public members of the base class become:', c: 'Public members of the derived class', w1: 'Private members of the derived class', w2: 'Protected members of the derived class', w3: 'Inaccessible', exp: 'Public inheritance preserves public visibility.', d: 'Easy' },
    { q: 'In public inheritance, private members of the base class are:', c: 'Inherited but not directly accessible by derived class member functions', w1: 'Directly accessible in derived class', w2: 'Turned into public members', w3: 'Deleted', exp: 'Private members remain strictly private to the base class.', d: 'Medium' },
    { q: 'When a derived class object is created, in what order are constructors executed?', c: 'Base class constructor first, followed by derived class constructor', w1: 'Derived class constructor first, then base class', w2: 'Simultaneously', w3: 'Only the derived constructor runs', exp: 'Base must be initialized before derived enhancements.', d: 'Easy' },
    { q: 'When a derived class object is destroyed, in what order are destructors executed?', c: 'Derived class destructor first, followed by base class destructor (reverse order)', w1: 'Base class destructor first, then derived', w2: 'Only the base destructor runs', w3: 'Simultaneously', exp: 'Destruction proceeds in exact reverse order of construction.', d: 'Easy' },
    { q: 'How can a derived class constructor pass arguments to its base class constructor in C++?', c: 'Using member initializer list: Derived(int a, int b) : Base(a) { ... }', w1: 'Calling Base(a) inside the body of Derived', w2: 'Using super(a)', w3: 'Base.init(a)', exp: 'Base constructors must be invoked via the initializer list.', d: 'Medium' },
    { q: 'What is operator overloading in C++?', c: 'Giving special meaning to existing C++ operators (like +, -, <<) when applied to user-defined class objects', w1: 'Creating completely new operator symbols', w2: 'Overriding system memory', w3: 'Changing the precedence of operators', exp: 'Keyword operator followed by symbol, e.g. operator+.', d: 'Easy' },
    { q: 'Which operator CANNOT be overloaded in C++?', c: 'The scope resolution operator (::) and member selection (.)', w1: '+', w2: '<<', w3: '[]', exp: '::, ., .*, and ?: cannot be overloaded.', d: 'Medium' },
    { q: 'What is a friend function in C++?', c: 'A non-member function granted full access to the private and protected members of a class', w1: 'A member function inherited from base class', w2: 'A function that can only access public members', w3: 'A function that cannot take arguments', exp: 'Declared with keyword friend inside class definition.', d: 'Easy' },
    { q: 'Can friendship in C++ be inherited or transitive?', c: 'No, friendship is neither inherited nor transitive', w1: 'Yes, always inherited', w2: 'Yes, if class A is friend of B, and B of C, A is friend of C', w3: 'Inherited only in public inheritance', exp: 'Friendship is granted explicitly and is not inherited.', d: 'Medium' },
    { q: 'What is a virtual function in C++ (declared with keyword \'virtual\')?', c: 'A member function in a base class that can be overridden in a derived class and supports dynamic (runtime) polymorphism', w1: 'A function that has no code', w2: 'A function stored in ROM', w3: 'A function that cannot be modified', exp: 'Resolved at runtime via the vtable.', d: 'Easy' },
    { q: 'What is a pure virtual function in C++?', c: 'A virtual function declared with = 0 (e.g. virtual void draw() = 0;)', w1: 'A virtual function with an empty body {}', w2: 'A function marked final', w3: 'A constructor', exp: '= 0 declares an interface method that must be implemented by derived classes.', d: 'Easy' },
    { q: 'A class that contains at least one pure virtual function is called:', c: 'An abstract class (cannot be instantiated directly)', w1: 'A concrete class', w2: 'A final class', w3: 'A static class', exp: 'Abstract classes serve as blueprints; you cannot create objects of an abstract class.', d: 'Easy' },
    { q: 'Why should a base class designed for polymorphic deletion have a virtual destructor?', c: 'To ensure that the derived class destructor is properly invoked when deleting a derived object via a base pointer', w1: 'To make the object smaller in memory', w2: 'To prevent objects from being deleted', w3: 'It is required for compile-time constants', exp: 'Non-virtual destructor causes undefined behavior and resource leaks during polymorphic delete.', d: 'Hard' },
    { q: 'What is the scope resolution operator in C++?', c: '::', w1: '->', w2: '.', w3: ':', exp: 'Used to specify class scope (ClassName::methodName) or global scope (::x).', d: 'Easy' },
    { q: 'What is a static data member in a C++ class?', c: 'A variable shared by all instances of the class (only one copy exists in memory)', w1: 'A variable that cannot be changed', w2: 'A variable stored on the heap for each object', w3: 'A private variable only', exp: 'Belongs to the class itself rather than individual instances.', d: 'Easy' },
    { q: 'Can a static member function in C++ access non-static class data members directly?', c: 'No, because static member functions do not have a \'this\' pointer', w1: 'Yes, always', w2: 'Only if the member is public', w3: 'Only inside main()', exp: 'Static functions lack object instance context (*this).', d: 'Medium' },
    { q: 'What is the arrow operator (->) used for in C++?', c: 'To access a member of an object through a pointer (ptr->member is equivalent to (*ptr).member)', w1: 'To declare a pointer', w2: 'To deallocate memory', w3: 'To assign a value', exp: 'Syntax sugar for dereference and member access.', d: 'Easy' },
    { q: 'What is the output of the following code?\nclass A { public: int x; A(int v) : x(v) {} };\nA a1(5); A a2 = a1; cout << a2.x;', c: '5', w1: '0', w2: 'Garbage value', w3: 'Compilation error', exp: 'Default copy constructor copies member x = 5.', d: 'Easy' },
    { q: 'What is multiple inheritance in C++?', c: 'A derived class inheriting from more than one base class (e.g. class C : public A, public B)', w1: 'A class inheriting through multiple levels', w2: 'A class with multiple constructors', w3: 'A function with multiple returns', exp: 'C++ natively allows inheriting from multiple parent classes.', d: 'Easy' },
    { q: 'The "Diamond Problem" in C++ multiple inheritance is resolved using:', c: 'Virtual inheritance (virtual base classes)', w1: 'Private inheritance', w2: 'Friend functions', w3: 'Operator overloading', exp: 'Virtual base classes ensure only one shared base subobject is created.', d: 'Hard' },
    { q: 'What is an inline function in C++?', c: 'A function where the compiler attempts to replace the function call directly with its machine code to reduce call overhead', w1: 'A function defined outside a class', w2: 'A recursive function', w3: 'A function that takes no parameters', exp: 'inline hint reduces stack frame push/pop overhead for small functions.', d: 'Medium' },
    { q: 'What is function overriding in C++?', c: 'Redefining a base class virtual function in a derived class with the exact same signature', w1: 'Defining functions with different parameters in the same class', w2: 'Hiding a function using private access', w3: 'Calling a function multiple times', exp: 'Core mechanism for dynamic runtime polymorphism.', d: 'Easy' },
    { q: 'In C++11, the \'override\' specifier is used to:', c: 'Ensure that a member function is overriding a base class virtual function (compiler throws an error if it doesn\'t)', w1: 'Make a function virtual', w2: 'Prevent a function from being inherited', w3: 'Speed up execution', exp: 'Prevents subtle bugs from mismatched signatures.', d: 'Medium' },
    { q: 'In C++11, the \'final\' specifier on a virtual function:', c: 'Prevents further derived classes from overriding that function', w1: 'Forces derived classes to override it', w2: 'Deletes the function', w3: 'Makes the function private', exp: 'Specifies the end of polymorphism for that method.', d: 'Medium' },
    { q: 'What does nullptr represent in C++11?', c: 'A type-safe null pointer literal of type std::nullptr_t', w1: 'The integer 0', w2: 'A void pointer', w3: 'An empty string', exp: 'Replaces ambiguous NULL macro (which was 0) with a distinct pointer type.', d: 'Easy' },
    { q: 'What is the Rule of Three in classic C++ for classes managing resources?', c: 'If you define a Destructor, Copy Constructor, or Copy Assignment Operator, you should define all three', w1: 'A class must have 3 constructors', w2: 'A class must have 3 member variables', w3: 'Objects cannot exceed 3 instances', exp: 'Ensures correct resource lifetime management and avoids shallow-copy bugs.', d: 'Hard' },
    { q: 'What is the syntax for defining an overloaded insertion operator (<<) for class Point?', c: 'ostream& operator<<(ostream& os, const Point& p) { ... return os; }', w1: 'Point operator<<(ostream os) { ... }', w2: 'void operator<<(Point p) { ... }', w3: 'istream& operator<<(istream& is, Point p) { ... }', exp: 'Overloaded stream operators return stream reference for chaining.', d: 'Medium' },
    { q: 'Can the assignment operator (operator=) be a non-member (friend) function in C++?', c: 'No, operator= MUST be a non-static member function of the class', w1: 'Yes, it can be a friend function', w2: 'Yes, if declared inline', w3: 'Only in structs', exp: 'C++ standard requires operator= to be a member function.', d: 'Medium' },
    { q: 'What is encapsulation in Object-Oriented Programming?', c: 'Bundling data and methods into a single unit (class) while restricting direct access to internal details (data hiding)', w1: 'Writing multiple functions with the same name', w2: 'Inheriting properties from a base class', w3: 'Dynamic memory allocation', exp: 'Definition of encapsulation.', d: 'Easy' },
    { q: 'What is polymorphism in C++?', c: 'The ability of different objects to respond to the same function call in their own specific way (one interface, multiple implementations)', w1: 'Having multiple variables of the same type', w2: 'Converting integers to strings', w3: 'Compiling code on multiple platforms', exp: 'Definition of polymorphism.', d: 'Easy' },
    { q: 'What is early (static) binding in C++?', c: 'Resolving function calls at compile time (used for regular non-virtual functions and overloaded functions)', w1: 'Resolving function calls at runtime via vtable', w2: 'Allocating memory at runtime', w3: 'Constructing static variables', exp: 'Early binding occurs at compilation.', d: 'Easy' },
    { q: 'What is late (dynamic) binding in C++?', c: 'Resolving function calls at runtime based on the actual type of the object pointed to (used for virtual functions)', w1: 'Resolving calls at compile time', w2: 'Linking libraries at build time', w3: 'Declaring inline functions', exp: 'Late binding powers runtime polymorphism.', d: 'Easy' },
    { q: 'How is dynamic dispatch implemented internally by most C++ compilers?', c: 'Through a Virtual Method Table (vtable) and a hidden virtual pointer (vptr) inside each object', w1: 'Through if-else statements generated at compile time', w2: 'Using global hash tables', w3: 'Using string comparisons of method names', exp: 'vptr points to the class vtable containing function pointers.', d: 'Hard' },
    { q: 'What is the output of: class B { public: virtual void f() { cout << "B"; } }; class D : public B { public: void f() override { cout << "D"; } }; B *ptr = new D(); ptr->f(); ?', c: 'D', w1: 'B', w2: 'BD', w3: 'Compilation error', exp: 'Because f() is virtual, ptr->f() dynamically resolves to D::f() based on actual object type.', d: 'Medium' }
  ];

  cppMid.forEach((it, idx) => qs.push(createQuestion(`CPP-MID-${String(idx + 1).padStart(3, '0')}`, 'subj-cpp', false, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'Bara C-- Mid.pdf', idx)));
  cppFinal.forEach((it, idx) => qs.push(createQuestion(`CPP-FIN-${String(idx + 1).padStart(3, '0')}`, 'subj-cpp', true, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'c-- Final.pdf', idx)));

  // ==========================================
  // OBJECT-ORIENTED PROGRAMMING (subj-oop)
  // Mid: 32 (OOP principles, Classes, Objects, Constructors, Encapsulation, Composition vs Inheritance, Shallow vs Deep Copy, Operator Overloading)
  // Final: 52 (Polymorphism, Virtual functions, Abstract classes, Pure virtual, Interface design, Templates, STL containers, Exception handling, Design patterns basics)
  // ==========================================
  const oopMid = [
    { q: 'Which of the following is NOT one of the four primary pillars of Object-Oriented Programming?', c: 'Compilation', w1: 'Encapsulation', w2: 'Inheritance', w3: 'Polymorphism', exp: 'The four pillars are Encapsulation, Abstraction, Inheritance, and Polymorphism.', d: 'Easy' },
    { q: 'Encapsulation is best demonstrated by:', c: 'Making member variables private and providing public getter and setter methods', w1: 'Creating multiple derived classes', w2: 'Writing global functions', w3: 'Using templates for generic types', exp: 'Data hiding combined with accessor methods encapsulates state.', d: 'Easy' },
    { q: 'An instance of a class is known as:', c: 'An object', w1: 'A method', w2: 'An interface', w3: 'A template', exp: 'A class is a blueprint; an object is an instance.', d: 'Easy' },
    { q: 'A constructor that initializes all member variables with default values when no arguments are provided is a:', c: 'Default constructor', w1: 'Parameterized constructor', w2: 'Copy constructor', w3: 'Destructor', exp: 'Invoked when an object is declared with no arguments.', d: 'Easy' },
    { q: 'What is constructor overloading?', c: 'Defining multiple constructors with different parameter lists in the same class', w1: 'Having constructors in both base and derived classes', w2: 'Calling a constructor inside a loop', w3: 'A constructor that calls a destructor', exp: 'Permits object initialization in multiple ways.', d: 'Easy' },
    { q: 'In C++, constructor delegation (introduced in C++11) allows:', c: 'A constructor to call another constructor of the same class in its initializer list', w1: 'A constructor to call a destructor', w2: 'A class to delegate its construction to a global function', w3: 'A derived class constructor to be private', exp: 'Reduces duplicate initialization code.', d: 'Medium' },
    { q: 'The initialization list of a constructor is executed:', c: 'Before the constructor body executes', w1: 'After the constructor body finishes', w2: 'Only when an error occurs', w3: 'During destruction', exp: 'Initializes members directly upon memory allocation.', d: 'Medium' },
    { q: 'Which members MUST be initialized in the constructor initialization list rather than the body?', c: 'const members and reference members (&)', w1: 'int variables only', w2: 'Static members', w3: 'Private members', exp: 'References and const members must be initialized when created, not assigned.', d: 'Hard' },
    { q: 'What is a copy constructor called for?', c: 'When an object is passed by value to a function, returned by value, or initialized from another object of the same type', w1: 'When assigning an object using = operator after initialization', w2: 'When deleting an object', w3: 'Only during compilation', exp: 'Invoked during initialization from another instance.', d: 'Medium' },
    { q: 'What is the signature of a standard copy constructor for class Complex?', c: 'Complex(const Complex &other);', w1: 'Complex(Complex other);', w2: 'void Complex(Complex *other);', w3: 'Complex copy(Complex other);', exp: 'Must take by reference (typically const); passing by value would cause infinite recursion.', d: 'Hard' },
    { q: 'A deep copy differs from a shallow copy because a deep copy:', c: 'Allocates new memory and copies the actual values rather than just copying pointer addresses', w1: 'Only copies the first member', w2: 'Is automatically done by default by the compiler', w3: 'Uses less memory', exp: 'Prevents aliasing and double-free errors.', d: 'Medium' },
    { q: 'The "is-a" relationship in object-oriented design is modeled using:', c: 'Inheritance', w1: 'Composition', w2: 'Aggregation', w3: 'Friendship', exp: 'Example: Dog is-an Animal.', d: 'Easy' },
    { q: 'The "has-a" relationship in object-oriented design is modeled using:', c: 'Composition or Aggregation', w1: 'Inheritance', w2: 'Polymorphism', w3: 'Template specialization', exp: 'Example: Car has-an Engine.', d: 'Easy' },
    { q: 'In composition (strong "has-a"):', c: 'The contained object cannot exist independently of the containing object (shared lifetime)', w1: 'The contained object exists independently', w2: 'The relationship is defined using the \'is\' keyword', w3: 'The base class is abstract', exp: 'Destroying a Car destroys its Engine subobject in composition.', d: 'Medium' },
    { q: 'In aggregation (weak "has-a"):', c: 'The contained object can exist independently of the containing object (e.g., Department has Teachers)', w1: 'The lifetime of both objects is strictly identical', w2: 'Inheritance is required', w3: 'Private inheritance is enforced', exp: 'Teachers continue to exist even if Department is closed.', d: 'Medium' },
    { q: 'The keyword \'explicit\' on a single-parameter constructor prevents:', c: 'Implicit type conversions and copy-initialization', w1: 'The constructor from being called', w2: 'Memory allocation', w3: 'Inheritance of the constructor', exp: 'explicit Complex(double r) prevents code like Complex c = 5.0.', d: 'Hard' },
    { q: 'Operator overloading enables user-defined classes to:', c: 'Define custom behavior for standard operators (+, -, *, ==, <<, etc.)', w1: 'Change the precedence of C++ operators', w2: 'Invent new operators like @ or $', w3: 'Bypass encapsulation completely', exp: 'Provides intuitive, readable mathematical syntax for objects.', d: 'Easy' },
    { q: 'Which operator should return *this by reference to allow chaining (e.g. a = b = c;)?', c: 'The assignment operator (operator=)', w1: 'The addition operator (operator+)', w2: 'The equality operator (operator==)', w3: 'The destructor', exp: 'MyClass& operator=(const MyClass &rhs) { ... return *this; } allows assignment chaining.', d: 'Medium' },
    { q: 'Why is self-assignment check (if (this == &rhs) return *this;) essential in operator=?', c: 'To prevent deleting your own heap memory before copying it', w1: 'To make the assignment faster', w2: 'To prevent infinite recursion', w3: 'It is optional and never needed', exp: 'Deleting old resources in a self-assignment would destroy the source data.', d: 'Hard' },
    { q: 'A static member function:', c: 'Can be invoked using ClassName::functionName() without creating an instance of the class', w1: 'Has access to non-static member variables', w2: 'Has a this pointer', w3: 'Cannot be public', exp: 'Static methods belong to the class, not to an instance.', d: 'Easy' },
    { q: 'Const member functions (e.g., int getX() const;):', c: 'Promise not to modify any non-mutable member variables of the calling object', w1: 'Can only be called by const objects', w2: 'Cannot return any value', w3: 'Can only be static', exp: 'Guarantees read-only access on *this.', d: 'Medium' },
    { q: 'Which keyword allows a specific member variable to be modified even inside a const member function?', c: 'mutable', w1: 'volatile', w2: 'dynamic', w3: 'register', exp: 'mutable variables (e.g. cache/mutex) can be modified in const methods.', d: 'Hard' },
    { q: 'What is the purpose of getter and setter methods?', c: 'To control and validate access to private data members (maintaining encapsulation)', w1: 'To speed up execution', w2: 'To replace constructors', w3: 'To make all variables public', exp: 'Enables data validation and hides internal representations.', d: 'Easy' },
    { q: 'What is method overloading in OOP?', c: 'Defining multiple methods in the same class with identical names but different signatures', w1: 'Re-implementing a base class method in a derived class', w2: 'Calling a method recursively', w3: 'Making a method static', exp: 'Compile-time ad-hoc polymorphism.', d: 'Easy' },
    { q: 'Can a constructor be declared as virtual in C++?', c: 'No, constructors CANNOT be virtual', w1: 'Yes, always', w2: 'Only in abstract classes', w3: 'Only default constructors', exp: 'An object\'s exact type must be known at construction time; vtable is established during construction.', d: 'Medium' },
    { q: 'Can a destructor be declared as virtual in C++?', c: 'Yes, and base classes designed for inheritance should virtually always have virtual destructors', w1: 'No, destructors cannot be virtual', w2: 'Only private destructors', w3: 'Only in structs', exp: 'Virtual destructor is necessary for proper cleanup via base class pointers.', d: 'Easy' },
    { q: 'In C++, protected members of a base class are accessible by:', c: 'Member functions of the base class and member functions of derived classes', w1: 'The public world directly', w2: 'Only the base class itself', w3: 'Unrelated classes', exp: 'Provides visibility down the inheritance hierarchy.', d: 'Easy' },
    { q: 'What is the return type of the comparison operator operator==(const MyClass &other) const?', c: 'bool', w1: 'int', w2: 'void', w3: 'MyClass', exp: 'Comparison yields true or false.', d: 'Easy' },
    { q: 'When an object is passed BY VALUE to a function:', c: 'The copy constructor is called to create a local copy', w1: 'The address of the original object is passed', w2: 'The destructor is called immediately', w3: 'The object cannot be read', exp: 'Pass-by-value invokes the copy constructor.', d: 'Easy' },
    { q: 'When an object is passed BY CONST REFERENCE (const MyClass &obj):', c: 'No copy is made (efficient) and the function cannot modify the original object (safe)', w1: 'A deep copy is made', w2: 'The object is destroyed upon return', w3: 'Only public members can be read', exp: 'Combines the efficiency of pass-by-reference with the safety of pass-by-value.', d: 'Medium' },
    { q: 'What is an anonymous (temporary) object in C++?', c: 'An unnamed object created on the fly (e.g. return Complex(1, 2);)', w1: 'An object with no class', w2: 'A null pointer', w3: 'A leaked memory block', exp: 'Rvalue temporary objects with lifespan of the full expression.', d: 'Medium' },
    { q: 'The scope of an automatic object declared inside a block { ... } ends when:', c: 'Execution reaches the closing brace }, and its destructor is called automatically', w1: 'The program terminates', w2: 'delete is called manually', w3: 'After 10 seconds', exp: 'Automatic stack storage duration.', d: 'Easy' }
  ];

  const oopFinal = [
    { q: 'Polymorphism in OOP is primarily achieved in C++ through:', c: 'Inheritance and virtual functions (dynamic binding)', w1: 'Friend functions', w2: 'Global variables', w3: 'Preprocessor macros', exp: 'Virtual functions enable runtime dynamic dispatch.', d: 'Easy' },
    { q: 'A class with at least one pure virtual function (virtual void f() = 0;) is:', c: 'An abstract class, which cannot be instantiated directly', w1: 'A concrete class', w2: 'An empty class', w3: 'A sealed class', exp: 'Abstract classes define interfaces for derived classes to implement.', d: 'Easy' },
    { q: 'If a derived class does NOT override a pure virtual function inherited from an abstract base class:', c: 'The derived class also becomes an abstract class and cannot be instantiated', w1: 'The code compiles and runs using the base implementation', w2: 'The pure virtual function is ignored', w3: 'A runtime exception is thrown on startup', exp: 'Failure to implement pure virtual functions leaves derived class abstract.', d: 'Medium' },
    { q: 'What is the Virtual Method Table (vtable)?', c: 'An array of function pointers maintained by the compiler for each polymorphic class to resolve virtual function calls at runtime', w1: 'A table of object variables in RAM', w2: 'A database table', w3: 'A debug log file', exp: 'Core mechanism of C++ runtime polymorphism.', d: 'Medium' },
    { q: 'Every object of a polymorphic class contains a hidden pointer called:', c: 'vptr (virtual pointer), which points to the class\'s vtable', w1: 'this pointer', w2: 'base pointer', w3: 'heap pointer', exp: 'Added to object layout to locate the vtable.', d: 'Medium' },
    { q: 'What is an interface in object-oriented design?', c: 'A class that contains ONLY pure virtual functions and no data members, defining a contract', w1: 'A graphical user interface (GUI)', w2: 'A class with only private members', w3: 'A template function', exp: 'Abstract interface contract pattern.', d: 'Easy' },
    { q: 'What does the dynamic_cast operator do in C++?', c: 'Safely converts a base class pointer to a derived class pointer at runtime, returning nullptr if invalid', w1: 'Converts integers to floats', w2: 'Forces a cast without any checks', w3: 'Allocates dynamic memory', exp: 'Uses Run-Time Type Information (RTTI) to verify polymorphic downcasts.', d: 'Hard' },
    { q: 'What does typeid operator return in C++?', c: 'A reference to a std::type_info object representing the runtime type of an expression', w1: 'The size of the object in bytes', w2: 'The memory address', w3: 'A string copy', exp: 'Requires #include <typeinfo> and polymorphic types for runtime inspection.', d: 'Medium' },
    { q: 'What are function templates in C++?', c: 'Blueprints for generating functions that can operate on different data types with a single codebase', w1: 'Macros that replace text', w2: 'Virtual functions in base classes', w3: 'Inline assembly functions', exp: 'template <typename T> T max(T a, T b) generates type-specific functions at compile time.', d: 'Easy' },
    { q: 'What are class templates in C++?', c: 'Generic classes parameterized by types (e.g. template <typename T> class Stack { ... };)', w1: 'Classes that cannot have members', w2: 'Inherited classes only', w3: 'Abstract classes with no methods', exp: 'Foundation of generic programming and the Standard Template Library (STL).', d: 'Easy' },
    { q: 'The C++ Standard Template Library (STL) consists of which three major components?', c: 'Containers, Iterators, and Algorithms', w1: 'Classes, Objects, and Functions', w2: 'Pointers, References, and Arrays', w3: 'Compilers, Linkers, and Debuggers', exp: 'The classic STL triad.', d: 'Easy' },
    { q: 'Which STL container represents a dynamically resizable array with contiguous memory storage?', c: 'std::vector', w1: 'std::list', w2: 'std::set', w3: 'std::map', exp: 'std::vector provides O(1) random access and dynamic resizing.', d: 'Easy' },
    { q: 'What is the time complexity of accessing an element by index (vec[i]) in a std::vector?', c: 'O(1) (constant time)', w1: 'O(n)', w2: 'O(log n)', w3: 'O(n²)', exp: 'Contiguous memory allows immediate address calculation.', d: 'Easy' },
    { q: 'What is the time complexity of inserting an element at the back of std::vector (push_back)?', c: 'Amortized O(1)', w1: 'O(n) always', w2: 'O(log n)', w3: 'O(n²)', exp: 'Capacity doubling ensures amortized constant time.', d: 'Medium' },
    { q: 'Which STL container implements a doubly-linked list with non-contiguous memory storage?', c: 'std::list', w1: 'std::vector', w2: 'std::deque', w3: 'std::array', exp: 'std::list is a doubly linked list with O(1) insertions anywhere given an iterator.', d: 'Easy' },
    { q: 'Which STL container stores unique elements sorted automatically in logarithmic time?', c: 'std::set (implemented as a Red-Black Tree)', w1: 'std::vector', w2: 'std::list', w3: 'std::stack', exp: 'Self-balancing BST guarantees O(log n) search, insertion, and deletion.', d: 'Medium' },
    { q: 'Which STL container stores key-value pairs sorted by key?', c: 'std::map', w1: 'std::set', w2: 'std::pair', w3: 'std::vector', exp: 'std::map<Key, Value> stores sorted associative pairs in a Red-Black tree.', d: 'Easy' },
    { q: 'What is an iterator in C++ STL?', c: 'An object that points to an element within a container and enables sequential traversal like a pointer', w1: 'A loop counter variable', w2: 'A sorting function', w3: 'An index integer', exp: 'Abstracts traversal across different container types.', d: 'Easy' },
    { q: 'Which method returns an iterator pointing to the FIRST element of an STL container?', c: 'container.begin()', w1: 'container.front()', w2: 'container.start()', w3: 'container.first()', exp: 'begin() returns an iterator; front() returns a reference to the element.', d: 'Easy' },
    { q: 'Which method returns an iterator pointing PAST THE LAST element of an STL container?', c: 'container.end()', w1: 'container.back()', w2: 'container.last()', w3: 'container.stop()', exp: 'end() points to the theoretical past-the-end position.', d: 'Easy' },
    { q: 'In C++ exception handling, which block contains code that might throw an exception?', c: 'try block', w1: 'catch block', w2: 'throw block', w3: 'finally block', exp: 'Exceptions thrown inside a try block are caught by an associated catch block.', d: 'Easy' },
    { q: 'Which keyword is used to signal/raise an exception in C++?', c: 'throw', w1: 'raise', w2: 'catch', w3: 'signal', exp: 'throw expr; raises an exception.', d: 'Easy' },
    { q: 'A catch(...) block with three dots in C++ catches:', c: 'Any exception of any type (catch-all handler)', w1: 'Only integer exceptions', w2: 'Only standard exceptions', w3: 'Zero exceptions', exp: 'Default catch-all handler.', d: 'Easy' },
    { q: 'What is RAII (Resource Acquisition Is Initialization) in C++?', c: 'A programming idiom where resources (memory, file handles, sockets) are acquired in a constructor and released in the destructor', w1: 'A compiler flag for optimizations', w2: 'A method for initializing arrays with zeros', w3: 'An algorithm for garbage collection', exp: 'Ensures exception-safe leak-free resource management.', d: 'Medium' },
    { q: 'Which C++11 smart pointer represents exclusive ownership of a dynamically allocated object?', c: 'std::unique_ptr', w1: 'std::shared_ptr', w2: 'std::weak_ptr', w3: 'std::auto_ptr', exp: 'Cannot be copied, only moved (std::move).', d: 'Medium' },
    { q: 'Which C++11 smart pointer represents shared ownership using reference counting?', c: 'std::shared_ptr', w1: 'std::unique_ptr', w2: 'std::raw_ptr', w3: 'std::safe_ptr', exp: 'Deletes object when the reference count drops to zero.', d: 'Medium' },
    { q: 'std::weak_ptr is used in conjunction with std::shared_ptr to solve:', c: 'Cyclic reference memory leaks (circular dependencies)', w1: 'Dangling pointers', w2: 'Out-of-bounds array access', w3: 'Stack overflow', exp: 'Observes an object without incrementing its reference count.', d: 'Hard' },
    { q: 'The Singleton design pattern ensures that:', c: 'A class has only one instance and provides a global access point to it', w1: 'A class has no instances', w2: 'Every object has unique methods', w3: 'All methods are virtual', exp: 'Private constructor + static getInstance() method.', d: 'Medium' },
    { q: 'The Factory Method design pattern is used to:', c: 'Define an interface for creating an object, but let subclasses decide which class to instantiate', w1: 'Destroy objects safely', w2: 'Convert objects to JSON', w3: 'Ensure single ownership', exp: 'Decouples object creation from client code.', d: 'Medium' },
    { q: 'In the SOLID design principles, the "S" stands for:', c: 'Single Responsibility Principle (a class should have one, and only one, reason to change)', w1: 'Static Typing Principle', w2: 'Scope Resolution', w3: 'System Inheritance', exp: 'Each module/class focuses on a single responsibility.', d: 'Medium' },
    { q: 'In SOLID principles, the "O" stands for the Open/Closed Principle, which states that software entities should be:', c: 'Open for extension, but closed for modification', w1: 'Open source only', w2: 'Closed to user inputs', w3: 'Open to inheritance but closed to composition', exp: 'Extend behavior by adding code, not modifying tested code.', d: 'Medium' },
    { q: 'In SOLID principles, the "L" stands for Liskov Substitution Principle (LSP), which requires that:', c: 'Subtypes must be substitutable for their base types without altering the correctness of the program', w1: 'Subclasses must override every method', w2: 'Base classes must be abstract', w3: 'Classes cannot have more than 2 levels of inheritance', exp: 'Derived classes must adhere to base class contracts.', d: 'Hard' },
    { q: 'In SOLID principles, the "I" stands for Interface Segregation Principle, meaning:', c: 'Clients should not be forced to depend on interfaces they do not use (many specific interfaces are better than one general interface)', w1: 'Interfaces must be private', w2: 'Classes can only implement one interface', w3: 'Interfaces cannot have virtual methods', exp: 'Break large interfaces into smaller, cohesive ones.', d: 'Medium' },
    { q: 'In SOLID principles, the "D" stands for Dependency Inversion Principle, which states:', c: 'High-level modules should not depend on low-level modules; both should depend on abstractions', w1: 'Dependencies must be declared global', w2: 'Derived classes cannot call base methods', w3: 'Destructors cannot throw exceptions', exp: 'Depend upon abstractions, not concretions.', d: 'Hard' },
    { q: 'Which STL algorithm is used to sort a container in ascending order?', c: 'std::sort(vec.begin(), vec.end());', w1: 'std::order(vec);', w2: 'vec.sort();', w3: 'std::arrange(vec.start());', exp: 'std::sort uses introsort (quick/heap/insertion hybrid) running in O(n log n).', d: 'Easy' },
    { q: 'Which STL algorithm performs binary search on a pre-sorted container?', c: 'std::binary_search(begin, end, val)', w1: 'std::find(begin, end, val)', w2: 'std::search_binary()', w3: 'std::lookup()', exp: 'Returns true/false in O(log n) time.', d: 'Easy' },
    { q: 'What is a lambda function in C++11?', c: 'An anonymous inline function that can capture variables from its enclosing scope [captures](params){body}', w1: 'A function defined in a separate header', w2: 'A virtual destructor', w3: 'A global macro', exp: 'Convenient callable objects used with algorithms.', d: 'Medium' },
    { q: 'In a C++11 lambda [=](int x) { return x + a; }, the capture clause [=] means:', c: 'Capture all local variables used in the lambda BY VALUE', w1: 'Capture all variables BY REFERENCE', w2: 'Capture nothing', w3: 'Only capture global variables', exp: '[=] captures by value; [&] captures by reference.', d: 'Medium' },
    { q: 'What does std::move do in C++11?', c: 'Casts an lvalue to an rvalue reference (T&&), enabling move semantics instead of expensive deep copying', w1: 'Physically moves bytes in memory', w2: 'Deletes the source object immediately', w3: 'Copies an object to the heap', exp: 'Unlocks move constructors and move assignment operators.', d: 'Hard' },
    { q: 'What is the benefit of move semantics in C++11?', c: 'Resources (e.g. heap memory pointers) are transferred from temporary objects without expensive deep copying', w1: 'It prevents all compiler errors', w2: 'It eliminates the need for constructors', w3: 'It makes all functions virtual', exp: 'Move constructors transfer ownership in O(1) pointer swaps.', d: 'Hard' },
    { q: 'The Observer design pattern is ideal for:', c: 'A one-to-many dependency where when one object changes state, all its dependents are notified automatically', w1: 'Creating families of related objects', w2: 'Wrapping an incompatible interface', w3: 'Ensuring only one instance of a class exists', exp: 'Core pattern for event handling and MVC architecture.', d: 'Medium' },
    { q: 'The Adapter design pattern is used to:', c: 'Convert the interface of a class into another interface clients expect, enabling incompatible classes to work together', w1: 'Ensure thread safety', w2: 'Clone objects', w3: 'Hide class implementation', exp: 'Structural wrapper pattern.', d: 'Medium' },
    { q: 'What is the purpose of std::stack container adapter in STL?', c: 'Provides Last-In, First-Out (LIFO) access with push(), pop(), and top() operations', w1: 'First-In, First-Out (FIFO)', w2: 'Random access by index', w3: 'Sorted storage', exp: 'Restricts operations to LIFO discipline.', d: 'Easy' },
    { q: 'What is the purpose of std::queue in STL?', c: 'Provides First-In, First-Out (FIFO) access with push(), pop(), front(), and back()', w1: 'LIFO access', w2: 'Direct indexing', w3: 'Hash storage', exp: 'Standard FIFO queue.', d: 'Easy' },
    { q: 'What is std::priority_queue in STL based on by default?', c: 'A Max-Heap where top() always returns the largest element', w1: 'A Min-Heap', w2: 'A FIFO linked list', w3: 'A circular array', exp: 'Default priority_queue is a max-heap.', d: 'Medium' },
    { q: 'In C++ templates, template specialization allows:', c: 'Providing a customized implementation of a template for a specific data type', w1: 'Restricting a template to only integers', w2: 'Preventing templates from compiling', w3: 'Inheriting from templates', exp: 'e.g. template <> class Vector<bool> specialized for bit packing.', d: 'Hard' },
    { q: 'What is slicing in C++?', c: 'Assigning a derived object to a base object by value, which strips off (slices away) the derived members', w1: 'Dividing an array into two halves', w2: 'Deleting memory partially', w3: 'Converting float to int', exp: 'Occurs when assigning Base b = derived_obj; avoided by using pointers or references.', d: 'Hard' },
    { q: 'An abstract class can have:', c: 'Constructors, member variables, normal member functions, and pure virtual functions', w1: 'Only pure virtual functions and nothing else', w2: 'No constructors', w3: 'No member variables', exp: 'Abstract classes can have normal state and methods for derived reuse.', d: 'Medium' },
    { q: 'What is the output of std::min(10, 20) in <algorithm>?', c: '10', w1: '20', w2: '0', w3: '15', exp: 'Returns the smaller of two values.', d: 'Easy' },
    { q: 'What happens if an exception is thrown in C++ but never caught by any catch block?', c: 'std::terminate() is called, terminating the program abnormally', w1: 'The program ignores the error and continues', w2: 'The operating system restarts the function', w3: 'The compiler fixes the error', exp: 'Uncaught exceptions invoke std::terminate.', d: 'Medium' },
    { q: 'Why should destructors never throw exceptions in C++?', c: 'If another exception is already active during stack unwinding, throwing another terminates the program immediately', w1: 'Destructors cannot contain code', w2: 'Exceptions make destructors slower', w3: 'It is a syntax error to write try-catch in a destructor', exp: 'Two simultaneous exceptions trigger immediate std::terminate.', d: 'Hard' },
    { q: 'The Strategy design pattern allows:', c: 'Defining a family of algorithms, encapsulating each one, and making them interchangeable at runtime', w1: 'Creating only one object instance', w2: 'Restricting access to private fields', w3: 'Copying complex trees', exp: 'Enables switching behavioral algorithms dynamically.', d: 'Medium' }
  ];

  oopMid.forEach((it, idx) => qs.push(createQuestion(`OOP-MID-${String(idx + 1).padStart(3, '0')}`, 'subj-oop', false, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'Midterms (2023-2024).pdf', idx)));
  oopFinal.forEach((it, idx) => qs.push(createQuestion(`OOP-FIN-${String(idx + 1).padStart(3, '0')}`, 'subj-oop', true, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, '2023_2024 Final.pdf', idx)));

  return qs;
}

module.exports = { getCppAndOopQuestions };
