const { createQuestion } = require('./bank_factory');

function getDsAndAsmQuestions() {
  const qs = [];

  // ==========================================
  // DATA STRUCTURES & ALGORITHMS (subj-datastruct)
  // Mid: 32 (Big-O analysis, Arrays, Stacks, Queues, Circular Queues, Linked Lists - singly, doubly, circular, Stack applications like infix/postfix, Recursion)
  // Final: 52 (Trees, BST, AVL Trees, Heaps, Priority Queues, Hashing, Hash Tables, Graphs - BFS/DFS, Shortest Path Dijkstra, MST Prim/Kruskal, Sorting algorithms)
  // ==========================================
  const dsMid = [
    { q: 'What does Big-O notation O(f(n)) describe in algorithm analysis?', c: 'An asymptotic upper bound on the growth rate of running time or space as input size n grows', w1: 'The exact number of CPU clock cycles', w2: 'The lower bound on execution time', w3: 'The average number of lines of code', exp: 'Big-O represents worst-case asymptotic upper bound.', d: 'Easy' },
    { q: 'Which of the following time complexities grows the SLOWEST as n approaches infinity?', c: 'O(log n)', w1: 'O(n)', w2: 'O(n log n)', w3: 'O(n²)', exp: 'Logarithmic growth is strictly slower than linear or polynomial growth.', d: 'Easy' },
    { q: 'Which time complexity represents quadratic growth?', c: 'O(n²)', w1: 'O(2^n)', w2: 'O(n³)', w3: 'O(n log n)', exp: 'n² is quadratic.', d: 'Easy' },
    { q: 'What is the time complexity of searching for an element in an UNSORTED array of size n?', c: 'O(n) (linear search)', w1: 'O(1)', w2: 'O(log n)', w3: 'O(n²)', exp: 'In the worst case, every element must be inspected.', d: 'Easy' },
    { q: 'What is the time complexity of Binary Search on a SORTED array of size n?', c: 'O(log n)', w1: 'O(n)', w2: 'O(1)', w3: 'O(n log n)', exp: 'Each comparison halves the remaining search space.', d: 'Easy' },
    { q: 'A Stack is an abstract data structure that follows which principle?', c: 'LIFO (Last-In, First-Out)', w1: 'FIFO (First-In, First-Out)', w2: 'LILO (Last-In, Last-Out)', w3: 'Priority order', exp: 'The last element pushed is the first one popped.', d: 'Easy' },
    { q: 'What is the time complexity of push and pop operations on a stack implemented with an array or linked list?', c: 'O(1) constant time', w1: 'O(n)', w2: 'O(log n)', w3: 'O(n²)', exp: 'Accessing and modifying the top of the stack is O(1).', d: 'Easy' },
    { q: 'What condition occurs when attempting to pop from an empty stack?', c: 'Stack Underflow', w1: 'Stack Overflow', w2: 'Segmentation fault always', w3: 'Null pointer exception', exp: 'Popping from empty stack is underflow.', d: 'Easy' },
    { q: 'What condition occurs when attempting to push onto a full array-based stack of fixed capacity?', c: 'Stack Overflow', w1: 'Stack Underflow', w2: 'Memory leak', w3: 'Dangling pointer', exp: 'Exceeding allocated capacity is overflow.', d: 'Easy' },
    { q: 'Which data structure is primarily used to evaluate arithmetic postfix (Reverse Polish) expressions?', c: 'Stack', w1: 'Queue', w2: 'Binary Tree', w3: 'Graph', exp: 'Operands are pushed onto a stack; operators pop two operands and push result.', d: 'Easy' },
    { q: 'Evaluate the postfix expression: 5 3 + 2 *', c: '16', w1: '11', w2: '13', w3: '10', exp: '5 + 3 = 8; 8 * 2 = 16.', d: 'Easy' },
    { q: 'A Queue is an abstract data structure that follows which principle?', c: 'FIFO (First-In, First-Out)', w1: 'LIFO (Last-In, First-Out)', w2: 'Random access', w3: 'Alphabetical order', exp: 'Elements are enqueued at rear and dequeued from front.', d: 'Easy' },
    { q: 'In a standard linear queue implemented with a fixed array, what problem arises after multiple enqueues and dequeues?', c: 'False overflow: rear reaches the end of the array while front space is empty', w1: 'Stack underflow', w2: 'Infinite recursion', w3: 'Array corruption', exp: 'Linear array queue wastes vacated front spaces.', d: 'Medium' },
    { q: 'How does a Circular Queue solve the false overflow problem of linear queues?', c: 'By wrapping the indices around using the modulo operator: (rear + 1) % MAX_SIZE', w1: 'By shifting all elements forward on every dequeue', w2: 'By dynamically doubling array size each time', w3: 'By using pointers to functions', exp: 'Modulo arithmetic wraps around to reuse front positions in O(1).', d: 'Medium' },
    { q: 'In a singly linked list, each node contains:', c: 'Data and a pointer/reference to the next node in the list', w1: 'Only data', w2: 'Data and pointers to both next and previous nodes', w3: 'An array index', exp: 'Singly linked list has a single forward pointer.', d: 'Easy' },
    { q: 'What is the time complexity of inserting a new node at the HEAD (beginning) of a singly linked list?', c: 'O(1)', w1: 'O(n)', w2: 'O(log n)', w3: 'O(n²)', exp: 'Only requires updating new node\'s next and the head pointer.', d: 'Easy' },
    { q: 'What is the time complexity of accessing the k-th element in a singly linked list of size n?', c: 'O(k) or O(n) in worst case (sequential access)', w1: 'O(1) random access', w2: 'O(log n)', w3: 'O(n²)', exp: 'Must traverse k pointers sequentially from head.', d: 'Easy' },
    { q: 'In a doubly linked list, each node contains:', c: 'Data, a pointer to the next node, and a pointer to the previous node', w1: 'Two data fields and one pointer', w2: 'Pointers to left and right child nodes', w3: 'Only a next pointer', exp: 'Bidirectional links permit two-way traversal.', d: 'Easy' },
    { q: 'What is the main advantage of a doubly linked list over a singly linked list?', c: 'Can be traversed in both directions, and a node can be deleted in O(1) if its pointer is given', w1: 'Uses less memory', w2: 'Guarantees O(1) search by value', w3: 'Provides array-like indexing', exp: 'Access to node->prev enables instant local link adjustments.', d: 'Medium' },
    { q: 'What does the \'next\' pointer of the last node point to in a standard NULL-terminated singly linked list?', c: 'nullptr (or NULL)', w1: 'The head node', w2: 'Itself', w3: 'A random address', exp: 'nullptr signals the end of the list.', d: 'Easy' },
    { q: 'In a circular linked list, what does the \'next\' pointer of the last node point to?', c: 'The first (head) node of the list', w1: 'nullptr', w2: 'The previous node', w3: 'Itself always', exp: 'Forms a continuous closed cycle with no null pointers.', d: 'Easy' },
    { q: 'Floyd\'s Cycle-Finding Algorithm (Tortoise and Hare) detects a cycle in a linked list by using:', c: 'Two pointers moving at different speeds (slow moves 1 step, fast moves 2 steps)', w1: 'A hash table storing all addresses', w2: 'Sorting the pointers', w3: 'Recursion with depth counter', exp: 'Fast pointer catches slow pointer inside any loop in O(n) time and O(1) space.', d: 'Hard' },
    { q: 'What is the space complexity of an in-place algorithm that reverses a singly linked list iteratively?', c: 'O(1) auxiliary space', w1: 'O(n)', w2: 'O(n²)', w3: 'O(log n)', exp: 'Only requires three temporary pointers (prev, curr, next).', d: 'Medium' },
    { q: 'What is a Deque (Double-Ended Queue)?', c: 'A linear data structure where elements can be inserted and deleted from both ends (front and rear) in O(1)', w1: 'A queue that only deletes from front', w2: 'A stack with two arrays', w3: 'A tree data structure', exp: 'Double-ended queue supports push/pop at both front and back.', d: 'Easy' },
    { q: 'Converting an infix expression (A + B * C) to postfix yields:', c: 'A B C * +', w1: 'A B + C *', w2: '+ A * B C', w3: 'A B * C +', exp: 'Multiplication has higher precedence than addition: B * C first, then A + (B * C).', d: 'Medium' },
    { q: 'Which data structure is inherently used by the operating system to manage function calls and local variables?', c: 'Call Stack', w1: 'Priority Queue', w2: 'Circular Queue', w3: 'Binary Search Tree', exp: 'Activation records (stack frames) are pushed on call and popped on return.', d: 'Easy' },
    { q: 'What happens if a recursive function lacks a base case or has an unreachable base case?', c: 'Infinite recursion resulting in a Stack Overflow error', w1: 'Memory leak in heap', w2: 'Queue underflow', w3: 'Slow execution without crashing', exp: 'Call stack exhausts allocated thread stack memory.', d: 'Easy' },
    { q: 'What is the recurrence relation for the Tower of Hanoi problem with n disks?', c: 'T(n) = 2 T(n - 1) + 1, giving time complexity O(2^n)', w1: 'T(n) = T(n - 1) + 1', w2: 'T(n) = 2 T(n / 2) + n', w3: 'T(n) = T(n - 2) + n', exp: 'Move n - 1 disks twice plus 1 move for the largest disk => 2^n - 1 moves.', d: 'Medium' },
    { q: 'In dynamic arrays (like std::vector), when the array is full, its capacity is typically:', c: 'Doubled (multiplied by 2 or 1.5), copying existing elements to a new memory block', w1: 'Increased by 1 element', w2: 'Fixed forever', w3: 'Halved', exp: 'Geometric resizing achieves amortized O(1) push_back.', d: 'Easy' },
    { q: 'What is the time complexity to insert an element at index 0 of an array of size n?', c: 'O(n)', w1: 'O(1)', w2: 'O(log n)', w3: 'O(n²)', exp: 'All n elements must be shifted one position to the right.', d: 'Easy' },
    { q: 'What is the time complexity to delete an element at index 0 of an array of size n?', c: 'O(n)', w1: 'O(1)', w2: 'O(log n)', w3: 'O(n²)', exp: 'Remaining n - 1 elements must be shifted one position to the left.', d: 'Easy' },
    { q: 'Which statement is TRUE comparing Arrays and Linked Lists?', c: 'Arrays provide O(1) random access by index; Linked Lists provide O(1) insertion/deletion at known nodes without shifting', w1: 'Linked Lists use less memory per element than Arrays', w2: 'Arrays can easily grow without reallocating contiguous memory', w3: 'Binary search can be performed in O(log n) on a singly linked list', exp: 'Fundamental trade-off between contiguous arrays and pointer-linked nodes.', d: 'Medium' }
  ];

  const dsFinal = [
    { q: 'In a tree data structure, the unique node with no parent is called the:', c: 'Root node', w1: 'Leaf node', w2: 'Internal node', w3: 'Sibling node', exp: 'The top-level origin of the tree hierarchy.', d: 'Easy' },
    { q: 'A node in a tree with no children is called a:', c: 'Leaf node (external node)', w1: 'Root node', w2: 'Parent node', w3: 'Branch node', exp: 'Leaves have degree 0.', d: 'Easy' },
    { q: 'The depth of a node in a tree is defined as:', c: 'The number of edges from the root node to that node', w1: 'The number of children the node has', w2: 'The height of the tree', w3: 'The total number of leaves', exp: 'Root is at depth 0.', d: 'Easy' },
    { q: 'In a Binary Tree, each node can have at most:', c: '2 children (left child and right child)', w1: '1 child', w2: '3 children', w3: 'Any number of children', exp: 'Binary means degree at most 2.', d: 'Easy' },
    { q: 'A Full (Proper) Binary Tree is a binary tree in which:', c: 'Every node has either 0 or 2 children', w1: 'All leaf nodes are at the same depth', w2: 'Every node has exactly 1 child', w3: 'All levels are completely filled', exp: 'No node has only 1 child.', d: 'Medium' },
    { q: 'A Complete Binary Tree of height h is a binary tree in which:', c: 'All levels are completely filled except possibly the last, which is filled from left to right', w1: 'Every node has 2 children', w2: 'All leaves are at different depths', w3: 'No node has left children', exp: 'Basis for array-based binary heap implementation.', d: 'Medium' },
    { q: 'What is the property that defines a Binary Search Tree (BST)?', c: 'For every node X, all keys in its left subtree are < X.key, and all keys in its right subtree are > X.key', w1: 'All keys in the tree are equal', w2: 'The left subtree is always deeper than right subtree', w3: 'Children are stored in random order', exp: 'BST ordering invariant enables binary search.', d: 'Easy' },
    { q: 'Which tree traversal visits nodes in the order: Left Subtree, Root, Right Subtree?', c: 'In-order traversal', w1: 'Pre-order traversal', w2: 'Post-order traversal', w3: 'Level-order traversal', exp: 'LNR: Left, Node, Right.', d: 'Easy' },
    { q: 'Performing an In-order traversal on a Binary Search Tree (BST) visits the keys in:', c: 'Sorted ascending order', w1: 'Sorted descending order', w2: 'Reverse topological order', w3: 'Random order', exp: 'Direct consequence of the BST invariant.', d: 'Easy' },
    { q: 'Which tree traversal visits nodes in the order: Root, Left Subtree, Right Subtree?', c: 'Pre-order traversal (NLR)', w1: 'In-order traversal', w2: 'Post-order traversal', w3: 'Breadth-first traversal', exp: 'Pre-order visits the current node before its subtrees.', d: 'Easy' },
    { q: 'Which tree traversal visits nodes in the order: Left Subtree, Right Subtree, Root?', c: 'Post-order traversal (LRN)', w1: 'Pre-order traversal', w2: 'In-order traversal', w3: 'Level-order traversal', exp: 'Post-order visits children before their parent (used for deleting trees).', d: 'Easy' },
    { q: 'Level-order traversal of a binary tree visits nodes level by level using which data structure?', c: 'Queue (Breadth-First Search)', w1: 'Stack', w2: 'Priority Queue', w3: 'Hash Table', exp: 'BFS across tree levels requires a FIFO queue.', d: 'Easy' },
    { q: 'In the worst-case (skewed/degenerate tree), the time complexity to search in a BST is:', c: 'O(n)', w1: 'O(log n)', w2: 'O(1)', w3: 'O(n log n)', exp: 'Degenerates into a linked list when keys are inserted in sorted order.', d: 'Medium' },
    { q: 'What is an AVL Tree?', c: 'A self-balancing Binary Search Tree where the height difference between left and right subtrees (balance factor) is at most 1', w1: 'A tree where every node has 3 children', w2: 'A tree with all leaves on the left', w3: 'A binary heap', exp: 'Balance factor ∈ {-1, 0, +1} guarantees O(log n) worst-case height.', d: 'Medium' },
    { q: 'The worst-case time complexity for search, insertion, and deletion in an AVL tree of n nodes is:', c: 'O(log n)', w1: 'O(n)', w2: 'O(1)', w3: 'O(n²)', exp: 'Strict height balancing guarantees logarithmic operations.', d: 'Easy' },
    { q: 'Which rotations are used to rebalance an AVL tree after insertion or deletion?', c: 'Single rotations (LL, RR) and Double rotations (LR, RL)', w1: 'Only 360-degree rotations', w2: 'Heapify operations', w3: 'Color flipping only', exp: 'Four rebalancing cases restore the AVL invariant.', d: 'Medium' },
    { q: 'In a Max-Heap:', c: 'The key of every node is greater than or equal to the keys of its children, with maximum at the root', w1: 'The key of every node is less than its children', w2: 'Keys are sorted in in-order traversal', w3: 'Every node has at least 3 children', exp: 'Max-heap property.', d: 'Easy' },
    { q: 'In an array representation of a binary heap where root is at index 0, the left child of node at index i is at:', c: '2*i + 1', w1: '2*i', w2: 'i / 2', w3: '2*i + 2', exp: 'Left child = 2i + 1; Right child = 2i + 2; Parent = (i - 1)/2.', d: 'Easy' },
    { q: 'The time complexity to extract the maximum element (extractMax) from a binary Max-Heap of n elements is:', c: 'O(log n)', w1: 'O(1)', w2: 'O(n)', w3: 'O(n log n)', exp: 'Swapping root with last leaf and sinking down (heapify) takes O(log n).', d: 'Easy' },
    { q: 'Building a binary heap from an unsorted array of n elements using the bottom-up buildHeap algorithm takes:', c: 'O(n) time', w1: 'O(n log n)', w2: 'O(n²)', w3: 'O(log n)', exp: 'Sum of heights across all nodes converges to O(n).', d: 'Hard' },
    { q: 'A Hash Table provides average-case search, insertion, and deletion in time:', c: 'O(1) constant time', w1: 'O(log n)', w2: 'O(n)', w3: 'O(n log n)', exp: 'Direct array indexing via hash function yields O(1) average performance.', d: 'Easy' },
    { q: 'What is a hash collision in a hash table?', c: 'When two distinct keys produce the same hash code/index from the hash function', w1: 'When the hash table is empty', w2: 'When memory runs out', w3: 'When a key is deleted', exp: 'h(k₁) = h(k₂) for k₁ ≠ k₂.', d: 'Easy' },
    { q: 'In Separate Chaining collision resolution, colliding elements are stored in:', c: 'A linked list (or other container) at the corresponding hash bucket', w1: 'The next adjacent empty slot in the array', w2: 'A secondary hash table only', w3: 'They overwrite previous elements', exp: 'Each bucket heads a chain of colliding entries.', d: 'Easy' },
    { q: 'In Open Addressing with Linear Probing, when collision occurs at index i, the next slot checked is:', c: '(i + 1) % TABLE_SIZE', w1: '(i + 2) % TABLE_SIZE', w2: '(i + i²) % TABLE_SIZE', w3: 'i / 2', exp: 'Linearly scans successive slots: (i + 1), (i + 2), ...', d: 'Easy' },
    { q: 'What is the primary drawback of Linear Probing in hash tables?', c: 'Primary Clustering (long contiguous blocks of occupied slots build up, degrading performance)', w1: 'Secondary clustering only', w2: 'Infinite loops on empty table', w3: 'Excessive memory usage', exp: 'Clusters merge and lengthen insertion search times.', d: 'Medium' },
    { q: 'The load factor α of a hash table with n elements and m buckets is defined as:', c: 'α = n / m', w1: 'α = m / n', w2: 'α = n * m', w3: 'α = n - m', exp: 'Measure of table fullness; rehashing typically triggered when α > 0.7.', d: 'Easy' },
    { q: 'A Graph G = (V, E) consists of a set of vertices V and a set of:', c: 'Edges E connecting pairs of vertices', w1: 'Root nodes', w2: 'Leaves', w3: 'Arrays', exp: 'Graph definition.', d: 'Easy' },
    { q: 'Which graph representation is most space-efficient for a SPARSE graph (|E| << |V|²)?', c: 'Adjacency List (space O(|V| + |E|))', w1: 'Adjacency Matrix (space O(|V|²))', w2: 'Incidence Matrix', w3: 'Dense 2D array', exp: 'Adjacency list stores only existing edges.', d: 'Easy' },
    { q: 'Breadth-First Search (BFS) explores a graph level by level and finds:', c: 'The shortest path in terms of number of edges in an unweighted graph', w1: 'The minimum spanning tree in a weighted graph', w2: 'Topological sort order', w3: 'Strongly connected components directly', exp: 'BFS discovers nodes in order of increasing distance from start.', d: 'Medium' },
    { q: 'Depth-First Search (DFS) traverses as deep as possible before backtracking, using internally a:', c: 'Stack (or recursive call stack)', w1: 'FIFO Queue', w2: 'Priority Queue', w3: 'Hash Table', exp: 'DFS is a LIFO exploration strategy.', d: 'Easy' },
    { q: 'What is a Directed Acyclic Graph (DAG)?', c: 'A directed graph with no directed cycles', w1: 'An undirected graph with cycles', w2: 'A tree with multiple roots', w3: 'A complete graph', exp: 'Essential for scheduling and dependency resolution.', d: 'Easy' },
    { q: 'Topological Sort is an ordering of vertices in a DAG such that for every directed edge u → v:', c: 'Vertex u comes before vertex v in the ordering', w1: 'Vertex v comes before vertex u', w2: 'All vertices are visited in alphabetical order', w3: 'All leaf nodes come first', exp: 'Linear ordering respecting all precedence constraints.', d: 'Medium' },
    { q: 'Dijkstra\'s algorithm finds the shortest paths from a single source vertex to all other vertices in a weighted graph with:', c: 'NON-NEGATIVE edge weights only', w1: 'Negative edge weights allowed', w2: 'Negative cycles', w3: 'Unweighted graphs only', exp: 'Greedy approach fails if negative weights exist.', d: 'Medium' },
    { q: 'With a min-priority queue (binary heap), the time complexity of Dijkstra\'s algorithm is:', c: 'O((|V| + |E|) log |V|)', w1: 'O(|V|²)', w2: 'O(|V| * |E|)', w3: 'O(|V|³)', exp: 'log |V| for each extract-min and decrease-key operation.', d: 'Hard' },
    { q: 'Which algorithm can find single-source shortest paths in graphs that contain NEGATIVE edge weights (detecting negative cycles)?', c: 'Bellman-Ford algorithm', w1: 'Dijkstra\'s algorithm', w2: 'Kruskal\'s algorithm', w3: 'Prim\'s algorithm', exp: 'Relaxes all edges |V| - 1 times in O(|V| * |E|) time.', d: 'Medium' },
    { q: 'A Minimum Spanning Tree (MST) of a connected, undirected, weighted graph is a subgraph that:', c: 'Connects all |V| vertices with exactly |V| - 1 edges while minimizing total edge weight, with no cycles', w1: 'Has |V| edges', w2: 'Contains cycles', w3: 'Finds the longest path', exp: 'Definition of MST.', d: 'Easy' },
    { q: 'Kruskal\'s algorithm finds an MST by:', c: 'Sorting all edges in ascending order of weight and greedily adding edges that do not form a cycle (using Disjoint Set / Union-Find)', w1: 'Growing a tree from a single start vertex', w2: 'Running BFS from all vertices', w3: 'Removing minimum weight edges', exp: 'Greedy edge-centric approach running in O(|E| log |E|).', d: 'Medium' },
    { q: 'Prim\'s algorithm finds an MST by:', c: 'Starting from an arbitrary vertex and greedily adding the cheapest edge connecting the growing tree to a new vertex', w1: 'Sorting all edges first', w2: 'Using Bellman-Ford relaxation', w3: 'Connecting disconnected components randomly', exp: 'Vertex-centric greedy tree expansion.', d: 'Medium' },
    { q: 'What is the Disjoint Set (Union-Find) data structure used for in Kruskal\'s algorithm?', c: 'To check in near O(1) time whether two vertices belong to the same connected component (cycle detection)', w1: 'To sort edges', w2: 'To store weights', w3: 'To calculate shortest paths', exp: 'Union by rank and path compression provide α(n) near-constant time.', d: 'Hard' },
    { q: 'What is the worst-case time complexity of Quick Sort?', c: 'O(n²) (when pivot is repeatedly the smallest or largest element in an already sorted array)', w1: 'O(n log n)', w2: 'O(n)', w3: 'O(log n)', exp: 'Unbalanced partitions lead to n recursions of size n - 1.', d: 'Easy' },
    { q: 'What is the AVERAGE-CASE time complexity of Quick Sort?', c: 'O(n log n)', w1: 'O(n²)', w2: 'O(n)', w3: 'O(log n)', exp: 'Random or balanced pivots yield O(n log n) expected performance.', d: 'Easy' },
    { q: 'What is the time complexity of Merge Sort in ALL cases (best, average, and worst)?', c: 'O(n log n)', w1: 'O(n²)', w2: 'O(n)', w3: 'O(2^n)', exp: 'Divide-and-conquer splits in half (log n levels) and merges in O(n) per level.', d: 'Easy' },
    { q: 'What is the primary auxiliary space complexity of standard Merge Sort for an array of size n?', c: 'O(n) auxiliary space (not in-place)', w1: 'O(1)', w2: 'O(log n)', w3: 'O(n²)', exp: 'Requires temporary arrays to merge two sorted halves.', d: 'Easy' },
    { q: 'What is the time complexity of Heap Sort in worst case?', c: 'O(n log n) and it is an in-place sorting algorithm (O(1) space)', w1: 'O(n²)', w2: 'O(n)', w3: 'O(n log² n)', exp: 'Builds heap in O(n) and performs n extractMax operations in O(log n).', d: 'Medium' },
    { q: 'A sorting algorithm is called STABLE if:', c: 'It preserves the relative order of elements that have equal keys', w1: 'It runs in O(n log n) time', w2: 'It uses O(1) extra space', w3: 'It does not crash', exp: 'Equal elements remain in original sequence.', d: 'Easy' },
    { q: 'Which of the following sorting algorithms is STABLE by design?', c: 'Merge Sort (and Insertion Sort)', w1: 'Quick Sort (standard)', w2: 'Heap Sort', w3: 'Selection Sort', exp: 'Merge sort does not swap equal elements across distant indices.', d: 'Medium' },
    { q: 'What is the minimum number of comparisons needed to sort n elements in any comparison-based sorting algorithm in the worst case?', c: 'Ω(n log n)', w1: 'Ω(n)', w2: 'Ω(n²)', w3: 'Ω(log n)', exp: 'Decision tree of n! permutations has height at least log₂(n!) = Ω(n log n).', d: 'Hard' },
    { q: 'Counting Sort can achieve O(n + k) linear time complexity because:', c: 'It is a non-comparison based integer sorting algorithm that counts occurrences of each key', w1: 'It divides the array in half', w2: 'It uses a binary search tree', w3: 'It sorts floats in place', exp: 'Bypasses comparison lower bound by indexing direct counts.', d: 'Medium' },
    { q: 'Radix Sort sorts elements by:', c: 'Processing individual digits from least significant digit (LSD) to most significant digit (MSD) using a stable sub-sort', w1: 'Comparing adjacent elements', w2: 'Partitioning around a pivot', w3: 'Building a heap', exp: 'Digit-by-digit sorting in O(d * (n + b)) time.', d: 'Medium' },
    { q: 'What is the time complexity of Insertion Sort on an ALREADY SORTED array of size n?', c: 'O(n) (best case: only 1 comparison per element)', w1: 'O(n²)', w2: 'O(n log n)', w3: 'O(1)', exp: 'Inner while loop terminates immediately on each pass.', d: 'Easy' },
    { q: 'A Red-Black tree is a self-balancing binary search tree where every node is colored red or black, guaranteeing max height of:', c: '2 * log₂(n + 1)', w1: 'n', w2: 'log₂(n) / 2', w3: 'n / 2', exp: 'Black-height rules ensure path to deepest leaf is at most twice shortest path.', d: 'Hard' },
    { q: 'What is the maximum number of edges in a simple undirected graph with n vertices?', c: 'n(n - 1) / 2', w1: 'n²', w2: 'n(n + 1) / 2', w3: '2n', exp: 'Every vertex can connect to n - 1 other vertices: n(n-1)/2.', d: 'Easy' }
  ];

  dsMid.forEach((it, idx) => qs.push(createQuestion(`DS-MID-${String(idx + 1).padStart(3, '0')}`, 'subj-datastruct', false, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'Data Struct. Mid Exam.pdf', idx)));
  dsFinal.forEach((it, idx) => qs.push(createQuestion(`DS-FIN-${String(idx + 1).padStart(3, '0')}`, 'subj-datastruct', true, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'FINAL data -Algorithms .pdf', idx)));

  // ==========================================
  // ASSEMBLY LANGUAGE (subj-assembly)
  // Mid: 32 (8086 Architecture, General registers, Segment registers, Pointer/Index registers, FLAGS, Addressing modes, MOV, ADD, SUB, INC, DEC, JMP, CMP, Conditional jumps)
  // Final: 52 (MUL, DIV, Bitwise AND/OR/XOR/NOT, Shifts/Rotates, Stack PUSH/POP, CALL/RET, Procedures, Interrupts INT 21h, String instructions LODSB/STOSB, Macros)
  // ==========================================
  const asmMid = [
    { q: 'The Intel 8086 microprocessor has an internal bus and registers of size:', c: '16 bits', w1: '8 bits', w2: '32 bits', w3: '64 bits', exp: '8086 is a classic 16-bit microprocessor.', d: 'Easy' },
    { q: 'How many address lines does the 8086 processor have, and what is its maximum physical memory space?', c: '20 address lines, allowing 1 MB (2²⁰ bytes) of physical memory', w1: '16 lines, allowing 64 KB', w2: '24 lines, allowing 16 MB', w3: '32 lines, allowing 4 GB', exp: '2²⁰ = 1,048,576 bytes = 1 MB.', d: 'Easy' },
    { q: 'How is a 20-bit physical address calculated from a Segment register and an Offset in 8086?', c: 'Physical Address = (Segment * 16) + Offset = (Segment << 4) + Offset', w1: 'Physical Address = Segment + Offset', w2: 'Physical Address = (Segment * 256) + Offset', w3: 'Physical Address = Segment * Offset', exp: 'Segment is shifted left by 4 bits (multiplied by 10h = 16) and added to offset.', d: 'Medium' },
    { q: 'If CS = 2000h and IP = 0100h, what is the physical memory address of the next instruction to fetch?', c: '20100h', w1: '20010h', w2: '21000h', w3: '20001h', exp: '(2000h * 10h) + 0100h = 20000h + 0100h = 20100h.', d: 'Easy' },
    { q: 'Which 8086 register acts as the primary Accumulator for arithmetic and I/O operations?', c: 'AX (AH and AL)', w1: 'BX', w2: 'CX', w3: 'DX', exp: 'AX is the dedicated 16-bit Accumulator register.', d: 'Easy' },
    { q: 'Which register is specifically used as a default loop counter by the LOOP instruction in 8086?', c: 'CX (Count register)', w1: 'AX', w2: 'BX', w3: 'DX', exp: 'LOOP instruction automatically decrements CX until it reaches 0.', d: 'Easy' },
    { q: 'Which general-purpose register is commonly used as a Base register for memory addressing?', c: 'BX (Base register)', w1: 'AX', w2: 'CX', w3: 'DX', exp: 'BX can be enclosed in brackets [BX] for base addressing.', d: 'Easy' },
    { q: 'Which register pair holds the 32-bit product of a 16-bit multiplication in 8086?', c: 'DX:AX (DX holds high 16 bits, AX holds low 16 bits)', w1: 'AX:BX', w2: 'CX:AX', w3: 'BX:DX', exp: 'AX * operand produces DX:AX result.', d: 'Medium' },
    { q: 'The Instruction Pointer register (IP) holds:', c: 'The offset of the next machine instruction to be fetched from the Code Segment (CS)', w1: 'The address of the current stack frame', w2: 'The result of the last arithmetic operation', w3: 'The interrupt vector', exp: 'CS:IP points to the next instruction byte.', d: 'Easy' },
    { q: 'Which 8086 Segment register is paired by default with the Stack Pointer (SP)?', c: 'SS (Stack Segment)', w1: 'CS (Code Segment)', w2: 'DS (Data Segment)', w3: 'ES (Extra Segment)', exp: 'The active stack is located at SS:SP.', d: 'Easy' },
    { q: 'Which Segment register is used by default for data access with instructions like MOV AX, [SI]?', c: 'DS (Data Segment)', w1: 'CS', w2: 'SS', w3: 'ES', exp: 'DS is the default segment for general data offsets.', d: 'Easy' },
    { q: 'What are SI and DI registers in 8086?', c: 'Source Index (SI) and Destination Index (DI), used for string and memory indexing', w1: 'Segment registers', w2: 'Control registers', w3: 'Flag registers', exp: 'SI and DI serve as 16-bit index registers.', d: 'Easy' },
    { q: 'The Zero Flag (ZF) in the FLAGS register is set to 1 when:', c: 'The result of an arithmetic or logical operation is exactly zero', w1: 'The result is negative', w2: 'A carry occurs from the MSB', w3: 'An overflow occurs', exp: 'ZF = 1 if result == 0; ZF = 0 if result != 0.', d: 'Easy' },
    { q: 'The Sign Flag (SF) in 8086 is equal to:', c: 'The most significant bit (MSB) of the result (1 if negative, 0 if positive in two\'s complement)', w1: 'The least significant bit', w2: 'The parity of the result', w3: '1 when overflow happens', exp: 'SF mirrors bit 7 (for 8-bit) or bit 15 (for 16-bit).', d: 'Easy' },
    { q: 'The Carry Flag (CF) is set when:', c: 'There is an arithmetic carry out of or borrow into the most significant bit', w1: 'The result is zero', w2: 'A signed overflow occurs', w3: 'An interrupt is pending', exp: 'CF indicates unsigned arithmetic overflow.', d: 'Easy' },
    { q: 'The Overflow Flag (OF) is set when:', c: 'A signed arithmetic operation produces a result that exceeds the two\'s complement range', w1: 'An unsigned carry occurs', w2: 'The result is zero', w3: 'CX becomes zero', exp: 'OF detects signed overflow (e.g. adding two positive numbers yields negative).', d: 'Medium' },
    { q: 'Which addressing mode is used in the instruction: MOV AX, 1234h ?', c: 'Immediate Addressing', w1: 'Register Addressing', w2: 'Direct Addressing', w3: 'Register Indirect Addressing', exp: 'The operand value 1234h is directly encoded in the instruction.', d: 'Easy' },
    { q: 'Which addressing mode is used in: MOV AX, BX ?', c: 'Register Addressing', w1: 'Immediate Addressing', w2: 'Based Addressing', w3: 'Direct Addressing', exp: 'Both source and destination are processor registers.', d: 'Easy' },
    { q: 'Which addressing mode is used in: MOV AX, [1000h] ?', c: 'Direct Addressing', w1: 'Immediate Addressing', w2: 'Register Addressing', w3: 'Indexed Addressing', exp: 'A direct memory offset address [1000h] is specified.', d: 'Easy' },
    { q: 'Which addressing mode is used in: MOV AX, [BX] ?', c: 'Register Indirect Addressing', w1: 'Direct Addressing', w2: 'Immediate Addressing', w3: 'Base-Index Addressing', exp: 'Memory address is held inside a base or index register.', d: 'Easy' },
    { q: 'Which addressing mode is used in: MOV AX, [BX + SI + 4] ?', c: 'Based Indexed with Displacement Addressing', w1: 'Immediate Addressing', w2: 'Direct Addressing', w3: 'Relative Addressing', exp: 'Combines base register (BX), index register (SI), and constant displacement (4).', d: 'Medium' },
    { q: 'Which of the following MOV instructions is INVALID in 8086 assembly?', c: 'MOV [1000h], [2000h] (Memory-to-Memory transfer is not supported)', w1: 'MOV AX, [1000h]', w2: 'MOV [1000h], AX', w3: 'MOV BX, CX', exp: '8086 cannot move data directly from memory to memory in a single MOV.', d: 'Medium' },
    { q: 'Which instruction adds the contents of BX to AX and stores the sum in AX?', c: 'ADD AX, BX', w1: 'ADD BX, AX', w2: 'SUM AX, BX', w3: 'MOV AX, AX + BX', exp: 'Syntax is ADD destination, source (AX = AX + BX).', d: 'Easy' },
    { q: 'What does the instruction SUB AX, BX do?', c: 'AX = AX - BX, and updates FLAGS accordingly', w1: 'BX = BX - AX', w2: 'AX = BX - AX', w3: 'Compares without modifying AX', exp: 'Destination = Destination - Source.', d: 'Easy' },
    { q: 'What does the INC DX instruction do?', c: 'Increments DX by 1 without affecting the Carry Flag (CF)', w1: 'Increments DX by 2', w2: 'Sets CF to 1', w3: 'Divides DX by 2', exp: 'INC affects ZF, SF, OF, AF, PF but deliberately preserves CF.', d: 'Medium' },
    { q: 'What does the DEC CX instruction do?', c: 'Decrements CX by 1 without affecting the Carry Flag (CF)', w1: 'Decrements CX by 2', w2: 'Multiplies CX by 10', w3: 'Clears CX to 0', exp: 'DEC updates all arithmetic flags except CF.', d: 'Easy' },
    { q: 'What does the CMP AX, BX instruction do?', c: 'Performs AX - BX internally to set FLAGS, but does NOT modify AX or BX', w1: 'Stores the difference in AX', w2: 'Stores the difference in BX', w3: 'Jumps to a label immediately', exp: 'Compare instruction is a non-destructive subtraction for flag setting.', d: 'Easy' },
    { q: 'After CMP AX, BX, which conditional jump instruction jumps if AX is EQUAL to BX?', c: 'JE (Jump if Equal) or JZ (Jump if Zero)', w1: 'JNE (Jump if Not Equal)', w2: 'JG (Jump if Greater)', w3: 'JL (Jump if Less)', exp: 'If AX == BX, AX - BX = 0, so ZF = 1 (JE/JZ).', d: 'Easy' },
    { q: 'Which jump instruction is used for UNSIGNED comparison "Jump if Above" (AX > BX)?', c: 'JA (Jump if Above)', w1: 'JG (Jump if Greater)', w2: 'JGE', w3: 'JAE', exp: 'JA/JB are for unsigned numbers; JG/JL are for signed numbers.', d: 'Medium' },
    { q: 'Which jump instruction is used for SIGNED comparison "Jump if Greater" (AX > BX)?', c: 'JG (Jump if Greater)', w1: 'JA (Jump if Above)', w2: 'JB', w3: 'JNC', exp: 'JG checks (SF == OF) and ZF == 0 for signed values.', d: 'Medium' },
    { q: 'The unconditional jump instruction in 8086 is:', c: 'JMP label', w1: 'JE label', w2: 'CALL label', w3: 'RET', exp: 'JMP transfers control to target label unconditionally.', d: 'Easy' },
    { q: 'In an 8086 assembly program, the directive DB allocates:', c: 'Define Byte (1 byte of memory)', w1: 'Define Word (2 bytes)', w2: 'Define Doubleword (4 bytes)', w3: 'Define Bit', exp: 'DB = 1 byte, DW = 2 bytes, DD = 4 bytes.', d: 'Easy' }
  ];

  const asmFinal = [
    { q: 'The 8086 instruction MUL BL performs which operation?', c: 'AX = AL * BL (unsigned 8-bit multiplication with 16-bit result in AX)', w1: 'AL = AL * BL', w2: 'DX:AX = AX * BL', w3: 'BL = AL * BL', exp: 'Implicit multiplicand is AL; product is stored in AX.', d: 'Easy' },
    { q: 'The 8086 instruction MUL CX performs which operation?', c: 'DX:AX = AX * CX (unsigned 16-bit multiplication with 32-bit result in DX:AX)', w1: 'AX = AX * CX', w2: 'DX = AX * CX', w3: 'CX = AX * CX', exp: 'Product of 16-bit values resides in register pair DX:AX.', d: 'Medium' },
    { q: 'The instruction IMUL differs from MUL because IMUL performs:', c: 'Signed integer multiplication', w1: 'Immediate multiplication only', w2: 'Floating-point multiplication', w3: 'Modulo division', exp: 'MUL is unsigned; IMUL respects two\'s complement signed numbers.', d: 'Easy' },
    { q: 'When executing DIV BL (8-bit unsigned division), the dividend and quotient/remainder registers are:', c: 'Dividend is in AX; Quotient is stored in AL, Remainder in AH', w1: 'Dividend in AL; Quotient in AH', w2: 'Dividend in DX:AX; Quotient in AX', w3: 'Quotient in BL', exp: 'AX / BL => AL = quotient, AH = remainder.', d: 'Medium' },
    { q: 'When executing DIV CX (16-bit unsigned division), the dividend and results are:', c: 'Dividend is in DX:AX; Quotient is stored in AX, Remainder in DX', w1: 'Dividend in AX; Quotient in AL, Remainder in AH', w2: 'Dividend in CX; Quotient in DX', w3: 'Result in DX:AX', exp: '(DX:AX) / CX => AX = quotient, DX = remainder.', d: 'Medium' },
    { q: 'What happens if a DIV instruction in 8086 attempts division by zero or the quotient overflows?', c: 'Processor triggers Interrupt Type 0 (Divide Error / Divide by Zero Interrupt)', w1: 'Result is set to infinity', w2: 'Carry flag is set', w3: 'Program ignores the error', exp: 'INT 0 is the hardware divide error exception.', d: 'Medium' },
    { q: 'What does the AND AX, BX instruction do?', c: 'Performs bitwise logical AND between AX and BX, storing result in AX and clearing CF and OF', w1: 'Performs logical addition', w2: 'Swaps AX and BX', w3: 'Checks if AX equals BX', exp: 'Bitwise AND: result bit is 1 iff both operand bits are 1.', d: 'Easy' },
    { q: 'What does the OR AX, BX instruction do?', c: 'Performs bitwise logical OR between AX and BX, storing result in AX', w1: 'Bitwise XOR', w2: 'Adds the values', w3: 'Bitwise NOT', exp: 'Bitwise OR: result bit is 1 if either operand bit is 1.', d: 'Easy' },
    { q: 'What is the most efficient idiom to clear a register to zero in 8086 assembly (e.g. clear AX)?', c: 'XOR AX, AX', w1: 'MOV AX, 0', w2: 'SUB AX, AX', w3: 'AND AX, 0', exp: 'XOR AX, AX produces smaller machine code (2 bytes) and faster execution.', d: 'Easy' },
    { q: 'What does the TEST AX, BX instruction do?', c: 'Performs bitwise AND between AX and BX to update FLAGS (ZF, SF, PF), without altering AX or BX', w1: 'Stores the AND result in AX', w2: 'Compares AX with zero', w3: 'Jumps if equal', exp: 'Non-destructive bitwise AND used to check specific bit masks.', d: 'Medium' },
    { q: 'What does the NOT AX instruction do?', c: 'Performs bitwise one\'s complement (inverts all bits of AX) without modifying flags', w1: 'Calculates two\'s complement', w2: 'Multiplies by -1', w3: 'Clears all flags', exp: 'Inverts 0s to 1s and 1s to 0s.', d: 'Easy' },
    { q: 'What does the NEG AX instruction do?', c: 'Replaces the value of AX with its two\'s complement (arithmetic negation: AX = 0 - AX)', w1: 'Bitwise NOT', w2: 'Divides by -1', w3: 'Sets the sign flag only', exp: 'Calculates negative value: NEG 5 yields -5.', d: 'Easy' },
    { q: 'The instruction SHL AX, 1 (Shift Logical Left by 1) is equivalent to:', c: 'Multiplying AX by 2 (unsigned), shifting 0 into LSB and MSB into Carry Flag (CF)', w1: 'Dividing AX by 2', w2: 'Adding 1 to AX', w3: 'Rotating bits', exp: 'Left shift multiplies by powers of 2.', d: 'Easy' },
    { q: 'The instruction SHR AX, 1 (Shift Logical Right by 1) is equivalent to:', c: 'Unsigned division by 2, shifting 0 into MSB and LSB into Carry Flag (CF)', w1: 'Signed division by 2', w2: 'Multiplying by 2', w3: 'Inverting bits', exp: 'Zero-filled right shift for unsigned numbers.', d: 'Easy' },
    { q: 'The instruction SAR AX, 1 (Shift Arithmetic Right) differs from SHR because SAR:', c: 'Preserves the original sign bit by copying the MSB during right shift (signed division by 2)', w1: 'Inserts 0 at the MSB', w2: 'Inserts 1 at the LSB', w3: 'Rotates bits through carry', exp: 'Sign-extending right shift maintains negative signs.', d: 'Medium' },
    { q: 'The ROL AX, 1 (Rotate Left) instruction shifts bits left such that the bit shifted out of MSB is:', c: 'Rotated back into the LSB and also copied into the Carry Flag (CF)', w1: 'Discarded', w2: 'Replaced by 0', w3: 'Inverted', exp: 'Circular bit rotation.', d: 'Medium' },
    { q: 'In 8086, the stack grows in memory:', c: 'Downward from higher memory addresses to lower memory addresses', w1: 'Upward from lower to higher addresses', w2: 'Bidirectionally', w3: 'Horizontally', exp: 'Push decrements SP; pop increments SP.', d: 'Easy' },
    { q: 'When PUSH AX is executed in 8086:', c: 'SP is decremented by 2 (SP = SP - 2), and AX is written to memory at SS:SP', w1: 'SP is incremented by 2', w2: 'AX is written first, then SP is incremented', w3: 'SP is decremented by 1', exp: '16-bit word push decrements SP by 2 bytes.', d: 'Medium' },
    { q: 'When POP BX is executed in 8086:', c: 'The 16-bit word at SS:SP is copied into BX, and SP is incremented by 2 (SP = SP + 2)', w1: 'SP is decremented by 2', w2: 'SP is multiplied by 2', w3: 'The stack is cleared', exp: 'Pop retrieves the word and advances SP by 2 bytes.', d: 'Medium' },
    { q: 'What does the PUSHF instruction do?', c: 'Pushes the entire 16-bit FLAGS register onto the stack', w1: 'Pushes function arguments', w2: 'Pops flags', w3: 'Clears all flags', exp: 'Saves processor flags on stack.', d: 'Easy' },
    { q: 'What does the POPF instruction do?', c: 'Restores the 16-bit FLAGS register from the top of the stack', w1: 'Pushes flags', w2: 'Clears interrupts', w3: 'Sets zero flag', exp: 'Restores status flags from stack.', d: 'Easy' },
    { q: 'The CALL procedure_name instruction in 8086:', c: 'Pushes the return address (IP) onto the stack and jumps to the procedure', w1: 'Jumps without saving return address', w2: 'Pushes all general registers', w3: 'Halts the CPU', exp: 'Saves IP (and CS for far call) on stack before branch.', d: 'Easy' },
    { q: 'The RET instruction at the end of a procedure:', c: 'Pops the return address from the stack into IP and resumes execution at the calling site', w1: 'Terminates the program to DOS', w2: 'Clears the stack memory', w3: 'Returns 0 in AX', exp: 'Restores IP from stack.', d: 'Easy' },
    { q: 'A FAR procedure differs from a NEAR procedure because a FAR procedure:', c: 'Is located in a different code segment, so CALL/RET push and pop BOTH CS and IP', w1: 'Takes more arguments', w2: 'Executes faster', w3: 'Uses only 8-bit registers', exp: 'Inter-segment calls require 32-bit pointer (CS:IP).', d: 'Medium' },
    { q: 'What is the function of the Base Pointer register (BP) in stack operations?', c: 'To access function parameters and local variables on the stack without modifying SP', w1: 'To store return values', w2: 'To count loops', w3: 'To hold code addresses', exp: 'Forms standard stack frame: MOV BP, SP followed by [BP + 4], [BP - 2].', d: 'Medium' },
    { q: 'In 8086 MS-DOS programming, software interrupts are invoked using:', c: 'INT instruction (e.g. INT 21h)', w1: 'CALL 21h', w2: 'JMP 21h', w3: 'SYSCALL', exp: 'INT n triggers vector n in the Interrupt Vector Table (IVT).', d: 'Easy' },
    { q: 'What is the Interrupt Vector Table (IVT) in 8086?', c: 'A 1024-byte table at physical memory 00000h to 003FFh containing 256 4-byte interrupt service routine addresses (CS:IP)', w1: 'A table in the BIOS ROM only', w2: 'A list of hardware ports', w3: 'The CPU cache', exp: '256 interrupts x 4 bytes each = 1024 bytes (1 KB).', d: 'Hard' },
    { q: 'To terminate a program and return control to DOS via INT 21h, which service function is placed in AH?', c: 'AH = 4Ch (MOV AH, 4Ch; INT 21h)', w1: 'AH = 01h', w2: 'AH = 02h', w3: 'AH = 09h', exp: 'Service 4Ch is the DOS process exit function.', d: 'Easy' },
    { q: 'Which DOS INT 21h service prints a single character to the screen?', c: 'AH = 02h with character in DL (MOV AH, 02h; MOV DL, \'A\'; INT 21h)', w1: 'AH = 09h', w2: 'AH = 01h', w3: 'AH = 4Ch', exp: 'Function 02h outputs character in DL.', d: 'Easy' },
    { q: 'Which DOS INT 21h service displays a string terminated by a dollar sign (\'$\')?', c: 'AH = 09h with DX pointing to the string offset (MOV AH, 09h; LEA DX, msg; INT 21h)', w1: 'AH = 02h', w2: 'AH = 08h', w3: 'AH = 0Ah', exp: 'Function 09h prints $-terminated string at DS:DX.', d: 'Easy' },
    { q: 'Which DOS INT 21h service reads a single character from the keyboard with echo?', c: 'AH = 01h (character returned in AL)', w1: 'AH = 02h', w2: 'AH = 09h', w3: 'AH = 4Ch', exp: 'Function 01h waits for keypress and returns ASCII code in AL.', d: 'Easy' },
    { q: 'The instruction LEA DX, message performs which action?', c: 'Load Effective Address: computes and loads the offset address of message into DX', w1: 'Loads the content of message into DX', w2: 'Copies DX into message', w3: 'Allocates memory for message', exp: 'LEA loads offset without memory dereference.', d: 'Easy' },
    { q: 'What does the Direction Flag (DF) control in 8086 string operations?', c: 'Auto-increment (if DF = 0, CLD) or auto-decrement (if DF = 1, STD) of index registers SI and DI', w1: 'The sign of numbers', w2: 'The direction of jumps', w3: 'The speed of the CPU', exp: 'CLD sets forward processing; STD sets backward processing.', d: 'Medium' },
    { q: 'Which instruction clears the Direction Flag (sets DF = 0 for auto-increment)?', c: 'CLD', w1: 'STD', w2: 'CLI', w3: 'STI', exp: 'Clear Direction Flag.', d: 'Easy' },
    { q: 'Which instruction sets the Direction Flag (sets DF = 1 for auto-decrement)?', c: 'STD', w1: 'CLD', w2: 'STI', w3: 'CLI', exp: 'Set Direction Flag.', d: 'Easy' },
    { q: 'What does the LODSB instruction do in 8086?', c: 'Loads the byte at DS:SI into AL and automatically increments or decrements SI', w1: 'Stores AL into ES:DI', w2: 'Compares AL with memory', w3: 'Loads a 16-bit word into AX', exp: 'Load String Byte.', d: 'Medium' },
    { q: 'What does the STOSB instruction do in 8086?', c: 'Stores the byte from AL into ES:DI and automatically updates DI', w1: 'Loads byte into AL', w2: 'Pushes AL to stack', w3: 'Swaps AL with memory', exp: 'Store String Byte.', d: 'Medium' },
    { q: 'What does the MOVSB instruction do?', c: 'Copies byte from DS:SI to ES:DI and updates both SI and DI', w1: 'Copies word from AX to BX', w2: 'Moves bytes on stack', w3: 'Transfers code between segments', exp: 'Move String Byte.', d: 'Medium' },
    { q: 'The repeat prefix REP in front of a string instruction (e.g. REP MOVSB) repeats the operation until:', c: 'CX reaches 0 (decrementing CX on each step)', w1: 'AX reaches 0', w2: 'ZF is set', w3: 'Interrupt occurs', exp: 'Repeats string operations CX times.', d: 'Medium' },
    { q: 'The REPE (or REPZ) prefix repeats the string comparison instruction (e.g. CMPSB) as long as:', c: 'CX ≠ 0 AND Zero Flag ZF = 1 (elements are equal)', w1: 'CX == 0 only', w2: 'ZF == 0 only', w3: 'CF == 1', exp: 'Repeat while equal.', d: 'Medium' },
    { q: 'What is a macro in assembly language?', c: 'A named block of code expanded inline by the assembler preprocessor during compilation', w1: 'A procedure called at runtime via CALL and RET', w2: 'A system interrupt', w3: 'A hardware register', exp: 'Macros replace text at assemble time; procedures use stack at runtime.', d: 'Medium' },
    { q: 'How does a macro differ from a procedure in execution and memory?', c: 'A macro generates inline code every time it is invoked (larger code size, no CALL/RET overhead); a procedure exists in one memory location', w1: 'A macro is slower than a procedure', w2: 'A procedure cannot take parameters', w3: 'A macro uses the stack for return addresses', exp: 'Classic code size vs speed trade-off.', d: 'Medium' },
    { q: 'Which instruction disables maskable hardware interrupts in 8086 by clearing the Interrupt Flag (IF)?', c: 'CLI (Clear Interrupt Flag)', w1: 'STI', w2: 'CLD', w3: 'HLT', exp: 'CLI ignores INTR line.', d: 'Easy' },
    { q: 'Which instruction enables maskable hardware interrupts in 8086 by setting the Interrupt Flag (IF)?', c: 'STI (Set Interrupt Flag)', w1: 'CLI', w2: 'STD', w3: 'NOP', exp: 'STI responds to INTR line.', d: 'Easy' },
    { q: 'The NOP instruction in 8086 performs which action?', c: 'No Operation: consumes 1 byte and 3 clock cycles without modifying registers or flags', w1: 'Halts the computer permanently', w2: 'Clears all registers', w3: 'Jumps to start', exp: 'Used for timing delays or padding machine code.', d: 'Easy' },
    { q: 'The HLT instruction causes the 8086 processor to:', c: 'Halt execution and enter an idle state until an external interrupt or reset occurs', w1: 'Reboot the computer immediately', w2: 'Clear RAM', w3: 'Execute NOP infinitely', exp: 'Processor halts until hardware interrupt arrives.', d: 'Easy' },
    { q: 'In 8086, I/O ports are accessed using which dedicated instructions?', c: 'IN and OUT (e.g., IN AL, 60h; OUT 20h, AL)', w1: 'MOV and PUSH', w2: 'READ and WRITE', w3: 'LOAD and STORE', exp: 'Isolated I/O uses IN/OUT instructions.', d: 'Medium' },
    { q: 'What does the LOOP label instruction do in 8086?', c: 'Decrements CX by 1, and jumps to label if CX ≠ 0', w1: 'Increments CX and jumps', w2: 'Jumps if CX == 0', w3: 'Loops infinitely', exp: 'CX = CX - 1; if (CX != 0) goto label.', d: 'Easy' },
    { q: 'What is the function of the IRET instruction?', c: 'Returns from an Interrupt Service Routine by popping IP, CS, and FLAGS from the stack', w1: 'Returns from a normal procedure', w2: 'Resets the CPU', w3: 'Enables interrupts only', exp: 'IRET restores IP, CS, and FLAGS saved by INT.', d: 'Medium' },
    { q: 'A 16-bit word stored in memory at address 1000h as [12h, 34h] (where 12h is at 1000h and 34h is at 1001h) evaluates in little-endian to:', c: '3412h', w1: '1234h', w2: '12h', w3: '34h', exp: 'Little-endian: lower byte at lower address (12h is low byte, 34h is high byte => 3412h).', d: 'Hard' },
    { q: 'Which register can be used with XLAT (Translate) instruction to perform table lookups?', c: 'BX (holding table base address) and AL (holding index)', w1: 'AX and DX', w2: 'CX and SI', w3: 'SP and BP', exp: 'XLAT replaces AL with byte at DS:[BX + unsigned AL].', d: 'Hard' },
    { q: 'Which flag is set if the number of 1-bits in the low byte of an arithmetic result is EVEN?', c: 'Parity Flag (PF = 1)', w1: 'Zero Flag', w2: 'Auxiliary Carry Flag', w3: 'Sign Flag', exp: 'Even parity sets PF to 1.', d: 'Medium' }
  ];

  asmMid.forEach((it, idx) => qs.push(createQuestion(`ASM-MID-${String(idx + 1).padStart(3, '0')}`, 'subj-assembly', false, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'Mid Solutions.pdf', idx)));
  asmFinal.forEach((it, idx) => qs.push(createQuestion(`ASM-FIN-${String(idx + 1).padStart(3, '0')}`, 'subj-assembly', true, it.q, it.c, it.w1, it.w2, it.w3, it.exp, it.d, 'Final Lab Assembly 2024.pdf', idx)));

  return qs;
}

module.exports = { getDsAndAsmQuestions };
