/**
 * Master Academic Question Bank - Computer Science & Software Engineering
 * Language: English (as in university syllabus and original exam files)
 */

function makeQ(id, subjectId, quizId, question, optA, optB, optC, optD, correct, explanation, difficulty, imageUrl, sourceFile, sourcePage = 1) {
  return {
    id,
    subjectId,
    quizId,
    question,
    options: [
      { id: 'a', text: String(optA) },
      { id: 'b', text: String(optB) },
      { id: 'c', text: String(optC) },
      { id: 'd', text: String(optD) }
    ],
    correctAnswer: correct,
    explanation,
    difficulty: difficulty || 'Medium',
    imageUrl: imageUrl || null,
    sourceFile: sourceFile || 'Official University Exam Archive.pdf',
    sourcePage: sourcePage || 1,
    status: 'Verified',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  };
}

const midOf = (subjId) => `quiz-${subjId}-mid`;
const finalOf = (subjId) => `quiz-${subjId}-final`;

const csSoftwareQuestions = [
  // ==========================================
  // C++ PROGRAMMING (CS111) - ENGLISH
  // ==========================================
  makeQ('CPP-MID-001', 'subj-cpp', midOf('subj-cpp'), 'What is the output of the following C++ code snippet?\n\nint x = 10;\nint *p = &x;\n*p = 25;\ncout << x;', '25', '10', 'Address of x', 'Compilation Error', 'a', 'Pointer p holds the memory address of x. Dereferencing *p and assigning 25 directly modifies the value stored at x, printing 25.', 'Easy', null, 'Bara C-- Mid.pdf', 1),
  makeQ('CPP-MID-002', 'subj-cpp', midOf('subj-cpp'), 'Which of the following statements about C++ references is FALSE?', 'A reference can be rebound to point to another object after initialization.', 'A reference must be initialized when declared.', 'A reference cannot be NULL.', 'A reference shares the same memory address as the referent.', 'a', 'Once a reference is initialized in C++, it cannot be rebound to refer to another object. Reassigning assigns to the referred object.', 'Medium', null, 'Bara C-- Mid.pdf', 1),
  makeQ('CPP-MID-003', 'subj-cpp', midOf('subj-cpp'), 'What is the result of sizeof(char) in bytes according to the C++ standard?', '1', '2', '4', 'Depends on the CPU architecture', 'a', 'By definition in the C++ standard, sizeof(char) is guaranteed to be exactly 1 byte.', 'Easy', null, 'Bara C-- Mid.pdf', 2),
  makeQ('CPP-FIN-001', 'subj-cpp', finalOf('subj-cpp'), 'In C++, dynamically allocated memory using the \'new\' operator must be freed using:', 'delete (or delete[] for arrays)', 'free()', 'destructor call', 'garbage collector', 'a', 'Memory allocated dynamically with new must be deallocated using delete, or delete[] for dynamic arrays, to avoid memory leaks.', 'Easy', null, 'c-- Final.pdf', 1),
  makeQ('CPP-FIN-002', 'subj-cpp', finalOf('subj-cpp'), 'What happens when a base class destructor is NOT declared virtual in C++?', 'Deleting a derived object via a base class pointer results in undefined behavior (derived destructor not called).', 'Both base and derived destructors are always called properly.', 'A compilation error is generated.', 'Only the derived destructor executes.', 'a', 'Without a virtual destructor in the base class, deleting through a base pointer causes undefined behavior, often omitting derived cleanup.', 'Medium', null, 'c-- Final.pdf', 2),
  makeQ('CPP-FIN-003', 'subj-cpp', finalOf('subj-cpp'), 'Which access specifier makes members accessible ONLY within the class itself and its friend functions?', 'private', 'protected', 'public', 'package-private', 'a', 'Private members can only be accessed within member functions of the class and friend classes/functions.', 'Easy', null, 'c-- Final.pdf', 2),

  // ==========================================
  // OBJECT ORIENTED PROGRAMMING (OOP - CS211) - ENGLISH
  // ==========================================
  makeQ('OOP-MID-001', 'subj-oop', midOf('subj-oop'), 'Which OOP principle hides internal object state and requires all interaction to occur through public methods?', 'Encapsulation', 'Polymorphism', 'Inheritance', 'Abstraction', 'a', 'Encapsulation bundles data and methods together and protects internal state through access modifiers (private/protected).', 'Easy', null, '2023_2024\'s_Midterm_1st_Sem_pdf_20260905_165038_٠٠٠٠.pdf', 1),
  makeQ('OOP-MID-002', 'subj-oop', midOf('subj-oop'), 'When a class contains dynamically allocated memory, which of the following is essential to avoid shallow copy bugs?', 'Custom Copy Constructor and Copy Assignment Operator', 'Virtual default constructor', 'Friend function', 'Inline static destructor', 'a', 'Default memberwise copying results in shallow copies (double-free errors). A custom copy constructor performs deep copying of the heap memory.', 'Medium', null, '2023_2024\'s_Midterm_1st_Sem_pdf_20260905_165038_٠٠٠٠.pdf', 2),
  makeQ('OOP-MID-003', 'subj-oop', midOf('subj-oop'), 'In C++, what is a pure virtual function?', 'A virtual function assigned = 0 that has no implementation in the base class.', 'A function that cannot be overridden.', 'A static member function that accesses private data.', 'A function declared inside a template class.', 'a', 'A pure virtual function is declared with virtual void func() = 0;, which turns the enclosing class into an abstract class.', 'Easy', null, '2023_2024\'s_Midterm_1st_Sem_pdf_20260905_165038_٠٠٠٠.pdf', 3),
  makeQ('OOP-FIN-001', 'subj-oop', finalOf('subj-oop'), 'Runtime polymorphism in C++ is achieved through:', 'Virtual functions and Base class pointers/references', 'Function overloading at compile time', 'Template specialization', 'Multiple inheritance without virtual keyword', 'a', 'Runtime (dynamic) polymorphism requires virtual functions in base classes invoked through base pointers or references using a vtable.', 'Medium', null, '2023_2024’s_Final_2nd_Sem_Part_1_pdf_20260905_162903_٠٠٠٠.pdf', 1),
  makeQ('OOP-FIN-002', 'subj-oop', finalOf('subj-oop'), 'What is the Diamond Problem in object-oriented programming?', 'An ambiguity that arises when a class inherits from two classes that both inherit from the same common base class.', 'A stack overflow caused by recursive constructor calls.', 'An error caused by using four virtual functions in one class.', 'A deadlock in multi-threaded member functions.', 'a', 'The diamond problem occurs when class D inherits from B and C, both inheriting from A, creating duplicate copies of A. Solved by virtual inheritance.', 'Medium', null, '2023_2024’s_Final_2nd_Sem_Part_1_pdf_20260905_162903_٠٠٠٠.pdf', 2),

  // ==========================================
  // DATA STRUCTURES (CS212) - ENGLISH
  // ==========================================
  makeQ('DS-MID-001', 'subj-datastruct', midOf('subj-datastruct'), 'What is the time complexity to insert a new node at the HEAD of a singly linked list?', 'O(1)', 'O(n)', 'O(log n)', 'O(n²)', 'a', 'Inserting at head only requires creating a node, pointing its next to the current head, and updating head pointer, taking constant O(1) time.', 'Easy', null, 'Data mid.pdf', 1),
  makeQ('DS-MID-002', 'subj-datastruct', midOf('subj-datastruct'), 'Which data structure follows the Last-In, First-Out (LIFO) access principle?', 'Stack', 'Queue', 'Array', 'Linked List', 'a', 'A stack strictly enforces LIFO order: elements are pushed and popped from the same end (top).', 'Easy', null, 'Data mid.pdf', 1),
  makeQ('DS-MID-003', 'subj-datastruct', midOf('subj-datastruct'), 'In a circular queue implemented using an array of size N, the condition for a full queue is:', '(rear + 1) % N == front', 'rear == front', 'rear == N - 1', 'front == 0', 'a', 'In a circular array queue of capacity N, one slot is kept empty to distinguish full from empty: (rear + 1) % N == front indicates full.', 'Medium', null, 'Data mid.pdf', 2),
  makeQ('DS-FIN-001', 'subj-datastruct', finalOf('subj-datastruct'), 'In a Binary Search Tree (BST), which traversal produces the keys in ascending sorted order?', 'In-order traversal', 'Pre-order traversal', 'Post-order traversal', 'Level-order traversal', 'a', 'In-order traversal visits (Left, Root, Right). Since BST ensures Left < Root < Right, in-order traversal yields elements in sorted order.', 'Easy', null, 'Final #1.pdf', 1),
  makeQ('DS-FIN-002', 'subj-datastruct', finalOf('subj-datastruct'), 'What is the worst-case time complexity of QuickSort?', 'O(n²)', 'O(n log n)', 'O(log n)', 'O(n)', 'a', 'When the pivot selection consistently picks the smallest or largest element (e.g. sorted array with first element as pivot), QuickSort degrades to O(n²).', 'Medium', null, 'Final #1.pdf', 1),
  makeQ('DS-FIN-003', 'subj-datastruct', finalOf('subj-datastruct'), 'Which of the following data structures is typically used to implement Breadth-First Search (BFS) in a graph?', 'Queue', 'Stack', 'Priority Queue', 'Binary Tree', 'a', 'BFS explores vertices level by level, requiring a FIFO Queue to process vertices in the order they are discovered.', 'Easy', null, 'Final #1.pdf', 2),

  // ==========================================
  // ASSEMBLY LANGUAGE (CS221) - ENGLISH
  // ==========================================
  makeQ('ASM-MID-001', 'subj-assembly', midOf('subj-assembly'), 'In x86 assembly, which general-purpose register is conventionally used as the loop counter with the LOOP instruction?', 'ECX (or CX)', 'EAX', 'EBX', 'EDX', 'a', 'The x86 LOOP instruction automatically decrements ECX (or CX) and jumps to the target label if ECX ≠ 0.', 'Easy', null, 'assembly-mid 2020-SOLUTION -2.pdf', 1),
  makeQ('ASM-MID-002', 'subj-assembly', midOf('subj-assembly'), 'What is the effect of executing: XOR EAX, EAX?', 'Clears EAX to 0 and sets the Zero Flag (ZF = 1)', 'Inverts all bits in EAX', 'Loads EAX with -1', 'Throws an invalid operand exception', 'a', 'XORing any register with itself produces all 0 bits, effectively clearing EAX to 0 and setting the Zero Flag ZF = 1 with fewer opcode bytes than MOV EAX, 0.', 'Easy', null, 'assembly-mid 2020-SOLUTION -2.pdf', 1),
  makeQ('ASM-MID-003', 'subj-assembly', midOf('subj-assembly'), 'Which flag is set when an arithmetic operation results in an unsigned arithmetic carry or borrow?', 'Carry Flag (CF)', 'Overflow Flag (OF)', 'Sign Flag (SF)', 'Parity Flag (PF)', 'a', 'The Carry Flag (CF) reflects unsigned arithmetic overflow/underflow, whereas the Overflow Flag (OF) reflects signed arithmetic overflow.', 'Medium', null, 'assembly-mid 2020-SOLUTION -2.pdf', 2),
  makeQ('ASM-FIN-001', 'subj-assembly', finalOf('subj-assembly'), 'In 8086 real mode, how is the physical 20-bit memory address calculated from a Segment:Offset pair?', 'Physical Address = (Segment * 16) + Offset', 'Physical Address = Segment + Offset', 'Physical Address = (Segment * 256) + Offset', 'Physical Address = Segment + (Offset * 16)', 'a', 'The 8086 processor computes a 20-bit physical address by shifting the 16-bit segment register 4 bits left (* 16) and adding the 16-bit offset.', 'Easy', null, 'Final Lab Assembly 2024.pdf', 1),
  makeQ('ASM-FIN-002', 'subj-assembly', finalOf('subj-assembly'), 'Which instruction pushes the current Instruction Pointer (EIP) onto the stack and jumps to the procedure label?', 'CALL', 'RET', 'JMP', 'INT', 'a', 'CALL pushes the return address (next instruction) onto the stack and transfers control; RET later pops it back into EIP.', 'Easy', null, 'Final Lab Assembly 2024.pdf', 2),

  // ==========================================
  // COMPUTER ARCHITECTURE (CS322) - ENGLISH
  // ==========================================
  makeQ('ARCH-MID-001', 'subj-arch', midOf('subj-arch'), 'In a classic 5-stage RISC instruction pipeline, what are the five pipeline stages in execution order?', 'IF, ID, EX, MEM, WB', 'ID, IF, EX, WB, MEM', 'IF, EX, ID, MEM, WB', 'IF, ID, MEM, EX, WB', 'a', 'Standard 5-stage RISC pipeline order: Instruction Fetch (IF), Instruction Decode / Register Read (ID), Execution / ALU (EX), Memory Access (MEM), Write Back (WB).', 'Easy', null, 'Mid T1.(2023-2024).pdf', 1),
  makeQ('ARCH-MID-002', 'subj-arch', midOf('subj-arch'), 'Which type of pipeline hazard occurs when an instruction depends on the result of a previous instruction that is still in the pipeline?', 'Data Hazard (Read-After-Write RAW)', 'Structural Hazard', 'Control Hazard', 'Branch Misprediction Hazard', 'a', 'Data hazards occur when data dependencies between overlapping instructions arise (e.g. Read-After-Write RAW).', 'Medium', null, 'Mid T1.(2023-2024).pdf', 2),
  makeQ('ARCH-FIN-001', 'subj-arch', finalOf('subj-arch'), 'Amdahl\'s Law states that the overall speedup of a system when enhancing a specific fraction f by a factor k is:', 'Speedup = 1 / [(1 - f) + (f / k)]', 'Speedup = (1 - f) + k * f', 'Speedup = k / (1 - f)', 'Speedup = 1 / (f * k)', 'a', 'Amdahl\'s Law formula is 1 / [(1 - f) + f/k], showing that speedup is limited by the serial (unaccelerated) fraction.', 'Medium', null, 'Final Computer Architecture.pdf', 1),
  makeQ('ARCH-FIN-002', 'subj-arch', finalOf('subj-arch'), 'In cache memory mapping, which design allows a block of main memory to be placed in ANY cache line?', 'Fully Associative Mapping', 'Direct Mapping', '2-Way Set Associative', 'Paged Mapping', 'a', 'In Fully Associative mapping, a block can be loaded into any available cache slot, minimizing conflict misses at the expense of search hardware.', 'Easy', null, 'Final Computer Architecture.pdf', 2),

  // ==========================================
  // ARTIFICIAL INTELLIGENCE (AI301) - ENGLISH
  // ==========================================
  makeQ('AI-MID-001', 'subj-ai', midOf('subj-ai'), 'Which search algorithm evaluates nodes using the evaluation function f(n) = g(n) + h(n)?', 'A* Search', 'Greedy Best-First Search', 'Depth-First Search', 'Uniform Cost Search', 'a', 'A* search uses f(n) = g(n) + h(n), where g(n) is the exact cost from start to n, and h(n) is the heuristic estimated cost from n to goal.', 'Easy', null, 'Final (1).pdf', 1),
  makeQ('AI-MID-002', 'subj-ai', midOf('subj-ai'), 'A heuristic function h(n) in A* search is called "admissible" if:', 'It never overestimates the actual true cost to reach the goal.', 'It is always strictly equal to 0.', 'It guarantees finding a solution with O(1) memory.', 'It overestimates cost to speed up pruning.', 'a', 'An admissible heuristic h(n) ≤ h*(n) ensures A* tree search is always optimal.', 'Medium', null, 'Final (1).pdf', 1),
  makeQ('AI-FIN-001', 'subj-ai', finalOf('subj-ai'), 'In adversarial two-player zero-sum games, what is the primary purpose of Alpha-Beta pruning in the Minimax algorithm?', 'To prune away branches of the search tree that cannot possibly influence the final minimax decision, without altering the result.', 'To guarantee that player 1 always wins.', 'To replace the heuristic evaluation function with dynamic programming.', 'To allow depth-first search to run in polynomial time.', 'a', 'Alpha-Beta pruning removes irrelevant nodes from evaluation while returning the exact same optimal minimax value.', 'Medium', null, 'Final (1).pdf', 2),
  makeQ('AI-FIN-002', 'subj-ai', finalOf('subj-ai'), 'Which inference rule in propositional logic states: if P → Q is true and P is true, then Q must be true?', 'Modus Ponens', 'Modus Tollens', 'Resolution', 'De Morgan\'s Law', 'a', 'Modus Ponens is the fundamental deductive rule: given P and P → Q, conclude Q.', 'Easy', null, 'Final (1).pdf', 2),

  // ==========================================
  // MACHINE LEARNING (AI411) - ENGLISH
  // ==========================================
  makeQ('ML-MID-001', 'subj-machine', midOf('subj-machine'), 'In supervised learning, what is the primary difference between Regression and Classification?', 'Regression predicts continuous numeric values, while Classification predicts discrete categorical labels.', 'Regression uses unlabeled data, while Classification uses labeled data.', 'Regression is unsupervised, while Classification is supervised.', 'Regression cannot use gradient descent.', 'a', 'Regression tasks predict continuous target variables, whereas Classification tasks predict class memberships.', 'Easy', null, 'Machines TEST BANK By MAE.pdf', 1),
  makeQ('ML-MID-002', 'subj-machine', midOf('subj-machine'), 'What activation function is commonly used at the output layer of a binary classification logistic regression model?', 'Sigmoid function: σ(z) = 1 / (1 + e^(-z))', 'ReLU function: max(0, z)', 'Linear identity function', 'Softmax over 10 classes', 'a', 'The sigmoid function squashes any real-valued input into the range (0, 1), representing a valid probability for binary classification.', 'Easy', null, 'Machines TEST BANK By MAE.pdf', 2),
  makeQ('ML-FIN-001', 'subj-machine', finalOf('subj-machine'), 'High variance in a machine learning model is a clear symptom of:', 'Overfitting (model memorizes training noise and fails to generalize)', 'Underfitting (model is too simplistic)', 'High bias and low capacity', 'Data leakage during normalization', 'a', 'High variance indicates the model is overly complex and captures random noise from the training set, performing poorly on unseen validation data (overfitting).', 'Medium', null, 'فاينل ماشين مهم.pdf', 1),
  makeQ('ML-FIN-002', 'subj-machine', finalOf('subj-machine'), 'Which regularization technique adds the sum of absolute values of weights (L1 norm) to the loss function, promoting feature sparsity?', 'Lasso Regularization (L1)', 'Ridge Regularization (L2)', 'ElasticNet without L1 penalty', 'Dropout', 'a', 'L1 (Lasso) regularization adds λ Σ|w_i| to the loss, driving non-essential coefficients exactly to 0 and providing automatic feature selection.', 'Medium', null, 'فاينل ماشين مهم.pdf', 2),

  // ==========================================
  // COMPUTER SKILLS (CS100) - ENGLISH
  // ==========================================
  makeQ('CS100-MID-001', 'subj-skills', midOf('subj-skills'), 'Which component of a computer system is responsible for performing arithmetic calculations and logical decisions?', 'ALU (Arithmetic Logic Unit)', 'RAM (Random Access Memory)', 'Hard Disk Drive', 'Control Bus', 'a', 'The ALU inside the CPU performs all elementary mathematical operations (addition, subtraction) and logical comparisons (AND, OR, NOT).', 'Easy', null, 'islamاسئلة_سنوات_مد_مهاراة_الحاسوب_والتعلم_الالكترو_1.pdf', 1),
  makeQ('CS100-MID-002', 'subj-skills', midOf('subj-skills'), 'In spreadsheet applications (such as Microsoft Excel), what does the formula =SUM(B2:B6) compute?', 'The total sum of values in cells B2, B3, B4, B5, and B6.', 'The average of cells B2 and B6.', 'The count of non-empty cells in row B.', 'The maximum value in column B.', 'a', 'The SUM function with range B2:B6 adds together all numeric values from cell B2 down to B6 inclusive.', 'Easy', null, 'islamاسئلة_سنوات_مد_مهاراة_الحاسوب_والتعلم_الالكترو_1.pdf', 2),
  makeQ('CS100-FIN-001', 'subj-skills', finalOf('subj-skills'), 'What does the abbreviation "URL" stand for in web browsing?', 'Uniform Resource Locator', 'Universal Routing Link', 'Unified Register Language', 'User Requested Location', 'a', 'URL stands for Uniform Resource Locator, standardizing addresses used to access web resources over HTTP/HTTPS.', 'Easy', null, 'فاينل مهارات حاسوب (1).pdf', 1),
  makeQ('CS100-FIN-002', 'subj-skills', finalOf('subj-skills'), 'Convert the binary number (1011)₂ to its decimal equivalent:', '11', '13', '9', '7', 'a', '(1011)₂ = 1*(2³) + 0*(2²) + 1*(2¹) + 1*(2⁰) = 8 + 0 + 2 + 1 = 11.', 'Easy', null, 'فاينل مهارات حاسوب (1).pdf', 2),

  // --- ADDITIONAL C++ QUESTIONS ---
  makeQ('CPP-MID-004', 'subj-cpp', midOf('subj-cpp'), 'Which C++ cast operator is designed for safe downcasting in an inheritance hierarchy with polymorphic types at runtime?', 'dynamic_cast', 'static_cast', 'reinterpret_cast', 'const_cast', 'a', 'dynamic_cast safely converts pointers or references up, down, and across inheritance hierarchies, verifying types at runtime via RTTI.', 'Medium', null, 'Bara C-- Mid.pdf', 2),
  makeQ('CPP-FIN-004', 'subj-cpp', finalOf('subj-cpp'), 'What happens when a std::vector exceeds its current capacity during a push_back() operation in C++?', 'It allocates a new larger memory block (typically doubling capacity), copies/moves existing elements, and frees old memory.', 'It throws an OutOfMemory compilation error.', 'It automatically converts itself into a linked list.', 'It drops the oldest element in FIFO order.', 'a', 'std::vector achieves amortized O(1) insertion by geometric resizing: doubling capacity and transferring existing elements.', 'Medium', null, 'c-- Final.pdf', 2),

  // --- ADDITIONAL OOP QUESTIONS ---
  makeQ('OOP-MID-004', 'subj-oop', midOf('subj-oop'), 'What is the function of the "this" pointer in C++ member functions?', 'An implicit constant pointer to the invoking object instance passed to non-static member functions.', 'A pointer to the base class vtable.', 'A static pointer to the main() function.', 'A global variable holding class metadata.', 'a', 'The this pointer is an implicit parameter passed to all non-static member functions pointing to the object instance invoking the function.', 'Easy', null, '2023_2024\'s_Midterm_1st_Sem_pdf_20260905_165038_٠٠٠٠.pdf', 2),
  makeQ('OOP-FIN-003', 'subj-oop', finalOf('subj-oop'), 'In object-oriented design, which principle states that high-level modules should not depend on low-level modules, but both should depend on abstractions?', 'Dependency Inversion Principle (DIP)', 'Single Responsibility Principle', 'Liskov Substitution Principle', 'Open-Closed Principle', 'a', 'The Dependency Inversion Principle (the D in SOLID) states that systems should decouple modules by programming to abstract interfaces.', 'Medium', null, '2023_2024’s_Final_2nd_Sem_Part_1_pdf_20260905_162903_٠٠٠٠.pdf', 2),

  // --- ADDITIONAL DATA STRUCTURES QUESTIONS ---
  makeQ('DS-MID-004', 'subj-datastruct', midOf('subj-datastruct'), 'What is the average and worst-case time complexity of searching for an element in a Hash Table with good collision handling?', 'Average O(1), Worst-case O(n)', 'Average O(log n), Worst-case O(n log n)', 'Average O(1), Worst-case O(1)', 'Average O(n), Worst-case O(n²)', 'a', 'Hash tables provide O(1) average lookup when keys distribute uniformly, but degrade to O(n) if all keys hash to the same bucket (worst-case).', 'Medium', null, 'Data mid.pdf', 2),
  makeQ('DS-FIN-004', 'subj-datastruct', finalOf('subj-datastruct'), 'Which graph algorithm computes single-source shortest paths on weighted directed graphs with non-negative edge weights?', 'Dijkstra\'s Algorithm', 'Kruskal\'s Algorithm', 'Floyd-Warshall Algorithm', 'Tarjan\'s Algorithm', 'a', 'Dijkstra\'s algorithm greedily extracts vertices with minimum tentative distance from a Priority Queue in O((V + E) log V) time.', 'Easy', null, 'Final #1.pdf', 2),

  // --- ADDITIONAL COMPUTER ARCHITECTURE QUESTIONS ---
  makeQ('ARCH-MID-003', 'subj-arch', midOf('subj-arch'), 'In a 32-bit byte-addressed architecture with a 16 KB direct-mapped cache and 64-byte cache lines, how many bits are used for the block OFFSET and INDEX fields?', 'Offset = 6 bits (2⁶=64), Index = 8 bits (256 cache lines)', 'Offset = 4 bits, Index = 10 bits', 'Offset = 8 bits, Index = 8 bits', 'Offset = 6 bits, Index = 14 bits', 'a', 'Block size = 64 bytes = 2⁶ => 6 offset bits. Total blocks = 16 KB / 64 B = 16384 / 64 = 256 = 2⁸ => 8 index bits. Remaining 32 - 14 = 18 bits are Tag.', 'Medium', null, 'Mid T1.(2023-2024).pdf', 2),
  makeQ('ARCH-FIN-003', 'subj-arch', finalOf('subj-arch'), 'What is the primary function of "Data Forwarding" (bypassing) in a pipelined CPU design?', 'To route computed ALU results directly to waiting pipeline stages without waiting for Write-Back to the register file.', 'To speed up instruction fetching from L2 cache.', 'To reorder branches dynamically.', 'To double the clock frequency.', 'a', 'Forwarding connects internal pipeline register outputs directly to ALU inputs, eliminating RAW data hazard stalls.', 'Medium', null, 'Final Computer Architecture.pdf', 2),

  // --- ADDITIONAL ARTIFICIAL INTELLIGENCE QUESTIONS ---
  makeQ('AI-MID-003', 'subj-ai', midOf('subj-ai'), 'Which uninformed search algorithm is guaranteed to find the shallowest goal node in a state space with uniform edge costs?', 'Breadth-First Search (BFS)', 'Depth-First Search (DFS)', 'Depth-Limited Search', 'Bidirectional DFS', 'a', 'BFS visits nodes in order of depth from the root, guaranteeing that the first time a goal is dequeued it is at minimum depth.', 'Easy', null, 'Final (1).pdf', 1),
  makeQ('AI-FIN-003', 'subj-ai', finalOf('subj-ai'), 'In Constraint Satisfaction Problems (CSP), what does the Arc Consistency algorithm (AC-3) enforce?', 'Every value in the domain of variable X has at least one valid supporting value in the domain of variable Y satisfying constraint (X, Y).', 'All variables are assigned numeric integers.', 'Every variable has exactly one remaining domain value.', 'The constraint graph is planar.', 'a', 'AC-3 eliminates values from variable domains that cannot participate in any valid solution across constrained arcs.', 'Medium', null, 'Final (1).pdf', 2),

  // --- ADDITIONAL MACHINE LEARNING QUESTIONS ---
  makeQ('ML-MID-003', 'subj-machine', midOf('subj-machine'), 'In evaluation of classification models, how is "Precision" defined from a confusion matrix?', 'Precision = True Positives / (True Positives + False Positives)', 'Precision = True Positives / (True Positives + False Negatives)', 'Precision = (True Positives + True Negatives) / Total', 'Precision = False Positives / True Positives', 'a', 'Precision measures the ratio of correct positive predictions to total predicted positives: TP / (TP + FP).', 'Medium', null, 'Machines TEST BANK By MAE.pdf', 2),
  makeQ('ML-FIN-003', 'subj-machine', finalOf('subj-machine'), 'What is the objective function optimized by the K-Means clustering algorithm?', 'Minimizing Within-Cluster Sum of Squares (WCSS / Inertia)', 'Maximizing Euclidean distance between all data points', 'Minimizing the number of clusters K to 1', 'Maximizing cross-entropy loss', 'a', 'K-Means iteratively partitions n observations into k clusters to minimize the sum of squared distances to cluster centroids (Inertia).', 'Medium', null, 'فاينل ماشين مهم.pdf', 2),

  // --- ADDITIONAL COMPUTER SKILLS QUESTIONS ---
  makeQ('CS100-MID-003', 'subj-skills', midOf('subj-skills'), 'How many total unique bit addresses can be indexed by a 32-bit IPv4 address versus a 128-bit IPv6 address?', 'IPv4 has 2³² addresses (~4.3 billion), whereas IPv6 has 2¹²⁸ addresses (~3.4 x 10³⁸).', 'IPv4 has 2⁶⁴ addresses, IPv6 has 2²⁵⁶ addresses.', 'IPv4 and IPv6 have the same address pool size.', 'IPv4 has 32 million addresses.', 'a', 'IPv4 uses 32-bit addresses (2³² ≈ 4.29 billion). IPv6 expands the address space to 128 bits (2¹²⁸ ≈ 3.4 x 10³⁸).', 'Easy', null, 'islamاسئلة_سنوات_مد_مهاراة_الحاسوب_والتعلم_الالكترو_1.pdf', 2),
  makeQ('CS100-FIN-003', 'subj-skills', finalOf('subj-skills'), 'In Microsoft Excel, what is the default behavior of the VLOOKUP function when the range_lookup parameter is FALSE?', 'It searches for an exact match to the lookup value in the first column of the table array.', 'It performs an approximate binary search on unsorted data.', 'It returns the average of the range.', 'It looks up values from right to left only.', 'a', 'Setting range_lookup = FALSE in VLOOKUP strictly searches for an exact match, returning #N/A if not found.', 'Easy', null, 'فاينل مهارات حاسوب (1).pdf', 2)
];

module.exports = { csSoftwareQuestions };
